In [1]:
import os
import pandas as pd

In [3]:
# Ruta del archivo
ruta = r"C:\Users\1513873\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Medios Virtuales\SMS ENVIADOS EN ENERO\CONSOLIDADO SMS ENERO.xlsx"

# Leer todas las hojas
hojas = pd.read_excel(ruta, sheet_name=None)

# Concatenar todas las hojas en un solo DataFrame
df = pd.concat(hojas.values(), ignore_index=True)

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [54]:
df['TIPO DOCUMENTO'] = df['TIPO DOCUMENTO'].str.upper()

In [53]:
df = df.rename(columns={
    'DESC_DOCUMENTO':'TIPO DOCUMENTO',
    'NRO_COMPARENDO':'NRO COMPARENDO',
    'ID_USUARIO':'DOCUMENTO',
    'NOMBRES':'NOMBRE',
    'CELULAR 1':'TELEFONO',
    'SMS':'TEXTO',
    'NOMBRE':'BASE',
    'FECHA':'FECHA ENVIO',
    'RESULTADO SMS':'RESULTADO SMS'
})

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1484484 entries, 0 to 1484483
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   TIPO DOCUMENTO  1351744 non-null  object
 1   NRO COMPARENDO  1445649 non-null  object
 2   DOCUMENTO       1484484 non-null  object
 3   NOMBRE          1197544 non-null  object
 4   TELEFONO        1484484 non-null  object
 5   SMS             1484484 non-null  object
 6   BASE            1484484 non-null  object
 7   FECHA           1484484 non-null  datetime64[ns]
 8   RESULTADO SMS   1460237 non-null  object
dtypes: datetime64[ns](1), object(8)
memory usage: 101.9+ MB

In [56]:
cuenta = df['TIPO DOCUMENTO'].value_counts()

cuenta

TIPO DOCUMENTO
CÉDULA CIUDADANÍA              900107
CEDULA CIUDADANIA              151106
CÉDULA CIUDADANÍA              127355
CÉDULA DE CIUDADANÍA           100468
CC                              34719
NIT                              8983
PASAPORTE                        6380
CEDULA DE CIUDADANIA             6348
TARJETA IDENTIDAD                3255
CÉDULA EXTRANJERIA               3141
PERMISO PROTECCIÓN TEMP.         2300
PASAPORTE                        1345
CÉDULA VENEZOLANA                1072
CÉDULA VENEZOLANA                1006
PERMISO PROTECCIÓN TEMP.          820
PERMISO PROTECCION TEMPORAL       730
PPT                               460
CÉDULA EXTRANJERIA                458
PAS                               438
CÉDULA EXTRANJERÍA                246
TARJETA IDENTIDAD                 240
CV                                206
CE                                172
TI                                136
PASAP                              73
REGISTRO CIVIL                     67
NIT                                29
CEDULA EXTRANJERIA                 22
CEDULA VENEZOLANA                  18
REGISTRO CIVIL                     13
CARNÉT DIPLOMÁTICO                 11
CEDULA ECUADOR                      6
CARNÉT DIPLOMÁTICO                  3
CARNET DIPLOMÁTICO                  3
CEDULA ECUADOR                      2
NN                                  2
C-ECUA                              2
CÉDULA ECUATORIANA                  1
SIN DOCUMENTO                       1
Name: count, dtype: int64

In [57]:
columnas = df.columns

for i in columnas:
    cuenta = df[i].astype(str).map(len).max()
    print(f'la columna: {i} tiene un londitud maxima de : {cuenta}')

la columna: TIPO DOCUMENTO tiene un londitud maxima de : 27
la columna: NRO COMPARENDO tiene un londitud maxima de : 45
la columna: DOCUMENTO tiene un londitud maxima de : 20
la columna: NOMBRE tiene un londitud maxima de : 300
la columna: TELEFONO tiene un londitud maxima de : 15
la columna: SMS  tiene un londitud maxima de : 218
la columna: BASE tiene un londitud maxima de : 206
la columna: FECHA  tiene un londitud maxima de : 10
la columna: RESULTADO SMS tiene un londitud maxima de : 22

In [6]:
import chardet

ruta_archivo = r"C:\Users\1513873\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\2025\ENERO\02_01_2025 - copia"
def detectar_encoding(ruta_archivo):
    with open(ruta_archivo, 'rb') as f:
        rawdata = f.read()
    return chardet.detect(rawdata)['encoding']

datos = []
for archivo in archivos:
    try:
        ruta_completa = os.path.join(carpeta, archivo)
        encoding = detectar_encoding(ruta_completa)
        with open(ruta_completa, 'r', encoding=encoding) as f:
            contenido = f.read()
            datos.append({
                'nombre_archivo': archivo,
                'contenido': contenido,
                'encoding': encoding  # Opcional: ver qué codificación detectó
            })
    except Exception as e:
        print(f"Error leyendo {archivo}: {str(e)}")

df = pd.DataFrame(datos)
df

,nombre_archivo,contenido,encoding
0,Ap pagados 31_12 al 01_01.TXT,nro_acuerdo\tfecha_ap\tid_usuario\tnombres\tap...,ISO-8859-1
1,Comparendos pagados 31_12 al 01_01.TXT,nro_comparendo\tnro_recibo\tfecha_liquida_cont...,ISO-8859-1

In [21]:
# 1. Especificar la carpeta y listar archivos
carpeta = r"C:\Users\1513873\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\2025\ENERO\02_01_2025 - copia"
archivos = [f for f in os.listdir(carpeta) if f.lower().endswith('.txt')]

# 2. Diccionario para almacenar los DataFrames
dfs = {}

# 3. Leer cada archivo y crear un DataFrame
for archivo in archivos:
    try:
        ruta_completa = os.path.join(carpeta, archivo)
        df = pd.read_csv(
            ruta_completa,
            sep='\t',                # Separador de tabulador
            encoding='ISO-8859-1',    # Codificación detectada
            header=0                  # Usar primera fila como encabezado
        )
        dfs[archivo] = df  # Guardar en el diccionario
        print(f"DataFrame creado para: {archivo} (Filas: {df.shape[0]}, Columnas: {df.shape[1]})")
    except Exception as e:
        print(f"Error procesando {archivo}: {str(e)}")

DataFrame creado para: Ap pagados 31_12 al 01_01.TXT (Filas: 172, Columnas: 14)
DataFrame creado para: Comparendos pagados 31_12 al 01_01.TXT (Filas: 62, Columnas: 10)

In [22]:
# Ejemplo: Obtener el DataFrame del primer archivo
nombre_primer_archivo = list(dfs.keys())[0]
df_1 = dfs[nombre_primer_archivo]

# Ver las primeras filas
df_1.head()

,nro_acuerdo,fecha_ap,id_usuario,nombres,apellidos,total_ap,consecutivo_ap,saldo_ap,valor,fecha_pago_cuota,consecutivo_cuota,cuotas_pendientes,total_cuotas,fecha_liquida
0,436981,31/10/2023 00:00:00,1128407838,YURANI ANDREA,GOMEZ LONDOÑO,6186902,406403,1062302,177050,31/10/2024 00:00:00,13,6,19,01/01/2025 13:04:01
1,436896,30/10/2023 11:56:37,1037237877,MATEO,ZAPATA ANGARITA,2427737,406293,647402,107899,31/10/2024 11:56:37,13,6,19,01/01/2025 12:05:42
2,414248,02/05/2022 00:00:00,71192551,JULIAN,FLOREZ HERNANDEZ,6533468,379162,588938,98151,04/11/2024 00:00:00,31,6,37,01/01/2025 21:16:01
3,430584,06/07/2023 12:36:52,76350862,LEONARDO,VALENCIA OTERO,1996016,398480,177437,88711,07/11/2024 12:36:51,17,2,19,01/01/2025 20:56:01
4,449229,07/06/2024 10:50:18,42050631,MARIBEL DE LOS DOLORES,CORREA,1605132,418756,642056,128410,08/11/2024 10:50:18,6,5,11,01/01/2025 13:40:01

In [23]:
# Ejemplo: Obtener el DataFrame del primer archivo
nombre_primer_archivo = list(dfs.keys())[1]
df_2 = dfs[nombre_primer_archivo]

# Ver las primeras filas
df_2.head()

,nro_comparendo,nro_recibo,fecha_liquida_contrav,compute_0004,id_usuario,nombres,apellidos,nro_resolucion,cobro_coactivo,intereses
0,D05001000000044749921,9001979448,01/01/2025 01:46:10,214735,43522070,GLORIA PATRICIA,AUBAD MARIN,NaN,NaN,0
1,D05001000000044416504,9001979451,01/01/2025 01:52:57,572628,1152206334,JULIAN,MEJIA ROYO,677590.0,NaN,4282
2,D05001000000044478798,9001979452,01/01/2025 02:25:04,429348,1007243289,JOHN JAIRO,BUILES HIDALGO,NaN,NaN,0
3,D05001000000044507424,9001979452,01/01/2025 02:25:05,429348,1007243289,JOHN JAIRO,BUILES HIDALGO,NaN,NaN,0
4,D05001000000044540205,9001979460,01/01/2025 08:15:03,214735,1037647429,DANIELA,LOPEZ RIOS,NaN,NaN,0

In [1]:
import os
import pandas as pd

# 1. Especificar la carpeta y listar archivos
carpeta = r"C:\Users\1513873\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\2025\ENERO\02_01_2025 - copia"
archivos = [f for f in os.listdir(carpeta) if f.lower().endswith('.txt')]

# 2. Lista para almacenar DataFrames temporales
lista_dfs = []

# 3. Leer cada archivo controlando los tipos de datos
for archivo in archivos:
    try:
        ruta_completa = os.path.join(carpeta, archivo)
        
        # Leer el archivo forzando columnas numéricas como cadenas
        df_temp = pd.read_csv(
            ruta_completa,
            sep='\t',
            encoding='ISO-8859-1',
            header=0,
            dtype=str  # Leer todo como texto inicialmente
        )
        
        # Convertir columnas numéricas a enteros (si no hay decimales)
        # Ejemplo para columnas como "nro_acuerdo" o "id_usuario"
        columnas_numericas = ['nro_acuerdo', 'id_usuario']  # <-- Ajusta con tus columnas
        for col in columnas_numericas:
            if col in df_temp.columns:
                df_temp[col] = pd.to_numeric(df_temp[col], errors='coerce').astype('Int64')
        
        df_temp['Fuente_Archivo'] = archivo
        lista_dfs.append(df_temp)
        print(f"Archivo {archivo} procesado. Filas: {len(df_temp)}")
        
    except Exception as e:
        print(f"Error en {archivo}: {str(e)}")

# 4. Concatenar y formatear salida
if lista_dfs:
    df_concatenado = pd.concat(lista_dfs, ignore_index=True)
    
    # Configurar pandas para evitar notación científica
    pd.options.display.float_format = '{:.0f}'.format  # Enteros sin decimales
    
    print("\nDataFrame concatenado:")
    display(df_concatenado.tail())
else:
    print("No hay datos para concatenar")

Archivo Ap pagados 31_12 al 01_01.TXT procesado. Filas: 172
Archivo Comparendos pagados 31_12 al 01_01.TXT procesado. Filas: 62

DataFrame concatenado:

,nro_acuerdo,fecha_ap,id_usuario,nombres,apellidos,total_ap,consecutivo_ap,saldo_ap,valor,fecha_pago_cuota,...,total_cuotas,fecha_liquida,Fuente_Archivo,nro_comparendo,nro_recibo,fecha_liquida_contrav,compute_0004,nro_resolucion,cobro_coactivo,intereses
229,<NA>,NaN,42886875,GLORIA MARIA,ZULUAGA ARBELAEZ,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,D05001000000044556785,9001979692,01/01/2025 20:45:22,214735,NaN,NaN,0
230,<NA>,NaN,42886875,GLORIA MARIA,ZULUAGA ARBELAEZ,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,D05001000000044604604,9001979692,01/01/2025 20:45:22,214735,NaN,NaN,0
231,<NA>,NaN,1001618141,SEBASTIAN,AYALA ARROYAVE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,2ACCC1856555,9001979698,01/01/2025 20:46:02,572628,202450017311,NaN,2851
232,<NA>,NaN,1038803778,JUAN FERNANDO,SANCHEZ SEPULVEDA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,05001000000044705111,9001979715,01/01/2025 21:53:38,214735,NaN,NaN,0
233,<NA>,NaN,1000756224,CRISTIAN,GONZALEZ MONTERO,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,D05001000000044501797,9001979720,01/01/2025 22:07:39,572628,NaN,NaN,0

In [5]:
df_concatenado[173:180]

,nro_acuerdo,fecha_ap,id_usuario,nombres,apellidos,total_ap,consecutivo_ap,saldo_ap,valor,fecha_pago_cuota,...,total_cuotas,fecha_liquida,Fuente_Archivo,nro_comparendo,nro_recibo,fecha_liquida_contrav,compute_0004,nro_resolucion,cobro_coactivo,intereses
173,<NA>,NaN,1152206334,JULIAN,MEJIA ROYO,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,D05001000000044416504,9001979451,01/01/2025 01:52:57,572628,0000677590,NaN,4282
174,<NA>,NaN,1007243289,JOHN JAIRO,BUILES HIDALGO,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,D05001000000044478798,9001979452,01/01/2025 02:25:04,429348,NaN,NaN,0
175,<NA>,NaN,1007243289,JOHN JAIRO,BUILES HIDALGO,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,D05001000000044507424,9001979452,01/01/2025 02:25:05,429348,NaN,NaN,0
176,<NA>,NaN,1037647429,DANIELA,LOPEZ RIOS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,D05001000000044540205,9001979460,01/01/2025 08:15:03,214735,NaN,NaN,0
177,<NA>,NaN,1037647429,DANIELA,LOPEZ RIOS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,D05001000000044494900,9001979460,01/01/2025 08:15:04,214735,NaN,NaN,0
178,<NA>,NaN,1037647429,DANIELA,LOPEZ RIOS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,D05001000000044520674,9001979460,01/01/2025 08:15:04,214735,NaN,NaN,0
179,<NA>,NaN,1234990930,GABRIEL ALEXANDER,HENAO GARCIA,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Comparendos pagados 31_12 al 01_01.TXT,05001000000032455466,9001979466,01/01/2025 08:34:02,468589,0021216884,S,120891

In [2]:
import os
import pandas as pd
import numpy as np

pd.options.display.float_format = '{:.0f}'.format
carpeta = r"C:\Users\1513873\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\2025\ENERO\02_01_2025 - copia"
archivos = [f for f in os.listdir(carpeta) if f.lower().endswith('.txt')]

def procesar_archivo(ruta: str, archivo: str) -> pd.DataFrame:
    # Leer archivo manteniendo todo como texto
    df = pd.read_csv(ruta, sep='\t', encoding='ISO-8859-1', header=0, dtype=str)
    
    if archivo.startswith('Ap pagados'):
        # =============================================
        # Transformaciones para archivo AP PAGADOS
        # =============================================
        columnas_requeridas = [
            'nro_acuerdo', 'id_usuario', 'nombres', 
            'apellidos', 'valor', 'fecha_liquida', 'consecutivo_cuota'
        ]
        
        # Verificar columnas existentes
        columnas_disponibles = [col for col in columnas_requeridas if col in df.columns]
        df = df[columnas_disponibles]
        
        # Renombrar columna
        df = df.rename(columns={'fecha_liquida': 'fecha_pago'})
        
        # Crear nombre_usuario
        df['nombre_usuario'] = df['nombres'].str.cat(df['apellidos'], sep=' ', na_rep='').str.strip()
        
        # Eliminar columnas originales
        df = df.drop(columns=['nombres', 'apellidos'])
        
        # Forzar tipo texto para valores numéricos grandes
        df['nro_acuerdo'] = df['nro_acuerdo'].astype(str)
        df['id_usuario'] = df['id_usuario'].astype(str)
        
    elif archivo.startswith('Comparendos pagados'):
        # =============================================
        # Transformaciones para archivo COMPARENDOS
        # =============================================
        columnas_requeridas = [
            'nro_comparendo', 'nro_recibo', 'fecha_liquida_contrav',
            'compute_0004', 'id_usuario', 'nombres', 'apellidos',
            'nro_resolucion', 'intereses'
        ]
        
        # Verificar columnas existentes
        columnas_disponibles = [col for col in columnas_requeridas if col in df.columns]
        df = df[columnas_disponibles]
        
        # Renombrar columna
        df = df.rename(columns={'fecha_liquida_contrav': 'fecha_pago'})
        
        # Llenar nro_comparendo con nro_resolucion si está vacío
        df['nro_comparendo'] = np.where(
            df['nro_comparendo'].isnull() | (df['nro_comparendo'] == ''),
            df['nro_resolucion'],
            df['nro_comparendo']
        )
        
        # Crear nombre_usuario
        df['nombre_usuario'] = df['nombres'].str.cat(df['apellidos'], sep=' ', na_rep='').str.strip()
        
        # Eliminar columnas originales
        df = df.drop(columns=['nombres', 'apellidos'])
        
        # Crear columna valor (compute_0004 + intereses)
        try:
            # Convertir a numérico
            df['compute_0004'] = pd.to_numeric(df['compute_0004'], errors='coerce')
            df['intereses'] = pd.to_numeric(df['intereses'], errors='coerce')
            
            # Calcular suma
            df['valor'] = (df['compute_0004'] + df['intereses']).astype(str)
            
            # Mantener como texto sin notación científica
            df['valor'] = df['valor'].apply(lambda x: x.split('.')[0] if '.' in x else x)
            
        except Exception as e:
            print(f"Error en cálculos: {str(e)}")
            df['valor'] = ''
        
        # Forzar tipo texto para valores numéricos grandes
        cols_numericas = ['nro_comparendo', 'nro_recibo', 'nro_resolucion']
        for col in cols_numericas:
            df[col] = df[col].astype(str)
    
    # Columnas comunes para todos los archivos
    df['archivo_origen'] = archivo
    
    return df

# Procesamiento
dataframes = []
for archivo in archivos:
    try:
        ruta_completa = os.path.join(carpeta, archivo)
        df_procesado = procesar_archivo(ruta_completa, archivo)
        dataframes.append(df_procesado)
        print(f"✅ {archivo}: Procesado correctamente ({len(df_procesado)} registros)")
    except Exception as e:
        print(f"❌ Error procesando {archivo}: {str(e)}")

# Concatenación final
if dataframes:
    df_final = pd.concat(dataframes, ignore_index=True)
    
    # Reordenar columnas
    column_order = [
        'nro_acuerdo', 'nro_comparendo', 'id_usuario', 'nombre_usuario',
        'valor', 'fecha_pago', 'archivo_origen'
    ]
    
    # Seleccionar solo las columnas existentes
    final_cols = [col for col in column_order if col in df_final.columns]
    df_final = df_final[final_cols]
    
    print("\n═ DATA FINAL ═══════════════════════════════════════")
    print(f"Total de registros: {len(df_final):,}")
    print(f"Columnas: {', '.join(df_final.columns)}")
    print("\nMuestra de datos:")
    display(df_final.head())
else:
    print("No se encontraron archivos válidos para procesar")

✅ Ap pagados 31_12 al 01_01.TXT: Procesado correctamente (172 registros)
✅ Comparendos pagados 31_12 al 01_01.TXT: Procesado correctamente (62 registros)

═ DATA FINAL ═══════════════════════════════════════
Total de registros: 234
Columnas: nro_acuerdo, nro_comparendo, id_usuario, nombre_usuario, valor, fecha_pago, archivo_origen

Muestra de datos:

,nro_acuerdo,nro_comparendo,id_usuario,nombre_usuario,valor,fecha_pago,archivo_origen
0,436981,NaN,1128407838,YURANI ANDREA GOMEZ LONDOÑO,177050,01/01/2025 13:04:01,Ap pagados 31_12 al 01_01.TXT
1,436896,NaN,1037237877,MATEO ZAPATA ANGARITA,107899,01/01/2025 12:05:42,Ap pagados 31_12 al 01_01.TXT
2,414248,NaN,71192551,JULIAN FLOREZ HERNANDEZ,98151,01/01/2025 21:16:01,Ap pagados 31_12 al 01_01.TXT
3,430584,NaN,76350862,LEONARDO VALENCIA OTERO,88711,01/01/2025 20:56:01,Ap pagados 31_12 al 01_01.TXT
4,449229,NaN,42050631,MARIBEL DE LOS DOLORES CORREA,128410,01/01/2025 13:40:01,Ap pagados 31_12 al 01_01.TXT

In [3]:
import os
import pandas as pd
import numpy as np
from pathlib import Path

# Configuración global
pd.options.display.float_format = '{:.0f}'.format
carpeta_base = r"C:\Users\1513873\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\2025\ENERO"

# Función para procesar cada archivo según su tipo
def procesar_archivo(ruta: str, archivo_nombre: str) -> pd.DataFrame:
    try:
        # Leer archivo manteniendo todo como texto
        df = pd.read_csv(ruta, sep='\t', encoding='ISO-8859-1', header=0, dtype=str)
        
        if archivo_nombre.startswith('Ap pagados'):
            # ========== Transformaciones para "Ap pagados" ==========
            columnas_requeridas = [
                'nro_acuerdo', 'id_usuario', 'nombres', 'apellidos', 
                'valor', 'fecha_liquida', 'consecutivo_cuota'
            ]
            df = df[[col for col in columnas_requeridas if col in df.columns]]
            
            # Renombrar y limpiar datos
            df = df.rename(columns={'fecha_liquida': 'fecha_pago'})
            df['nombre_usuario'] = df['nombres'].str.cat(df['apellidos'], sep=' ', na_rep='').str.strip()
            df = df.drop(columns=['nombres', 'apellidos'])
            
            # Forzar tipos (evitar notación científica)
            df['nro_acuerdo'] = df['nro_acuerdo'].astype(str)
            df['id_usuario'] = df['id_usuario'].astype(str)
            
        elif archivo_nombre.startswith('Comparendos pagados'):
            # ========== Transformaciones para "Comparendos pagados" ==========
            columnas_requeridas = [
                'nro_comparendo', 'nro_recibo', 'fecha_liquida_contrav', 
                'compute_0004', 'id_usuario', 'nombres', 'apellidos',
                'nro_resolucion', 'intereses'
            ]
            df = df[[col for col in columnas_requeridas if col in df.columns]]
            
            # Renombrar y limpiar datos
            df = df.rename(columns={'fecha_liquida_contrav': 'fecha_pago'})
            df['nro_comparendo'] = np.where(
                df['nro_comparendo'].isnull() | (df['nro_comparendo'] == ''),
                df['nro_resolucion'],
                df['nro_comparendo']
            )
            df['nombre_usuario'] = df['nombres'].str.cat(df['apellidos'], sep=' ', na_rep='').str.strip()
            df = df.drop(columns=['nombres', 'apellidos'])
            
            # Calcular valor total (compute_0004 + intereses)
            df['compute_0004'] = pd.to_numeric(df['compute_0004'], errors='coerce')
            df['intereses'] = pd.to_numeric(df['intereses'], errors='coerce')
            df['valor'] = (df['compute_0004'] + df['intereses']).astype(str)
            df['valor'] = df['valor'].apply(lambda x: x.split('.')[0] if '.' in x else x)
            
            # Forzar tipos para evitar notación científica
            for col in ['nro_comparendo', 'nro_recibo', 'nro_resolucion']:
                if col in df.columns:
                    df[col] = df[col].astype(str)
        
        # Columna común con ruta relativa del archivo
        df['archivo_origen'] = os.path.relpath(ruta, carpeta_base)
        return df
        
    except Exception as e:
        print(f"❌ Error crítico en {archivo_nombre}: {type(e).__name__} - {str(e)}")
        return pd.DataFrame()  # Retorna DataFrame vacío para evitar interrupción

# Procesamiento recursivo
dataframes = []
for root, _, files in os.walk(carpeta_base):
    for archivo in files:
        if archivo.lower().endswith('.txt'):
            ruta_completa = os.path.join(root, archivo)
            df_procesado = procesar_archivo(ruta_completa, archivo)
            if not df_procesado.empty:
                dataframes.append(df_procesado)
                print(f"✅ {archivo}: Procesado ({len(df_procesado)} registros)")

# Consolidación final
if dataframes:
    df_final = pd.concat(dataframes, ignore_index=True)
    
    # Reordenar columnas (solo las existentes)
    columnas_orden = [
        'nro_acuerdo', 'nro_comparendo', 'id_usuario', 'nombre_usuario',
        'valor', 'fecha_pago', 'archivo_origen'
    ]
    df_final = df_final[[col for col in columnas_orden if col in df_final.columns]]
    
    # Resultados
    print("\n═ RESULTADO FINAL ═══════════════════════════════")
    print(f"Total archivos procesados: {len(dataframes)}")
    print(f"Total registros: {len(df_final):,}")
    print("\nMuestra de datos:")
    display(df_final.head())
else:
    print("⚠️ No se encontraron archivos .txt válidos.")

✅ Ap pagados 01_01 al 26_01.TXT: Procesado (11830 registros)
✅ Ap pagados 23_01.TXT: Procesado (480 registros)
✅ Ap pagados 24_01 al 26_01.TXT: Procesado (662 registros)
✅ Ap pagados 27_01.TXT: Procesado (716 registros)
✅ Ap pagados 28_01.TXT: Procesado (428 registros)
✅ Ap pagados 29_01.TXT: Procesado (475 registros)
✅ Ap pagados 30_01.TXT: Procesado (671 registros)
✅ Comparendo pagados 30_01.TXT: Procesado (1679 registros)
✅ Comparendos pagados 01_01 al 26_01.TXT: Procesado (26299 registros)
✅ Comparendos pagados 23_01.TXT: Procesado (1492 registros)
✅ Comparendos pagados 24_01 al 26_01.TXT: Procesado (2068 registros)
✅ Comparendos pagados 27_01.TXT: Procesado (1664 registros)
✅ Comparendos pagados 28_01.TXT: Procesado (1156 registros)
✅ Comparendos pagados 28_01_V2.TXT: Procesado (1156 registros)
✅ Comparendos pagados 29_01.TXT: Procesado (1993 registros)
✅ Ap pagados 01_12 al 31_12.TXT: Procesado (11471 registros)
✅ Ap pagados 31_12 al 01_01.TXT: Procesado (172 registros)
✅ Comparendos pagados 01_12 al 31_12.TXT: Procesado (29256 registros)
✅ Comparendos pagados 31_12 al 01_01.TXT: Procesado (62 registros)
✅ Ap pagados 31_12 al 01_01.TXT: Procesado (172 registros)
✅ Comparendos pagados 31_12 al 01_01.TXT: Procesado (62 registros)
✅ Ap pagados 02_01.TXT: Procesado (1117 registros)
✅ Comparendos pagados 02_01.TXT: Procesado (2157 registros)
✅ Ap pagados 03_01.TXT: Procesado (658 registros)
✅ Comparendos pagados 03_01.TXT: Procesado (930 registros)
✅ Ap pagados 04_01 al 06_01.TXT: Procesado (551 registros)
✅ Comparendos pagados 04_01 al 06_01.TXT: Procesado (548 registros)
✅ Ap pagados 07_01.TXT: Procesado (1015 registros)
✅ Comparendos pagados 07_01.TXT: Procesado (1321 registros)
✅ Ap pagados 08_01.TXT: Procesado (660 registros)
✅ Comparendos pagados 08_01.TXT: Procesado (1254 registros)
✅ Ap pagados 09_01.TXT: Procesado (685 registros)
✅ Comparendos pagados 09_01.TXT: Procesado (1265 registros)
✅ Ap pagados 10_ al 12_01.TXT: Procesado (865 registros)
✅ Comparendos pagados 10_ al 12_01.TXT: Procesado (1760 registros)
✅ Ap pagados 13_01.TXT: Procesado (732 registros)
✅ Comparendos pagados 13_01.TXT: Procesado (1498 registros)
✅ Ap pagados 14_01.TXT: Procesado (641 registros)
✅ Comparendos pagados 14_01.TXT: Procesado (1557 registros)
✅ Ap pagados 15_01.TXT: Procesado (710 registros)
✅ Comparendos pagados 15_01.TXT: Procesado (1562 registros)
✅ Ap pagados 16_01.TXT: Procesado (760 registros)
✅ Comparendos pagados 16_01.TXT: Procesado (1680 registros)
✅ Ap pagados 17_01.TXT: Procesado (595 registros)
✅ Comparendos pagados 17_01.TXT: Procesado (1978 registros)
✅ AP pagados 01_01  al 19_01.TXT: Procesado (8888 registros)
✅ Ap pagados 18_01 al 19_01.TXT: Procesado (229 registros)
✅ AP PAGADOS DEL 18_01 AL 19_01.TXT: Procesado (229 registros)
✅ Comparendos pagados 01_01 al 19_01.TXT: Procesado (18350 registros)
✅ Comparendos pagados 18_01 al 19_01.TXT: Procesado (779 registros)
✅ COMPARENDOS PAGADOS DEL 18_01 AL 19_01.TXT: Procesado (779 registros)
✅ AP PAGADOS 20_01.TXT: Procesado (784 registros)
✅ COMPARENDOS PAGADOS 20_01.TXT: Procesado (1622 registros)
✅ A p pagados 21_01.TXT: Procesado (527 registros)
✅ Comparendos pagados 21_01.TXT: Procesado (1335 registros)
✅ Ap pagados  22_01.TXT: Procesado (489 registros)
✅ Comparendos pagados  22_01.TXT: Procesado (1428 registros)
✅ Ap pagados 23_01.TXT: Procesado (480 registros)
✅ Comparendos pagados 23_01.TXT: Procesado (1492 registros)
✅ Ap pagados 01_01 al 26_01.TXT: Procesado (11830 registros)
✅ Ap pagados 24_01 al 26_01.TXT: Procesado (662 registros)
✅ Comparendos pagados 01_01 al 26_01.TXT: Procesado (26299 registros)
✅ Comparendos pagados 24_01 al 26_01.TXT: Procesado (2068 registros)
✅ Ap pagados 27_01.TXT: Procesado (716 registros)
✅ Comparendos pagados 27_01.TXT: Procesado (1664 registros)
✅ Ap pagados 28_01.TXT: Procesado (428 registros)
✅ Comparendos pagados 28_01.TXT: Procesado (1156 registros)
✅ Comparendos pagados 28_01_V2.TXT: Procesado (1156 registros)
✅ Ap pagados 29_01.TXT: Procesado (475 registros)
✅ Comparendos pagados 29_01.TXT: Procesado (1993 registros)
✅ Ap pagados 30_01.TXT: Procesado (671 registros)
✅ Comparendo pagados 30_01.TXT: Procesado (1679 registros)

═ RESULTADO FINAL ═══════════════════════════════
Total archivos procesados: 72
Total registros: 208,671

Muestra de datos:

,nro_acuerdo,nro_comparendo,id_usuario,nombre_usuario,valor,fecha_pago,archivo_origen
0,447672,NaN,1000532614,MAIRA ALEJANDRA SILVA BOTERO,94522,02/01/2025 14:06:02,Ap pagados 01_01 al 26_01.TXT
1,444545,NaN,1075020365,JOSE VOSNEY PALACIOS PALACIOS,50916,07/01/2025 07:30:00,Ap pagados 01_01 al 26_01.TXT
2,440319,NaN,98668484,CARLOS ANDRES CORREA ZAPATA,76774,04/01/2025 01:06:01,Ap pagados 01_01 al 26_01.TXT
3,449116,NaN,71384474,JUAN DAVID MENDIVELZO SALAZAR,122348,02/01/2025 17:37:47,Ap pagados 01_01 al 26_01.TXT
4,452151,NaN,42155929,LUZ ADRIANA HINCAPIE GARCIA,77164,02/01/2025 16:44:15,Ap pagados 01_01 al 26_01.TXT

In [28]:
import os
import pandas as pd
import numpy as np
import hashlib
from datetime import datetime
from typing import Tuple

# Configuración global
pd.options.display.float_format = '{:.0f}'.format

def parse_fecha(fecha_str):
    """Intenta parsear la fecha en múltiples formatos comunes."""
    if pd.isna(fecha_str) or fecha_str == '':
        return None
    
    formatos = [
        '%d/%m/%Y %H:%M:%S', '%Y-%m-%d %H:%M:%S', '%d/%m/%Y', 
        '%Y-%m-%d', '%m/%d/%Y', '%d-%m-%Y %H:%M:%S', '%Y/%m/%d %H:%M:%S'
    ]
    
    for fmt in formatos:
        try:
            return pd.to_datetime(fecha_str, format=fmt, errors='raise')
        except:
            continue
    
    return None

def procesar_archivo(ruta_completa: str, archivo: str, carpeta_base: str) -> Tuple[pd.DataFrame, pd.DataFrame, list]:
    """
    Procesa un archivo individual y devuelve DataFrames limpios y con errores.
    """
    try:
        # Leer archivo manteniendo todo como texto
        df = pd.read_csv(ruta_completa, sep='\t', encoding='ISO-8859-1', dtype=str)
        advertencias = []
        
        # ========== Transformaciones comunes para todos los archivos ==========
        
        # 1. Verificar y mapear columnas de nombres
        if all(col in df.columns for col in ['nombres', 'apellidos']):
            df['nombre_usuario'] = df['nombres'].str.cat(df['apellidos'], sep=' ', na_rep='').str.strip()
            df = df.drop(columns=['nombres', 'apellidos'], errors='ignore')
        else:
            df['nombre_usuario'] = ''
            advertencias.append("No se encontraron columnas de nombres/apellidos")
        
        # 2. Mapear id_usuario a documento
        if 'id_usuario' in df.columns:
            df['documento'] = df['id_usuario'].astype(str)
            df = df.drop(columns=['id_usuario'], errors='ignore')
        else:
            df['documento'] = ''
            advertencias.append("No se encontró columna id_usuario")
        
        # 3. Manejo de fechas (intenta con diferentes nombres de columna)
        col_fecha = None
        for posible_col in ['fecha_liquida', 'fecha_liquida_contrav', 'fecha_pago']:
            if posible_col in df.columns:
                col_fecha = posible_col
                break
                
        if col_fecha:
            df['fecha_pago'] = df[col_fecha].apply(parse_fecha)
            if df['fecha_pago'].isna().any():
                advertencias.append(f"Algunas fechas en '{col_fecha}' no pudieron ser parseadas")
            if col_fecha != 'fecha_pago':
                df = df.drop(columns=[col_fecha], errors='ignore')
        else:
            df['fecha_pago'] = None
            advertencias.append("No se encontró columna de fecha")
        
        # 4. Manejo de valor (intenta con diferentes nombres de columna)
        if 'valor' not in df.columns:
            if all(col in df.columns for col in ['compute_0004', 'intereses']):
                df['compute_0004'] = pd.to_numeric(df['compute_0004'], errors='coerce').fillna(0)
                df['intereses'] = pd.to_numeric(df['intereses'], errors='coerce').fillna(0)
                df['valor'] = (df['compute_0004'] + df['intereses'])
                df = df.drop(columns=['compute_0004', 'intereses'], errors='ignore')
            else:
                df['valor'] = 0
                advertencias.append("No se encontraron columnas para calcular valor")
        
        # 5. Campos adicionales con valores por defecto
        df['nro_acuerdo'] = df.get('nro_acuerdo', '')
        df['nro_comparendo'] = df.get('nro_comparendo', '')
        df['consecutivo_cuota'] = df.get('consecutivo_cuota', '')
        df['nro_recibo'] = df.get('nro_recibo', '')
        df['nro_resolucion'] = df.get('nro_resolucion', '')
        
        # Si hay nro_comparendo vacío pero existe nro_resolucion, usamos ese
        if 'nro_resolucion' in df.columns:
            df['nro_comparendo'] = np.where(
                (df['nro_comparendo'].isnull()) | (df['nro_comparendo'] == ''),
                df['nro_resolucion'],
                df['nro_comparendo']
            )
        
        # ========== Procesamiento común ==========
        # Generar ID único
        df['id_registro'] = df.apply(
            lambda x: hashlib.sha256((
                f"{x['nro_acuerdo']}_"
                f"{x['nro_comparendo']}_"
                f"{x['documento']}_"
                f"{x['nombre_usuario']}_"
                f"{x['valor']}_"
                f"{x['consecutivo_cuota']}_"
                f"{x['fecha_pago']}"
            ).encode()).hexdigest(),
            axis=1
        )
        
        # Agregar metadatos
        df['archivo_origen'] = os.path.relpath(ruta_completa, carpeta_base)
        df['fecha_carga'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        # Convertir tipos de datos
        df['valor'] = pd.to_numeric(df['valor'], errors='coerce')
        
        # ===== NUEVO: Identificar errores específicos por registro =====
        # Crear columnas para cada tipo de error
        df['error_documento'] = (df['documento'].isna() | (df['documento'] == ''))
        df['error_valor'] = (df['valor'].isna() | (df['valor'] <= 0))
        df['error_fecha'] = df['fecha_pago'].isna()
        
        # Generar mensaje de error detallado para cada registro
        def generar_mensaje_error(row):
            errores = []
            if row['error_documento']:
                errores.append(f"Documento vacío o inválido: '{row['documento']}'")
            if row['error_valor']:
                errores.append(f"Valor inválido: '{row['valor']}' (debe ser mayor que 0)")
            if row['error_fecha']:
                # Buscar la columna de fecha original para mostrar el valor problemático
                col_fecha_orig = None
                for posible_col in ['fecha_liquida', 'fecha_liquida_contrav', 'fecha_pago']:
                    if posible_col in df.columns and posible_col != 'fecha_pago':
                        col_fecha_orig = posible_col
                        break
                
                valor_fecha = row[col_fecha_orig] if col_fecha_orig and col_fecha_orig in row else "No disponible"
                errores.append(f"Fecha inválida o no reconocida: '{valor_fecha}'")
            
            if errores:
                return " | ".join(errores)
            return ""
        
        df['mensaje_error'] = df.apply(generar_mensaje_error, axis=1)
        
        # Validar registros con la misma lógica anterior
        mask_errores = (df['error_documento'] | df['error_valor'] | df['error_fecha'])
        
        df_errores = df[mask_errores].copy()
        df_limpio = df[~mask_errores].copy()
        
        # Eliminar columnas de diagnóstico en el dataframe limpio
        df_limpio = df_limpio.drop(columns=['error_documento', 'error_valor', 'error_fecha'], errors='ignore')
        
        return df_limpio, df_errores, advertencias
    
    except Exception as e:
        # Crear un dataframe de error con información sobre la excepción
        df_error = pd.DataFrame({
            'archivo_origen': [os.path.relpath(ruta_completa, carpeta_base)],
            'mensaje_error': [f"Error de procesamiento: {str(e)}"]
        })
        return pd.DataFrame(), df_error, [f"Error procesando {archivo}: {str(e)}"]

def limpiar_datos_recursivo(carpeta_base: str) -> Tuple[pd.DataFrame, pd.DataFrame, list]:
    """
    Procesa todos los archivos TXT en la carpeta y subcarpetas.
    """
    resultados = []
    errores_totales = []
    advertencias_totales = []
    archivos_procesados = 0
    
    for root, _, files in os.walk(carpeta_base):
        for archivo in files:
            if archivo.lower().endswith('.txt'):
                ruta_completa = os.path.join(root, archivo)
                
                try:
                    # Procesar el archivo
                    df_limpio, df_errores, advertencias = procesar_archivo(ruta_completa, archivo, carpeta_base)
                    
                    if not df_limpio.empty:
                        resultados.append(df_limpio)
                    if not df_errores.empty:
                        errores_totales.append(df_errores)
                    if advertencias:
                        advertencias_totales.extend(advertencias)
                    
                    archivos_procesados += 1
                    print(f"Procesado: {archivo} - Válidos: {len(df_limpio)}, Errores: {len(df_errores)}")
                    
                    # Mostrar muestra de errores si existen
                    if not df_errores.empty and len(df_errores) <= 5:
                        print("  Detalle de errores encontrados:")
                        for _, fila in df_errores.iterrows():
                            print(f"  - Error: {fila['mensaje_error']}")
                
                except Exception as e:
                    advertencias_totales.append(f"Error procesando {archivo}: {str(e)}")
    
    # Consolidar resultados
    df_final = pd.concat(resultados, ignore_index=True) if resultados else pd.DataFrame()
    df_errores_final = pd.concat(errores_totales, ignore_index=True) if errores_totales else pd.DataFrame()
    
    print(f"\nProcesamiento completado. Archivos: {archivos_procesados}")
    print(f"Registros válidos: {len(df_final):,}")
    print(f"Registros con errores: {len(df_errores_final):,}")
    
    return df_final, df_errores_final, advertencias_totales

# Función auxiliar para analizar errores más frecuentes
def analizar_errores(df_errores):
    """
    Analiza los tipos de errores más frecuentes en el DataFrame de errores
    """
    if df_errores.empty:
        return print("No hay errores para analizar")
    
    # Contar tipos de errores (puede haber múltiples errores por registro)
    total_errores = len(df_errores)
    
    # Verificar si tenemos las columnas de diagnóstico
    if 'error_documento' in df_errores.columns:
        errores_documento = df_errores['error_documento'].sum()
        errores_valor = df_errores['error_valor'].sum()
        errores_fecha = df_errores['error_fecha'].sum()
        
        print(f"\nAnálisis de {total_errores} registros con errores:")
        print(f"- Problemas con documento: {errores_documento} ({errores_documento/total_errores*100:.1f}%)")
        print(f"- Problemas con valor: {errores_valor} ({errores_valor/total_errores*100:.1f}%)")
        print(f"- Problemas con fecha: {errores_fecha} ({errores_fecha/total_errores*100:.1f}%)")
    
    # Análisis por archivo
    print("\nDistribución de errores por archivo:")
    errores_por_archivo = df_errores['archivo_origen'].value_counts()
    for archivo, conteo in errores_por_archivo.items():
        print(f"- {archivo}: {conteo} errores")
    
    # Mostrar una muestra de errores concretos
    print("\nEjemplos de errores encontrados:")
    muestra = min(5, len(df_errores))
    for i, (_, fila) in enumerate(df_errores.sample(muestra).iterrows(), 1):
        print(f"{i}. Archivo: {fila['archivo_origen']}")
        if 'documento' in fila:
            print(f"   Documento: '{fila['documento']}'")
        if 'nombre_usuario' in fila:
            print(f"   Usuario: '{fila['nombre_usuario']}'")
        if 'valor' in fila:
            print(f"   Valor: '{fila['valor']}'")
        if 'fecha_pago' in fila:
            print(f"   Fecha (procesada): '{fila['fecha_pago']}'")
        print(f"   Error: {fila['mensaje_error']}")
        print()

# Ejemplo de uso
if __name__ == "__main__":
    carpeta_base = r"C:\Users\1513873\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\2025\ENERO"
    
    df_limpio, df_errores, warnings = limpiar_datos_recursivo(carpeta_base)
    
    # Mostrar resultados
    if not df_limpio.empty:
        print("\nMuestra de datos válidos:")
        display(df_limpio.head())
    
    if not df_errores.empty:
        print("\nMuestra de datos con errores:")
        # Mostrar columnas relevantes incluyendo valores problemáticos
        cols_mostrar = ['archivo_origen', 'documento', 'nombre_usuario', 'valor', 'fecha_pago', 'mensaje_error']
        # Asegúrate de que todas las columnas existan
        cols_existentes = [col for col in cols_mostrar if col in df_errores.columns]
        display(df_errores[cols_existentes].head())
        
        # Análisis detallado de errores
        analizar_errores(df_errores)
    
    if warnings:
        print("\nAdvertencias/Errores encontrados:")
        for warning in warnings:
            print(f"- {warning}")
            
    # Opcional: Guardar los errores en un archivo para revisión detallada
    if not df_errores.empty:
        ruta_errores = os.path.join(os.path.dirname(carpeta_base), "errores_procesamiento.csv")
        df_errores.to_csv(ruta_errores, index=False, encoding='utf-8-sig')
        print(f"\nSe ha guardado el detalle de errores en: {ruta_errores}")

Procesado: Ap pagados 01_01 al 26_01.TXT - Válidos: 11830, Errores: 0
Procesado: Ap pagados 23_01.TXT - Válidos: 480, Errores: 0
Procesado: Ap pagados 24_01 al 26_01.TXT - Válidos: 662, Errores: 0
Procesado: Ap pagados 27_01.TXT - Válidos: 716, Errores: 0
Procesado: Ap pagados 28_01.TXT - Válidos: 428, Errores: 0
Procesado: Ap pagados 29_01.TXT - Válidos: 475, Errores: 0
Procesado: Ap pagados 30_01.TXT - Válidos: 671, Errores: 0
Procesado: Comparendo pagados 30_01.TXT - Válidos: 1678, Errores: 1
  Detalle de errores encontrados:
  - Error: Valor inválido: '0' (debe ser mayor que 0)
Procesado: Comparendos pagados 01_01 al 26_01.TXT - Válidos: 26299, Errores: 0
Procesado: Comparendos pagados 23_01.TXT - Válidos: 1492, Errores: 0
Procesado: Comparendos pagados 24_01 al 26_01.TXT - Válidos: 2068, Errores: 0
Procesado: Comparendos pagados 27_01.TXT - Válidos: 1664, Errores: 0
Procesado: Comparendos pagados 28_01.TXT - Válidos: 1156, Errores: 0
Procesado: Comparendos pagados 28_01_V2.TXT - Válidos: 1156, Errores: 0
Procesado: Comparendos pagados 29_01.TXT - Válidos: 1993, Errores: 0
Procesado: Ap pagados 01_12 al 31_12.TXT - Válidos: 11471, Errores: 0
Procesado: Ap pagados 31_12 al 01_01.TXT - Válidos: 172, Errores: 0
Procesado: Comparendos pagados 01_12 al 31_12.TXT - Válidos: 29256, Errores: 0
Procesado: Comparendos pagados 31_12 al 01_01.TXT - Válidos: 62, Errores: 0
Procesado: Ap pagados 31_12 al 01_01.TXT - Válidos: 172, Errores: 0
Procesado: Comparendos pagados 31_12 al 01_01.TXT - Válidos: 62, Errores: 0
Procesado: Ap pagados 02_01.TXT - Válidos: 1117, Errores: 0
Procesado: Comparendos pagados 02_01.TXT - Válidos: 2157, Errores: 0
Procesado: Ap pagados 03_01.TXT - Válidos: 658, Errores: 0
Procesado: Comparendos pagados 03_01.TXT - Válidos: 930, Errores: 0
Procesado: Ap pagados 04_01 al 06_01.TXT - Válidos: 551, Errores: 0
Procesado: Comparendos pagados 04_01 al 06_01.TXT - Válidos: 548, Errores: 0
Procesado: Ap pagados 07_01.TXT - Válidos: 1015, Errores: 0
Procesado: Comparendos pagados 07_01.TXT - Válidos: 1321, Errores: 0
Procesado: Ap pagados 08_01.TXT - Válidos: 660, Errores: 0
Procesado: Comparendos pagados 08_01.TXT - Válidos: 1254, Errores: 0
Procesado: Ap pagados 09_01.TXT - Válidos: 685, Errores: 0
Procesado: Comparendos pagados 09_01.TXT - Válidos: 1265, Errores: 0
Procesado: Ap pagados 10_ al 12_01.TXT - Válidos: 865, Errores: 0
Procesado: Comparendos pagados 10_ al 12_01.TXT - Válidos: 1760, Errores: 0
Procesado: Ap pagados 13_01.TXT - Válidos: 732, Errores: 0
Procesado: Comparendos pagados 13_01.TXT - Válidos: 1498, Errores: 0
Procesado: Ap pagados 14_01.TXT - Válidos: 641, Errores: 0
Procesado: Comparendos pagados 14_01.TXT - Válidos: 1557, Errores: 0
Procesado: Ap pagados 15_01.TXT - Válidos: 710, Errores: 0
Procesado: Comparendos pagados 15_01.TXT - Válidos: 1562, Errores: 0
Procesado: Ap pagados 16_01.TXT - Válidos: 760, Errores: 0
Procesado: Comparendos pagados 16_01.TXT - Válidos: 1680, Errores: 0
Procesado: Ap pagados 17_01.TXT - Válidos: 595, Errores: 0
Procesado: Comparendos pagados 17_01.TXT - Válidos: 1978, Errores: 0
Procesado: AP pagados 01_01  al 19_01.TXT - Válidos: 8888, Errores: 0
Procesado: Ap pagados 18_01 al 19_01.TXT - Válidos: 229, Errores: 0
Procesado: AP PAGADOS DEL 18_01 AL 19_01.TXT - Válidos: 229, Errores: 0
Procesado: Comparendos pagados 01_01 al 19_01.TXT - Válidos: 18350, Errores: 0
Procesado: Comparendos pagados 18_01 al 19_01.TXT - Válidos: 779, Errores: 0
Procesado: COMPARENDOS PAGADOS DEL 18_01 AL 19_01.TXT - Válidos: 779, Errores: 0
Procesado: AP PAGADOS 20_01.TXT - Válidos: 784, Errores: 0
Procesado: COMPARENDOS PAGADOS 20_01.TXT - Válidos: 1622, Errores: 0
Procesado: A p pagados 21_01.TXT - Válidos: 527, Errores: 0
Procesado: Comparendos pagados 21_01.TXT - Válidos: 1335, Errores: 0
Procesado: Ap pagados  22_01.TXT - Válidos: 489, Errores: 0
Procesado: Comparendos pagados  22_01.TXT - Válidos: 1428, Errores: 0
Procesado: Ap pagados 23_01.TXT - Válidos: 480, Errores: 0
Procesado: Comparendos pagados 23_01.TXT - Válidos: 1492, Errores: 0
Procesado: Ap pagados 01_01 al 26_01.TXT - Válidos: 11830, Errores: 0
Procesado: Ap pagados 24_01 al 26_01.TXT - Válidos: 662, Errores: 0
Procesado: Comparendos pagados 01_01 al 26_01.TXT - Válidos: 26299, Errores: 0
Procesado: Comparendos pagados 24_01 al 26_01.TXT - Válidos: 2068, Errores: 0
Procesado: Ap pagados 27_01.TXT - Válidos: 716, Errores: 0
Procesado: Comparendos pagados 27_01.TXT - Válidos: 1664, Errores: 0
Procesado: Ap pagados 28_01.TXT - Válidos: 428, Errores: 0
Procesado: Comparendos pagados 28_01.TXT - Válidos: 1156, Errores: 0
Procesado: Comparendos pagados 28_01_V2.TXT - Válidos: 1156, Errores: 0
Procesado: Ap pagados 29_01.TXT - Válidos: 475, Errores: 0
Procesado: Comparendos pagados 29_01.TXT - Válidos: 1993, Errores: 0
Procesado: Ap pagados 30_01.TXT - Válidos: 671, Errores: 0
Procesado: Comparendo pagados 30_01.TXT - Válidos: 1678, Errores: 1
  Detalle de errores encontrados:
  - Error: Valor inválido: '0' (debe ser mayor que 0)

Procesamiento completado. Archivos: 72
Registros válidos: 208,669
Registros con errores: 2

Muestra de datos válidos:

,nro_acuerdo,fecha_ap,total_ap,consecutivo_ap,saldo_ap,valor,fecha_pago_cuota,consecutivo_cuota,cuotas_pendientes,total_cuotas,...,documento,fecha_pago,nro_comparendo,nro_recibo,nro_resolucion,id_registro,archivo_origen,fecha_carga,mensaje_error,cobro_coactivo
0,447672,02/05/2024 11:44:24,2126765,417199,945236,94522,03/10/2024 11:44:24,6,10,19,...,1000532614,2025-01-02 14:06:02,,,,3c9ffb5db6e5cb5eeaa18619eaad57ab9eb009c8468965...,Ap pagados 01_01 al 26_01.TXT,2025-05-13 23:59:13,,NaN
1,444545,06/03/2024 11:47:13,572806,414137,0,50916,07/10/2024 11:47:13,8,0,10,...,1075020365,2025-01-07 07:30:00,,,,939986046b31a6fa8efd631b5c028bb82512492625a637...,Ap pagados 01_01 al 26_01.TXT,2025-05-13 23:59:13,,NaN
2,440319,05/01/2024 12:01:58,1055654,409946,0,76774,07/10/2024 12:01:58,10,0,12,...,98668484,2025-01-04 01:06:01,,,,56ea7c4c56689cd96fc29bd4806f82f297106a54884627...,Ap pagados 01_01 al 26_01.TXT,2025-05-13 23:59:13,,NaN
3,449116,05/06/2024 12:24:05,1070552,418643,122354,122348,07/10/2024 12:24:05,5,1,8,...,71384474,2025-01-02 17:37:47,,,,7ae346a494d6508f60ca5f1dce218a81ef2c8cd78f19a7...,Ap pagados 01_01 al 26_01.TXT,2025-05-13 23:59:13,,NaN
4,452151,05/08/2024 14:10:19,1736204,421640,1157471,77164,07/10/2024 14:10:19,3,13,19,...,42155929,2025-01-02 16:44:15,,,,d71418e0f33aa7ac87533a99fffc3592cd4449b75094d3...,Ap pagados 01_01 al 26_01.TXT,2025-05-13 23:59:13,,NaN

Muestra de datos con errores:

,archivo_origen,documento,nombre_usuario,valor,fecha_pago,mensaje_error
0,Comparendo pagados 30_01.TXT,1017230454,DEISY JULIETH SALAZAR PIEDRAHITA,0,2025-01-30 17:40:12,Valor inválido: '0' (debe ser mayor que 0)
1,31_01_2025\Comparendo pagados 30_01.TXT,1017230454,DEISY JULIETH SALAZAR PIEDRAHITA,0,2025-01-30 17:40:12,Valor inválido: '0' (debe ser mayor que 0)

Análisis de 2 registros con errores:
- Problemas con documento: 0 (0.0%)
- Problemas con valor: 2 (100.0%)
- Problemas con fecha: 0 (0.0%)

Distribución de errores por archivo:
- Comparendo pagados 30_01.TXT: 1 errores
- 31_01_2025\Comparendo pagados 30_01.TXT: 1 errores

Ejemplos de errores encontrados:
1. Archivo: 31_01_2025\Comparendo pagados 30_01.TXT
   Documento: '1017230454'
   Usuario: 'DEISY JULIETH SALAZAR PIEDRAHITA'
   Valor: '0'
   Fecha (procesada): '2025-01-30 17:40:12'
   Error: Valor inválido: '0' (debe ser mayor que 0)

2. Archivo: Comparendo pagados 30_01.TXT
   Documento: '1017230454'
   Usuario: 'DEISY JULIETH SALAZAR PIEDRAHITA'
   Valor: '0'
   Fecha (procesada): '2025-01-30 17:40:12'
   Error: Valor inválido: '0' (debe ser mayor que 0)


Se ha guardado el detalle de errores en: C:\Users\1513873\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\2025\errores_procesamiento.csv

In [4]:
import os
import shutil
from collections import defaultdict

# Ruta de la carpeta principal
carpeta_principal = r'C:\Users\1513873\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos'

# Ruta de destino (puede ser la misma carpeta principal)
destino = r'C:\Users\1513873\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025'

# Diccionario para llevar registro de cuántas veces hemos visto cada nombre
contador_archivos = defaultdict(int)

# Crear carpeta de destino si no existe
os.makedirs(destino, exist_ok=True)

# Recorrer todas las subcarpetas
for root, dirs, files in os.walk(carpeta_principal):
    for file in files:
        # Obtener nombre base y extensión
        nombre_base, extension = os.path.splitext(file)
        ruta_original = os.path.join(root, file)
        
        # Determinar el nuevo nombre
        contador_archivos[file] += 1
        contador = contador_archivos[file]
        
        if contador == 1:
            # Primer archivo con este nombre - mantener nombre original
            nuevo_nombre = file
        else:
            # Archivo duplicado - añadir sufijo
            nuevo_nombre = f"{nombre_base}_{contador}{extension}"
        
        ruta_destino = os.path.join(destino, nuevo_nombre)
        
        # Mover el archivo
        shutil.move(ruta_original, ruta_destino)
        print(f"Movido: {file} -> {nuevo_nombre}")

Movido: Ap pagados 01_03 al 31_03.TXT -> Ap pagados 01_03 al 31_03.TXT
Movido: Ap pagados 01_04.TXT -> Ap pagados 01_04.TXT
Movido: Ap pagados 02_03.TXT -> Ap pagados 02_03.TXT
Movido: Ap pagados 03_04.TXT -> Ap pagados 03_04.TXT
Movido: Ap pagados 31_03.TXT -> Ap pagados 31_03.TXT
Movido: Comparendos pagados 01_03 al 31_03.TXT -> Comparendos pagados 01_03 al 31_03.TXT
Movido: Comparendos pagados 01_04.TXT -> Comparendos pagados 01_04.TXT
Movido: Comparendos pagados 02_03.TXT -> Comparendos pagados 02_03.TXT
Movido: Comparendos pagados 31_03.TXT -> Comparendos pagados 31_03.TXT
Movido: Comparendos pagados 01_03 al 31_03.TXT -> Comparendos pagados 01_03 al 31_03_2.TXT
Movido: Comparendos pagados 03_04.TXT -> Comparendos pagados 03_04.TXT
Movido: Ap pagados 04_04.TXT -> Ap pagados 04_04.TXT
Movido: BASE IMPOSICION DIARIA 05_04_2025.xlsx -> BASE IMPOSICION DIARIA 05_04_2025.xlsx
Movido: Comparendos pagados 04_04.TXT -> Comparendos pagados 04_04.TXT
Movido: Ap pagados 05_04 al 06_04.TXT -> Ap pagados 05_04 al 06_04.TXT
Movido: Comparendos pagados 05_04 al 06_04.TXT -> Comparendos pagados 05_04 al 06_04.TXT
Movido: Ap pagados 07_04.TXT -> Ap pagados 07_04.TXT
Movido: Comparendos pagados 07_04.TXT -> Comparendos pagados 07_04.TXT
Movido: Ap pagados 08_04.TXT -> Ap pagados 08_04.TXT
Movido: Comparendos pagados 08_04.TXT -> Comparendos pagados 08_04.TXT
Movido: Ap pagados 09_04.TXT -> Ap pagados 09_04.TXT
Movido: Comparendos pagados 09_04.TXT -> Comparendos pagados 09_04.TXT
Movido: Ap pagados 10_04.TXT -> Ap pagados 10_04.TXT
Movido: BASE IMPOSICION DIARIA 11_04_2025.xlsx -> BASE IMPOSICION DIARIA 11_04_2025.xlsx
Movido: Comparendos pagados 10_04.TXT -> Comparendos pagados 10_04.TXT
Movido: Ap pagados 11_04.TXT -> Ap pagados 11_04.TXT
Movido: Comparendos pagados 11_04.TXT -> Comparendos pagados 11_04.TXT
Movido: Ap pagados 01_04 al 13_04.TXT -> Ap pagados 01_04 al 13_04.TXT
Movido: Ap pagados 12_04 al 13_04.TXT -> Ap pagados 12_04 al 13_04.TXT
Movido: Comparendos pagados 01_04 al 13_04.TXT -> Comparendos pagados 01_04 al 13_04.TXT
Movido: Comparendos pagados 12_04 al 13_04.TXT -> Comparendos pagados 12_04 al 13_04.TXT
Movido: Ap pagados 14_04.TXT -> Ap pagados 14_04.TXT
Movido: Comparendos pagados 14_04.TXT -> Comparendos pagados 14_04.TXT
Movido: Ap pagados 15_04.TXT -> Ap pagados 15_04.TXT
Movido: BASE IMPOSICION DIARIA 16_04_2025.xlsx -> BASE IMPOSICION DIARIA 16_04_2025.xlsx
Movido: Comparendos pagados 15_04.TXT -> Comparendos pagados 15_04.TXT
Movido: BASE IMPOSICION DIARIA 17_04_2025.xlsx -> BASE IMPOSICION DIARIA 17_04_2025.xlsx
Movido: BASE IMPOSICION DIARIA 18_04_2025.xlsx -> BASE IMPOSICION DIARIA 18_04_2025.xlsx
Movido: BASE IMPOSICION DIARIA 19_04_2025.xlsx -> BASE IMPOSICION DIARIA 19_04_2025.xlsx
Movido: Ap pagados 01_04 al 20_04.TXT -> Ap pagados 01_04 al 20_04.TXT
Movido: Ap pagados 16_04 al 20_04.TXT -> Ap pagados 16_04 al 20_04.TXT
Movido: Comparendos pagados 01_04 al 20_04.TXT -> Comparendos pagados 01_04 al 20_04.TXT
Movido: Comparendos pagados 16_04 al 20_04.TXT -> Comparendos pagados 16_04 al 20_04.TXT
Movido: Ap pagados 21_04.TXT -> Ap pagados 21_04.TXT
Movido: Comparendos pagados 21_04.TXT -> Comparendos pagados 21_04.TXT
Movido: Ap pagados 22_04.TXT -> Ap pagados 22_04.TXT
Movido: Comparendos pagados 22_04.TXT -> Comparendos pagados 22_04.TXT
Movido: Ap pagados 23_04.TXT -> Ap pagados 23_04.TXT
Movido: Comparendos pagados 23_04.TXT -> Comparendos pagados 23_04.TXT
Movido: Ap pagados 01_04 al 24_04.TXT -> Ap pagados 01_04 al 24_04.TXT
Movido: Comparendos pagados 01_04 al 24_04.TXT -> Comparendos pagados 01_04 al 24_04.TXT
Movido: Ap pagados 25_04 al 27_04.TXT -> Ap pagados 25_04 al 27_04.TXT
Movido: Comparendos pagados 25_04 al 27_04.TXT -> Comparendos pagados 25_04 al 27_04.TXT
Movido: Ap pagados 28_04.TXT -> Ap pagados 28_04.TXT
Movido: Comparendos pagados 28_04.TXT -> Comparendos pagados 28_04.TXT
Movido: Ap pagados 29_04.TXT -> Ap pagados 29_04.TXT
Movido: Comparendos pagados 29_04.TXT -> Comparendos pagados 29_04.TXT
Movido: Ap pagados 01_12 al 31_12.TXT -> Ap pagados 01_12 al 31_12.TXT
Movido: Ap pagados 31_12 al 01_01.TXT -> Ap pagados 31_12 al 01_01.TXT
Movido: Comparendos pagados 01_12 al 31_12.TXT -> Comparendos pagados 01_12 al 31_12.TXT
Movido: Comparendos pagados 31_12 al 01_01.TXT -> Comparendos pagados 31_12 al 01_01.TXT
Movido: Ap pagados 02_01.TXT -> Ap pagados 02_01.TXT
Movido: Comparendos pagados 02_01.TXT -> Comparendos pagados 02_01.TXT
Movido: Ap pagados 03_01.TXT -> Ap pagados 03_01.TXT
Movido: BASE IMPOSICION DIARIA 04_01_2025.xlsx -> BASE IMPOSICION DIARIA 04_01_2025.xlsx
Movido: Comparendos pagados 03_01.TXT -> Comparendos pagados 03_01.TXT
Movido: Ap pagados 04_01 al 06_01.TXT -> Ap pagados 04_01 al 06_01.TXT
Movido: Comparendos pagados 04_01 al 06_01.TXT -> Comparendos pagados 04_01 al 06_01.TXT
Movido: Ap pagados 07_01.TXT -> Ap pagados 07_01.TXT
Movido: Comparendos pagados 07_01.TXT -> Comparendos pagados 07_01.TXT
Movido: Ap pagados 08_01.TXT -> Ap pagados 08_01.TXT
Movido: BASE IMPOSICION DIARIA 09_01_2025.xlsx -> BASE IMPOSICION DIARIA 09_01_2025.xlsx
Movido: Comparendos pagados 08_01.TXT -> Comparendos pagados 08_01.TXT
Movido: Ap pagados 09_01.TXT -> Ap pagados 09_01.TXT
Movido: Comparendos pagados 09_01.TXT -> Comparendos pagados 09_01.TXT
Movido: Ap pagados 10_ al 12_01.TXT -> Ap pagados 10_ al 12_01.TXT
Movido: Comparendos pagados 10_ al 12_01.TXT -> Comparendos pagados 10_ al 12_01.TXT
Movido: Ap pagados 13_01.TXT -> Ap pagados 13_01.TXT
Movido: Comparendos pagados 13_01.TXT -> Comparendos pagados 13_01.TXT
Movido: Ap pagados 14_01.TXT -> Ap pagados 14_01.TXT
Movido: Comparendos pagados 14_01.TXT -> Comparendos pagados 14_01.TXT
Movido: Ap pagados 15_01.TXT -> Ap pagados 15_01.TXT
Movido: Comparendos pagados 15_01.TXT -> Comparendos pagados 15_01.TXT
Movido: Ap pagados 16_01.TXT -> Ap pagados 16_01.TXT
Movido: Comparendos pagados 16_01.TXT -> Comparendos pagados 16_01.TXT
Movido: Ap pagados 17_01.TXT -> Ap pagados 17_01.TXT
Movido: Comparendos pagados 17_01.TXT -> Comparendos pagados 17_01.TXT
Movido: AP pagados 01_01  al 19_01.TXT -> AP pagados 01_01  al 19_01.TXT
Movido: Ap pagados 18_01 al 19_01.TXT -> Ap pagados 18_01 al 19_01.TXT
Movido: AP PAGADOS DEL 18_01 AL 19_01.TXT -> AP PAGADOS DEL 18_01 AL 19_01.TXT
Movido: Comparendos pagados 01_01 al 19_01.TXT -> Comparendos pagados 01_01 al 19_01.TXT
Movido: Comparendos pagados 18_01 al 19_01.TXT -> Comparendos pagados 18_01 al 19_01.TXT
Movido: COMPARENDOS PAGADOS DEL 18_01 AL 19_01.TXT -> COMPARENDOS PAGADOS DEL 18_01 AL 19_01.TXT
Movido: AP PAGADOS 20_01.TXT -> AP PAGADOS 20_01.TXT
Movido: COMPARENDOS PAGADOS 20_01.TXT -> COMPARENDOS PAGADOS 20_01.TXT
Movido: A p pagados 21_01.TXT -> A p pagados 21_01.TXT
Movido: Comparendos pagados 21_01.TXT -> Comparendos pagados 21_01.TXT
Movido: Ap pagados  22_01.TXT -> Ap pagados  22_01.TXT
Movido: Comparendos pagados  22_01.TXT -> Comparendos pagados  22_01.TXT
Movido: Ap pagados 23_01.TXT -> Ap pagados 23_01.TXT
Movido: Comparendos pagados 23_01.TXT -> Comparendos pagados 23_01.TXT
Movido: Ap pagados 01_01 al 26_01.TXT -> Ap pagados 01_01 al 26_01.TXT
Movido: Ap pagados 24_01 al 26_01.TXT -> Ap pagados 24_01 al 26_01.TXT
Movido: Comparendos pagados 01_01 al 26_01.TXT -> Comparendos pagados 01_01 al 26_01.TXT
Movido: Comparendos pagados 24_01 al 26_01.TXT -> Comparendos pagados 24_01 al 26_01.TXT
Movido: Ap pagados 27_01.TXT -> Ap pagados 27_01.TXT
Movido: Comparendos pagados 27_01.TXT -> Comparendos pagados 27_01.TXT
Movido: Ap pagados 28_01.TXT -> Ap pagados 28_01.TXT
Movido: Comparendos pagados 28_01.TXT -> Comparendos pagados 28_01.TXT
Movido: Comparendos pagados 28_01_V2.TXT -> Comparendos pagados 28_01_V2.TXT
Movido: Comparendos pagados.xlsx -> Comparendos pagados.xlsx
Movido: Ap pagados 29_01.TXT -> Ap pagados 29_01.TXT
Movido: Comparendos pagados 29_01.TXT -> Comparendos pagados 29_01.TXT
Movido: Ap pagados 30_01.TXT -> Ap pagados 30_01.TXT
Movido: Comparendo pagados 30_01.TXT -> Comparendo pagados 30_01.TXT
Movido: Ap pagados 31_01.TXT -> Ap pagados 31_01.TXT
Movido: Comparendos pagados 31_01.TXT -> Comparendos pagados 31_01.TXT
Movido: Comparendos pagados del 01_01 al 31_01.TXT -> Comparendos pagados del 01_01 al 31_01.TXT
Movido: Ap pagados 01_02 al 02_02.TXT -> Ap pagados 01_02 al 02_02.TXT
Movido: Comparendos pagados 01_02 al 02_02.TXT -> Comparendos pagados 01_02 al 02_02.TXT
Movido: Ap pagados 03_02.TXT -> Ap pagados 03_02.TXT
Movido: Comparendos pagados 03_02.TXT -> Comparendos pagados 03_02.TXT
Movido: Ap pagados 04_02.TXT -> Ap pagados 04_02.TXT
Movido: Comparendos pagados 04_02.TXT -> Comparendos pagados 04_02.TXT
Movido: Ap pagados 05_02.TXT -> Ap pagados 05_02.TXT
Movido: Comparendos pagados 05_02.TXT -> Comparendos pagados 05_02.TXT
Movido: Ap pagados 06_02.TXT -> Ap pagados 06_02.TXT
Movido: Comparendos pagados 06_02.TXT -> Comparendos pagados 06_02.TXT
Movido: Ap pagados 07_02 al 09_02.TXT -> Ap pagados 07_02 al 09_02.TXT
Movido: Comparendos pagados 07_02 al 09_02.TXT -> Comparendos pagados 07_02 al 09_02.TXT
Movido: Ap pagados 10_02.TXT -> Ap pagados 10_02.TXT
Movido: Comparendos pagados 10_02.TXT -> Comparendos pagados 10_02.TXT
Movido: Ap pagados 11_02.TXT -> Ap pagados 11_02.TXT
Movido: Comparedos pagados 11_02.TXT -> Comparedos pagados 11_02.TXT
Movido: Ap pagados 01_02 al 12_02.TXT -> Ap pagados 01_02 al 12_02.TXT
Movido: Ap pagados 12_02.TXT -> Ap pagados 12_02.TXT
Movido: Comparendos pagados 01_02 al 12_02.TXT -> Comparendos pagados 01_02 al 12_02.TXT
Movido: Comparendos pagados 12_02.TXT -> Comparendos pagados 12_02.TXT
Movido: Ap pagados 13_02.TXT -> Ap pagados 13_02.TXT
Movido: Comparendos pagados 13_02.TXT -> Comparendos pagados 13_02.TXT
Movido: Ap pagados 14_02.TXT -> Ap pagados 14_02.TXT
Movido: Comparendos pagados 14_02.TXT -> Comparendos pagados 14_02.TXT
Movido: Ap pagados 15_02 al 16_02.TXT -> Ap pagados 15_02 al 16_02.TXT
Movido: Comparendos pagados 15_02 al 16_02.TXT -> Comparendos pagados 15_02 al 16_02.TXT
Movido: Ap pagados 17_02.TXT -> Ap pagados 17_02.TXT
Movido: Comparendos pagados 17_02.TXT -> Comparendos pagados 17_02.TXT
Movido: Ap pagados 18_02.TXT -> Ap pagados 18_02.TXT
Movido: Comparendos pagados 18_02.TXT -> Comparendos pagados 18_02.TXT
Movido: Ap pagados 19_02.TXT -> Ap pagados 19_02.TXT
Movido: Comparendos pagados 19_02.TXT -> Comparendos pagados 19_02.TXT
Movido: Ap pagados 20_02.TXT -> Ap pagados 20_02.TXT
Movido: BASE IMPOSICION DIARIA 21_02_2025.xlsx -> BASE IMPOSICION DIARIA 21_02_2025.xlsx
Movido: Comparendos pagados 20_02.TXT -> Comparendos pagados 20_02.TXT
Movido: Ap pagados 20_02.TXT -> Ap pagados 20_02_2.TXT
Movido: BASE IMPOSICION DIARIA 22_02_2025.xlsx -> BASE IMPOSICION DIARIA 22_02_2025.xlsx
Movido: Comparendos pagados 20_02.TXT -> Comparendos pagados 20_02_2.TXT
Movido: Ap pagados 21_02 al 23_02.TXT -> Ap pagados 21_02 al 23_02.TXT
Movido: Comparendos pagados 21_02 al 23_02.TXT -> Comparendos pagados 21_02 al 23_02.TXT
Movido: Ap pagados 24_02.TXT -> Ap pagados 24_02.TXT
Movido: Comparendos pagados 24_02.TXT -> Comparendos pagados 24_02.TXT
Movido: Ap pagados 25_02.TXT -> Ap pagados 25_02.TXT
Movido: Comparendos pagados 25_02.TXT -> Comparendos pagados 25_02.TXT
Movido: Ap pagados 26_02.TXT -> Ap pagados 26_02.TXT
Movido: Comparendos pagados 26_02.TXT -> Comparendos pagados 26_02.TXT
Movido: Ap pagados 27_02.TXT -> Ap pagados 27_02.TXT
Movido: Comparendos pagados 27_02.TXT -> Comparendos pagados 27_02.TXT
Movido: Ap pagados 01_02 al 28_02.TXT -> Ap pagados 01_02 al 28_02.TXT
Movido: Ap pagados 28_02.TXT -> Ap pagados 28_02.TXT
Movido: Comparendos pagados 01_02 al 28_02.TXT -> Comparendos pagados 01_02 al 28_02.TXT
Movido: Comparendos pagados 28_02.TXT -> Comparendos pagados 28_02.TXT
Movido: Ap pagados 01_03 al 02_03.TXT -> Ap pagados 01_03 al 02_03.TXT
Movido: Comparendos pagados 01_03 al 02_03.TXT -> Comparendos pagados 01_03 al 02_03.TXT
Movido: Ap pagados 03_03.TXT -> Ap pagados 03_03.TXT
Movido: Comparendos pagados 03_03.TXT -> Comparendos pagados 03_03.TXT
Movido: Ap pagados 04_03.TXT -> Ap pagados 04_03.TXT
Movido: Comparendos pagados 04_03.TXT -> Comparendos pagados 04_03.TXT
Movido: Ap pagados 05_03.TXT -> Ap pagados 05_03.TXT
Movido: Comparendos pagados 05_03.TXT -> Comparendos pagados 05_03.TXT
Movido: AP pagados 06_03_2024.TXT -> AP pagados 06_03_2024.TXT
Movido: Comparendos pagados 06_03_2024.TXT -> Comparendos pagados 06_03_2024.TXT
Movido: Ap pagados 07_03.TXT -> Ap pagados 07_03.TXT
Movido: Comparendos pagados 07_03.TXT -> Comparendos pagados 07_03.TXT
Movido: Ap pagados 08_03 al 09_03.TXT -> Ap pagados 08_03 al 09_03.TXT
Movido: Comparendos pagados 08_03 al 09_03.TXT -> Comparendos pagados 08_03 al 09_03.TXT
Movido: Ap pagados 10_03.TXT -> Ap pagados 10_03.TXT
Movido: Comparendos pagados 10_03.TXT -> Comparendos pagados 10_03.TXT
Movido: Ap pagados 11_03.TXT -> Ap pagados 11_03.TXT
Movido: Comparendos pagados 11_03.TXT -> Comparendos pagados 11_03.TXT
Movido: Ap pagados 12_03.TXT -> Ap pagados 12_03.TXT
Movido: Comparendos pagados 12_03.TXT -> Comparendos pagados 12_03.TXT
Movido: Ap pagados 13_03.TXT -> Ap pagados 13_03.TXT
Movido: Comparendos pagados 13_03.TXT -> Comparendos pagados 13_03.TXT
Movido: BASE IMPOSICION DIARIA 15_03_2025.xlsx -> BASE IMPOSICION DIARIA 15_03_2025.xlsx
Movido: Ap pagados 01_03 al 16_03.TXT -> Ap pagados 01_03 al 16_03.TXT
Movido: Ap pagados 14_03 al 16_03.TXT -> Ap pagados 14_03 al 16_03.TXT
Movido: Comparendos pagados 01_03 al 16_03.TXT -> Comparendos pagados 01_03 al 16_03.TXT
Movido: Comparendos pagados 14_03 al 16_03.TXT -> Comparendos pagados 14_03 al 16_03.TXT
Movido: Ap pagados 17_03.TXT -> Ap pagados 17_03.TXT
Movido: Comparendos pagados 17_03.TXT -> Comparendos pagados 17_03.TXT
Movido: Ap pagados 01_03 al 18_03.TXT -> Ap pagados 01_03 al 18_03.TXT
Movido: Ap pagados 18_03.TXT -> Ap pagados 18_03.TXT
Movido: Comparendos pagados 01_03 al 18_03.TXT -> Comparendos pagados 01_03 al 18_03.TXT
Movido: Comparendos pagados 18_03.TXT -> Comparendos pagados 18_03.TXT
Movido: Ap pagados 19_03.TXT -> Ap pagados 19_03.TXT
Movido: Comparendos pagados 19_03.TXT -> Comparendos pagados 19_03.TXT
Movido: Ap pagados 20_03.TXT -> Ap pagados 20_03.TXT
Movido: Comparendos pagados 20_03.TXT -> Comparendos pagados 20_03.TXT
Movido: Ap pagados 21_03.TXT -> Ap pagados 21_03.TXT
Movido: Comparendos pagados 21_03.TXT -> Comparendos pagados 21_03.TXT
Movido: Ap pagados 22_03 al 24_03.TXT -> Ap pagados 22_03 al 24_03.TXT
Movido: Comparendos pagados 22_03 al 24_03.TXT -> Comparendos pagados 22_03 al 24_03.TXT
Movido: Ap pagados 25_03.TXT -> Ap pagados 25_03.TXT
Movido: Comparendos pagados 25_03.TXT -> Comparendos pagados 25_03.TXT
Movido: Ap pagados 26_03.TXT -> Ap pagados 26_03.TXT
Movido: Comparendos pagados 26_03.TXT -> Comparendos pagados 26_03.TXT
Movido: Ap pagados 27_03.TXT -> Ap pagados 27_03.TXT
Movido: Comparendos pagados 27_03.TXT -> Comparendos pagados 27_03.TXT
Movido: Ap pagados 27_03.TXT -> Ap pagados 27_03_2.TXT
Movido: BASE IMPOSICION DIARIA 29_03_2025.xlsx -> BASE IMPOSICION DIARIA 29_03_2025.xlsx
Movido: Comparendos pagados 27_03.TXT -> Comparendos pagados 27_03_2.TXT
Movido: Ap pagados 01_03 al 30_03.TXT -> Ap pagados 01_03 al 30_03.TXT
Movido: Ap pagados 28_03 al 30_03.TXT -> Ap pagados 28_03 al 30_03.TXT
Movido: Comparendos pagados 01_03 al 30_03.TXT -> Comparendos pagados 01_03 al 30_03.TXT
Movido: Comparendos pagados 28_03 al 30_03.TXT -> Comparendos pagados 28_03 al 30_03.TXT
Movido: Ap pagados 01_04 al 30_04.TXT -> Ap pagados 01_04 al 30_04.TXT
Movido: Comparendos pagados 01_04 al 30_04.TXT -> Comparendos pagados 01_04 al 30_04.TXT
Movido: Ap pagados 01_05 al 02_05.TXT -> Ap pagados 01_05 al 02_05.TXT
Movido: BASE IMPOSICION DIARIA 03_05_2025.xlsx -> BASE IMPOSICION DIARIA 03_05_2025.xlsx
Movido: Comparendos pagados 01_05 al 02_05.TXT -> Comparendos pagados 01_05 al 02_05.TXT
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_15_57.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_15_57.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_47_58.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_47_58.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_50_2.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_50_2.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_52_3.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_52_3.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_54_4.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_54_4.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_56_5.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_56_5.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_58_7.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_10_58_7.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_0_8.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_0_8.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_10_13.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_10_13.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_12_14.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_12_14.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_14_15.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_14_15.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_16_19.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_16_19.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_18_22.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_18_22.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_20_26.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_20_26.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_22_29.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_22_29.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_24_33.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_24_33.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_26_34.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_26_34.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_28_37.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_28_37.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_2_9.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_2_9.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_30_38.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_30_38.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_32_40.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_32_40.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_34_41.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_34_41.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_36_42.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_36_42.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_38_43.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_38_43.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_40_44.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_40_44.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_42_45.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_42_45.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_44_46.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_44_46.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_4_10.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_4_10.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_6_11.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_6_11.dmp
Movido: _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_8_12.dmp -> _minidump_default_pid_7808_tid_x4A0C_2025_5_3_11_8_12.dmp
Movido: Ap pagados 03_05 al 04_05.TXT -> Ap pagados 03_05 al 04_05.TXT
Movido: Comparendos pagados 03_05 al 04_05.TXT -> Comparendos pagados 03_05 al 04_05.TXT
Movido: Ap pagados 05_05.TXT -> Ap pagados 05_05.TXT
Movido: Comparendos pagados 05_05.TXT -> Comparendos pagados 05_05.TXT

In [10]:
import pandas as pd

In [13]:
df= pd.read_excel(r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Bases\2025\1- ENERO.xlsx", sheet_name='REGISTROS')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156451 entries, 0 to 156450
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   BASE                  156451 non-null  object
 1   FECHA DE ENTREGA      156451 non-null  datetime64[ns]
 2   TIPO DE DCTO          109419 non-null  object
 3   IDENTIFICACIÓN        156451 non-null  object
 4   NOMBRE                105658 non-null  object
 5   NRO. COMPARENDO       156451 non-null  object
 6   FECHA DE COMPARENDO   154833 non-null  object
 7   CODIGO DE INFRACCIÓN  151156 non-null  object
 8   PLACA                 138369 non-null  object
 9   VALOR INFRACCIÓN      155851 non-null  float64
 10  CEL1                  120620 non-null  object
 11  CEL2                  0 non-null       float64
 12  CEL3                  0 non-null       float64
 13  CEL4                  0 non-null       float64
 14  CEL5                  0 non-null       float64
 15  RESULTADOS            151795 non-null  object
dtypes: datetime64[ns](1), float64(5), object(10)
memory usage: 19.1+ MB

In [7]:
fecha_max = max(df['FECHA DE ENTREGA'])
fecha_max

Timestamp('2025-05-29 00:00:00')

In [9]:
df['FECHA DE ENTREGA'].value_counts()

FECHA DE ENTREGA
2025-05-05    130815
2025-05-02     31168
2025-05-13     21741
2025-05-23     10102
2025-05-20      7347
2025-05-12      5558
2025-05-27      4717
2025-05-29      3201
2025-05-19      2878
2025-05-07      2659
2025-05-28      2595
2025-05-14      2063
2025-05-15      2047
2025-05-09      1761
2025-05-22      1632
2025-05-16      1599
2025-05-06      1387
2025-05-03      1091
2025-05-26      1079
2025-05-21      1013
2025-05-08       852
2025-05-17       823
2025-05-24       730
2025-05-10       532
Name: count, dtype: int64

In [8]:
import pandas as pd
import sqlalchemy
from sqlalchemy import text

engine = sqlalchemy.create_engine('postgresql://postgres:admin@localhost:5432/SIMM')

query = """WITH telefonos_limpios AS (
    SELECT 
        id_registro,
        telefono AS original,
        REGEXP_REPLACE(telefono, '^\+57|[^0-9]', '', 'g') AS telefono_limpio
    FROM bases
    ),

    telefonos_validados AS (
    SELECT 
        id_registro,
        original,
        telefono_limpio,
        CASE
        -- 1. Teléfonos ausentes
        WHEN original IS NULL THEN 'AUSENTE: Valor NULL'
        WHEN TRIM(original) = '' THEN 'AUSENTE: Cadena vacía'

        -- 2. Teléfonos con solo ceros
        WHEN telefono_limpio ~ '^0+$' THEN 
            CASE 
                WHEN LENGTH(telefono_limpio) = 1 THEN 'ERRADO: Un solo cero'
                ELSE 'ERRADO: ' || LENGTH(telefono_limpio) || ' ceros consecutivos'
            END

        -- 3. Longitudes inválidas (7 o 10 dígitos esperados después de limpieza)
        WHEN LENGTH(telefono_limpio) NOT IN (7, 10) THEN 'ERRADO: Longitud incorrecta (' || LENGTH(telefono_limpio) || ' dígitos)'

        -- 4. Secuencias numéricas obvias
        WHEN telefono_limpio ~ '^(1234567|7654321|9876543|3210987|0123456|5432109|1234567890|9876543210|0123456789)' THEN 'ERRADO: Secuencia numérica obvia'

        -- 5. Repeticiones o patrones simples
        WHEN telefono_limpio ~ '^(\d)\1+$' THEN 'ERRADO: Todos los dígitos iguales'
        WHEN telefono_limpio ~ '(\d)\1{4}' THEN 'ERRADO: Demasiadas repeticiones (4+ dígitos iguales)'
        WHEN telefono_limpio ~ '^(\d\d)\1+' THEN 'ERRADO: Patrón repetitivo'
        WHEN LENGTH(telefono_limpio) = 7 AND telefono_limpio ~ '^(0{5,}|1{5,}|2{5,}|9{5,})$' THEN 'ERRADO: Fijo con patrón inválido (repetitivo)'
        WHEN LENGTH(telefono_limpio) = 7 THEN 'VALIDO: Fijo regional'


        -- 6. Validación móvil: 10 dígitos y empieza por 3
        -- 6.1. Móviles con patrones artificiales (ej. 3000000000, 3001111111, etc.)
        WHEN telefono_limpio ~ '^3\d{2}(0{5,}|1{5,}|2{5,}|6{5,}|9{5,})$' THEN 'ERRADO: Móvil con patrón inválido (repetitivo)'


        -- 6.2. Validación móvil: 10 dígitos y empieza por 3
        WHEN LENGTH(telefono_limpio) = 10 AND telefono_limpio ~ '^3\d{9}$' THEN 'VALIDO: Móvil'

        -- 7. Teléfono fijo nacional (con indicativo)
        WHEN LENGTH(telefono_limpio) = 10 AND LEFT(telefono_limpio, 3) IN ('601','604','605','607','608') THEN
            'VALIDO: Teléfono fijo largo (' || LEFT(telefono_limpio, 3) || ')'

        -- 8. Teléfono fijo regional (7 dígitos, empieza entre 2 y 9)
        WHEN LENGTH(telefono_limpio) = 7 AND LEFT(telefono_limpio, 1) BETWEEN '2' AND '9' THEN 'VALIDO: Fijo regional'

        -- 9. Internacional válido (código país +57)
        WHEN original ~ '^\+57' AND telefono_limpio ~ '^3\d{9}$' THEN 'VALIDO: Móvil con código país'

        -- 10. Demasiados ceros (>50% ceros)
        WHEN (LENGTH(telefono_limpio) - LENGTH(REGEXP_REPLACE(telefono_limpio, '0', '', 'g'))) > (LENGTH(telefono_limpio)/2) THEN 'ERRADO: Demasiados ceros'

        -- 11. Por defecto: inválido si no cumplió ningún criterio
        ELSE 'ERRADO: No cumple ningún patrón válido'
    END AS estado

    FROM telefonos_limpios
    )

    -- Resultado final
    SELECT 
    id_registro,
    original AS telefono_original,
    telefono_limpio,
    estado,
    CASE
        WHEN estado LIKE 'AUSENTE%' THEN 'AUSENTE'
        WHEN estado LIKE 'ERRADO%' THEN 'ERRADO'
        WHEN estado LIKE 'VALIDO%' THEN 'VALIDO'
        ELSE 'REVISAR'
    END AS categoria,
    LENGTH(telefono_limpio) AS longitud
    FROM telefonos_validados
    ORDER BY
    CASE
        WHEN estado LIKE 'AUSENTE%' THEN 1
        WHEN estado LIKE 'ERRADO%' THEN 2
        ELSE 3
    END,
    estado,
    original;"""

with engine.connect() as conn:
    df = pd.read_sql(text(query), conn)

df.to_csv('telefonos.csv', index=False)

<>:11: SyntaxWarning: invalid escape sequence '\+'
<>:11: SyntaxWarning: invalid escape sequence '\+'
C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_936\1830371728.py:11: SyntaxWarning: invalid escape sequence '\+'
  REGEXP_REPLACE(telefono, '^\+57|[^0-9]', '', 'g') AS telefono_limpio

In [1]:
import pandas as pd
import glob
import os


# Ruta a la carpeta donde están los archivos Excel
carpeta = r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Gestiones\2025\ABRIL" 

# Buscar todos los archivos .xlsx
archivos_excel = glob.glob(os.path.join(carpeta, "*.xlsx"))

# Verificar archivos encontrados
print(f"Archivos encontrados: {len(archivos_excel)}")

# Leer y concatenar todos los Excel
df_concatenado = pd.concat([
    pd.read_excel(archivo).assign(archivo=os.path.basename(archivo))
    for archivo in archivos_excel
], ignore_index=True)

# Mostrar los primeros registros
df_concatenado.head()

Archivos encontrados: 24

,ID_GESTION_CAMPANNA,NOMBRE_DOCUMENTO,NUMERO_DOCUMENTO,CONTACTO,FECHA_REGISTRO,TIPOLLAMADA,ID_REGISTRO_GESTION,NOMBRE_RESULTADO,TIPO_CHAT,FECHA_COMPROMISO_PAGO,FUNCIONARIO,NOMBRE_CAMPANNA,TELEFONO,NUMERO_OBLIGACION,VALOR_OBLIGACION,MIGRADO,NRO_COMPARENDO,archivo,Unnamed: 17
0,23118801.0,Cédula de Ciudadanía,1090990033,YARLEY SILVA,2025-04-01 07:01:14,Saliente,17435088690335307098,Mensaje,No aplica,NaN,Vanesa Henao,SIN CAMPA¿A,3146879574,D05001000000044522076,572628.0,NaN,D05001000000044522076,01-04-2025.xlsx,NaN
1,23118802.0,Cédula de Ciudadanía,1090497203,LUIS MIGUEL SOLANO ARGUELLO,2025-04-01 07:01:39,Saliente,17435088292325307097,Mensaje,No aplica,NaN,LAURA VILLADA,SIN CAMPA¿A,3105839261,D05001000000044538698,572628.0,NaN,D05001000000044538698,01-04-2025.xlsx,NaN
2,23118802.0,Cédula de Ciudadanía,1090497203,LUIS MIGUEL SOLANO ARGUELLO,2025-04-01 07:01:39,Saliente,17435088292325307097,Mensaje,No aplica,NaN,LAURA VILLADA,SIN CAMPA¿A,3105839261,D05001000000044583399,572628.0,NaN,D05001000000044583399,01-04-2025.xlsx,NaN
3,23118803.0,Cédula de Ciudadanía,1017155618,JENNIFFER RESTREPO,2025-04-01 07:02:05,Saliente,17435088609205307095,Mensaje,No aplica,NaN,MARTA GAVIRIA,SIN CAMPA¿A,3135541853,0002215135,572628.0,NaN,D05001000000042053248,01-04-2025.xlsx,NaN
4,23118804.0,Cédula de Ciudadanía,98695900,VICTOR JOSE ACEVEDO SERNA,2025-04-01 07:02:18,Saliente,17435089485695307103,Mensaje,No aplica,NaN,YURANY RAMIREZ,SIN CAMPA¿A,3128377970,D05001000000048061853,604054.0,NaN,D05001000000048061853,01-04-2025.xlsx,NaN

In [2]:
df_concatenado['FECHA_REGISTRO'] = pd.to_datetime(df_concatenado['FECHA_REGISTRO'], errors='coerce')

In [8]:
df_concatenado['FECHA_REGISTRO'] = pd.to_datetime(
    df_concatenado['FECHA_REGISTRO'],
    format='%d/%m/%Y %H:%M:%S',
    errors='coerce'
)

In [10]:
fechas_invalidas = df_concatenado['FECHA_REGISTRO'].isna().sum()
print(f'Fechas no válidas: {fechas_invalidas}')

Fechas no válidas: 0

In [3]:
import math
import pandas as pd
from pandas import ExcelWriter

# Tamaño máximo por hoja (Excel permite hasta 1,048,576 filas)
MAX_FILAS = 1048576

# Cantidad de partes que necesitás
num_partes = math.ceil(len(df_concatenado) / MAX_FILAS)

with pd.ExcelWriter("concatenado_dividido_ABRIL.xlsx", engine='xlsxwriter') as writer:
    for i in range(num_partes):
        inicio = i * MAX_FILAS
        fin = (i + 1) * MAX_FILAS
        df_concatenado.iloc[inicio:fin].to_excel(writer, sheet_name=f"Parte_{i+1}", index=False)

In [2]:
import os
import pandas as pd
from datetime import datetime
from pathlib import Path

def explorar_archivos_pagos(ruta_base):
    """
    Explora la estructura de carpetas y archivos de pagos
    
    Args:
        ruta_base (str): Ruta principal donde están las carpetas de meses
    
    Returns:
        DataFrame con información detallada de todos los archivos encontrados
    """
    
    archivos_encontrados = []
    
    # Verificar que la ruta existe
    if not os.path.exists(ruta_base):
        print(f"❌ La ruta {ruta_base} no existe")
        return pd.DataFrame()
    
    print(f"🔍 Explorando: {ruta_base}")
    print("=" * 50)
    
    # Recorrer la estructura de directorios
    for root, dirs, files in os.walk(ruta_base):
        # Calcular nivel de profundidad
        nivel = root.replace(ruta_base, '').count(os.sep)
        
        # Información del directorio actual
        carpeta_actual = os.path.basename(root)
        ruta_relativa = os.path.relpath(root, ruta_base)
        
        if nivel == 0:
            print(f"\n📁 Directorio base: {carpeta_actual}")
        else:
            print(f"{'  ' * nivel}📂 {carpeta_actual}")
        
        # Procesar archivos en el directorio actual
        archivos_txt = [f for f in files if f.lower().endswith('.txt')]
        
        if archivos_txt:
            print(f"{'  ' * (nivel + 1)}📄 Archivos encontrados: {len(archivos_txt)}")
            
            for archivo in archivos_txt:
                ruta_completa = os.path.join(root, archivo)
                
                # Obtener información del archivo
                try:
                    stat_info = os.stat(ruta_completa)
                    tamaño_kb = round(stat_info.st_size / 1024, 2)
                    fecha_modificacion = datetime.fromtimestamp(stat_info.st_mtime)
                    
                    # Extraer información del nombre del archivo
                    tipo_archivo = "Desconocido"
                    if "ap pagados" in archivo.lower():
                        tipo_archivo = "AP Pagados"
                    elif "comparendos pagados" in archivo.lower():
                        tipo_archivo = "Comparendos Pagados"
                    
                    # Intentar extraer rango de fechas del nombre
                    rango_fechas = extraer_rango_fechas(archivo)
                    
                    archivo_info = {
                        'ruta_completa': ruta_completa,
                        'ruta_relativa': ruta_relativa,
                        'carpeta_mes': carpeta_actual if nivel == 1 else 'Base',
                        'nombre_archivo': archivo,
                        'tipo_archivo': tipo_archivo,
                        'rango_fechas': rango_fechas,
                        'tamaño_kb': tamaño_kb,
                        'fecha_modificacion': fecha_modificacion,
                        'nivel_directorio': nivel
                    }
                    
                    archivos_encontrados.append(archivo_info)
                    
                    print(f"{'  ' * (nivel + 2)}• {archivo} ({tamaño_kb} KB) - {tipo_archivo}")
                    if rango_fechas:
                        print(f"{'  ' * (nivel + 3)}📅 Rango: {rango_fechas}")
                
                except Exception as e:
                    print(f"{'  ' * (nivel + 2)}❌ Error procesando {archivo}: {e}")
        
        elif nivel > 0:  # Solo mostrar para subcarpetas, no para la base
            print(f"{'  ' * (nivel + 1)}📭 Sin archivos .txt")
    
    # Crear DataFrame con los resultados
    df_archivos = pd.DataFrame(archivos_encontrados)
    
    if not df_archivos.empty:
        print(f"\n📊 RESUMEN:")
        print(f"Total de archivos encontrados: {len(df_archivos)}")
        print(f"Tipos de archivo encontrados:")
        print(df_archivos['tipo_archivo'].value_counts().to_string())
        print(f"\nCarpetas de mes encontradas:")
        carpetas_mes = df_archivos[df_archivos['carpeta_mes'] != 'Base']['carpeta_mes'].unique()
        print(f"{list(carpetas_mes)}")
    
    return df_archivos

def extraer_rango_fechas(nombre_archivo):
    """
    Intenta extraer el rango de fechas del nombre del archivo
    
    Args:
        nombre_archivo (str): Nombre del archivo
    
    Returns:
        str: Rango de fechas extraído o None
    """
    import re
    
    # Patrones comunes para fechas
    patrones = [
        r'(\d{2}_\d{2})',  # Formato: 05_06
        r'(\d{2}_\d{2})\s+al\s+(\d{2}_\d{2})',  # Formato: 01_06 al 15_06
        r'(\d{1,2}-\d{1,2})',  # Formato: 1-6
        r'(\d{1,2}-\d{1,2})\s+al\s+(\d{1,2}-\d{1,2})'  # Formato: 1-6 al 15-6
    ]
    
    for patron in patrones:
        match = re.search(patron, nombre_archivo, re.IGNORECASE)
        if match:
            if len(match.groups()) == 1:
                return match.group(1)
            else:
                return f"{match.group(1)} al {match.group(2)}"
    
    return None

def mostrar_detalle_archivo(df_archivos, indice):
    """
    Muestra información detallada de un archivo específico
    
    Args:
        df_archivos (DataFrame): DataFrame con información de archivos
        indice (int): Índice del archivo a mostrar
    """
    if indice >= len(df_archivos):
        print(f"❌ Índice {indice} fuera de rango. Máximo: {len(df_archivos)-1}")
        return
    
    archivo = df_archivos.iloc[indice]
    
    print("📄 DETALLE DEL ARCHIVO:")
    print("=" * 30)
    print(f"Nombre: {archivo['nombre_archivo']}")
    print(f"Tipo: {archivo['tipo_archivo']}")
    print(f"Carpeta: {archivo['carpeta_mes']}")
    print(f"Ruta completa: {archivo['ruta_completa']}")
    print(f"Tamaño: {archivo['tamaño_kb']} KB")
    print(f"Modificado: {archivo['fecha_modificacion']}")
    if archivo['rango_fechas']:
        print(f"Rango fechas: {archivo['rango_fechas']}")

# Ejemplo de uso
if __name__ == "__main__":
    # Cambiar esta ruta por la tuya
    ruta_base = r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025"
    
    print("🚀 EXPLORADOR DE ARCHIVOS DE PAGOS")
    print("=" * 50)
    
    # Explorar archivos
    df_archivos = explorar_archivos_pagos(ruta_base)
    
    if not df_archivos.empty:
        print(f"\n📋 Lista completa de archivos:")
        print("-" * 30)
        for i, archivo in df_archivos.iterrows():
            print(f"{i:2d}. [{archivo['tipo_archivo']}] {archivo['nombre_archivo']} - {archivo['carpeta_mes']}")
        
        # Ejemplo de cómo ver detalles de un archivo específico
        # mostrar_detalle_archivo(df_archivos, 0)  # Ver primer archivo
        
        # Guardar lista en CSV para análisis posterior
        df_archivos.to_csv('lista_archivos_pagos.csv', index=False, encoding='utf-8')
        print(f"\n💾 Lista guardada en: lista_archivos_pagos.csv")
    else:
        print("❌ No se encontraron archivos .txt en la ruta especificada")

🚀 EXPLORADOR DE ARCHIVOS DE PAGOS
==================================================
🔍 Explorando: C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025
==================================================

📁 Directorio base: 2025
  📂 ABRIL
    📭 Sin archivos .txt
    📂 01_04_2025
      📄 Archivos encontrados: 3
        • Ap pagados 31_03.TXT (135.64 KB) - AP Pagados
          📅 Rango: 31_03
        • Comparendos pagados 01_03 al 31_03.TXT (3544.93 KB) - Comparendos Pagados
          📅 Rango: 01_03
        • Comparendos pagados 31_03.TXT (158.67 KB) - Comparendos Pagados
          📅 Rango: 31_03
    📂 02_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 01_04.TXT (100.32 KB) - AP Pagados
          📅 Rango: 01_04
        • Comparendos pagados 01_04.TXT (158.15 KB) - Comparendos Pagados
          📅 Rango: 01_04
    📂 03_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 02_03.TXT (77.28 KB) - AP Pagados
          📅 Rango: 02_03
        • Comparendos pagados 02_03.TXT (160.83 KB) - Comparendos Pagados
          📅 Rango: 02_03
    📂 04_04_2025
      📄 Archivos encontrados: 4
        • Ap pagados 01_03 al 31_03.TXT (2145.6 KB) - AP Pagados
          📅 Rango: 01_03
        • Ap pagados 03_04.TXT (104.01 KB) - AP Pagados
          📅 Rango: 03_04
        • Comparendos pagados 01_03 al 31_03.TXT (3544.64 KB) - Comparendos Pagados
          📅 Rango: 01_03
        • Comparendos pagados 03_04.TXT (145.91 KB) - Comparendos Pagados
          📅 Rango: 03_04
    📂 05_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 04_04.TXT (104.09 KB) - AP Pagados
          📅 Rango: 04_04
        • Comparendos pagados 04_04.TXT (153.36 KB) - Comparendos Pagados
          📅 Rango: 04_04
    📂 07_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 05_04 al 06_04.TXT (54.0 KB) - AP Pagados
          📅 Rango: 05_04
        • Comparendos pagados 05_04 al 06_04.TXT (63.76 KB) - Comparendos Pagados
          📅 Rango: 05_04
    📂 08_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 07_04.TXT (116.05 KB) - AP Pagados
          📅 Rango: 07_04
        • Comparendos pagados 07_04.TXT (144.34 KB) - Comparendos Pagados
          📅 Rango: 07_04
    📂 09_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 08_04.TXT (90.6 KB) - AP Pagados
          📅 Rango: 08_04
        • Comparendos pagados 08_04.TXT (162.69 KB) - Comparendos Pagados
          📅 Rango: 08_04
    📂 10_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 09_04.TXT (83.37 KB) - AP Pagados
          📅 Rango: 09_04
        • Comparendos pagados 09_04.TXT (153.31 KB) - Comparendos Pagados
          📅 Rango: 09_04
    📂 11_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 10_04.TXT (72.69 KB) - AP Pagados
          📅 Rango: 10_04
        • Comparendos pagados 10_04.TXT (143.91 KB) - Comparendos Pagados
          📅 Rango: 10_04
    📂 12_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 11_04.TXT (60.98 KB) - AP Pagados
          📅 Rango: 11_04
        • Comparendos pagados 11_04.TXT (134.76 KB) - Comparendos Pagados
          📅 Rango: 11_04
    📂 14_04_2025
      📄 Archivos encontrados: 4
        • Ap pagados 01_04 al 13_04.TXT (913.24 KB) - AP Pagados
          📅 Rango: 01_04
        • Ap pagados 12_04 al 13_04.TXT (51.74 KB) - AP Pagados
          📅 Rango: 12_04
        • Comparendos pagados 01_04 al 13_04.TXT (1491.64 KB) - Comparendos Pagados
          📅 Rango: 01_04
        • Comparendos pagados 12_04 al 13_04.TXT (72.24 KB) - Comparendos Pagados
          📅 Rango: 12_04
    📂 15_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 14_04.TXT (88.09 KB) - AP Pagados
          📅 Rango: 14_04
        • Comparendos pagados 14_04.TXT (148.45 KB) - Comparendos Pagados
          📅 Rango: 14_04
    📂 16_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 15_04.TXT (96.48 KB) - AP Pagados
          📅 Rango: 15_04
        • Comparendos pagados 15_04.TXT (130.63 KB) - Comparendos Pagados
          📅 Rango: 15_04
    📂 17_04_2025
      📭 Sin archivos .txt
    📂 18_04_2025
      📭 Sin archivos .txt
    📂 19_04_2025
      📭 Sin archivos .txt
    📂 21_04_2025
      📄 Archivos encontrados: 4
        • Ap pagados 01_04 al 20_04.TXT (1252.75 KB) - AP Pagados
          📅 Rango: 01_04
        • Ap pagados 16_04 al 20_04.TXT (168.48 KB) - AP Pagados
          📅 Rango: 16_04
        • Comparendos pagados 01_04 al 20_04.TXT (1924.6 KB) - Comparendos Pagados
          📅 Rango: 01_04
        • Comparendos pagados 16_04 al 20_04.TXT (154.37 KB) - Comparendos Pagados
          📅 Rango: 16_04
    📂 22_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 21_04.TXT (141.88 KB) - AP Pagados
          📅 Rango: 21_04
        • Comparendos pagados 21_04.TXT (125.17 KB) - Comparendos Pagados
          📅 Rango: 21_04
    📂 23_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 22_04.TXT (93.95 KB) - AP Pagados
          📅 Rango: 22_04
        • Comparendos pagados 22_04.TXT (148.42 KB) - Comparendos Pagados
          📅 Rango: 22_04
    📂 24_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 23_04.TXT (87.27 KB) - AP Pagados
          📅 Rango: 23_04
        • Comparendos pagados 23_04.TXT (160.2 KB) - Comparendos Pagados
          📅 Rango: 23_04
    📂 25_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 01_04 al 24_04.TXT (1644.49 KB) - AP Pagados
          📅 Rango: 01_04
        • Comparendos pagados 01_04 al 24_04.TXT (2493.91 KB) - Comparendos Pagados
          📅 Rango: 01_04
    📂 28_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 25_04 al 27_04.TXT (124.97 KB) - AP Pagados
          📅 Rango: 25_04
        • Comparendos pagados 25_04 al 27_04.TXT (168.78 KB) - Comparendos Pagados
          📅 Rango: 25_04
    📂 29_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 28_04.TXT (98.34 KB) - AP Pagados
          📅 Rango: 28_04
        • Comparendos pagados 28_04.TXT (108.5 KB) - Comparendos Pagados
          📅 Rango: 28_04
    📂 30_04_2025
      📄 Archivos encontrados: 2
        • Ap pagados 29_04.TXT (83.42 KB) - AP Pagados
          📅 Rango: 29_04
        • Comparendos pagados 29_04.TXT (115.6 KB) - Comparendos Pagados
          📅 Rango: 29_04
  📂 ENERO
    📭 Sin archivos .txt
    📂 02_01_2025
      📄 Archivos encontrados: 4
        • Ap pagados 01_12 al 31_12.TXT (1574.06 KB) - AP Pagados
          📅 Rango: 01_12
        • Ap pagados 31_12 al 01_01.TXT (23.88 KB) - AP Pagados
          📅 Rango: 31_12
        • Comparendos pagados 01_12 al 31_12.TXT (3004.48 KB) - Comparendos Pagados
          📅 Rango: 01_12
        • Comparendos pagados 31_12 al 01_01.TXT (6.4 KB) - Comparendos Pagados
          📅 Rango: 31_12
    📂 03_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 02_01.TXT (154.0 KB) - AP Pagados
          📅 Rango: 02_01
        • Comparendos pagados 02_01.TXT (222.04 KB) - Comparendos Pagados
          📅 Rango: 02_01
    📂 04_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 03_01.TXT (90.45 KB) - AP Pagados
          📅 Rango: 03_01
        • Comparendos pagados 03_01.TXT (96.0 KB) - Comparendos Pagados
          📅 Rango: 03_01
    📂 07_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 04_01 al 06_01.TXT (75.76 KB) - AP Pagados
          📅 Rango: 04_01
        • Comparendos pagados 04_01 al 06_01.TXT (55.91 KB) - Comparendos Pagados
          📅 Rango: 04_01
    📂 08_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 07_01.TXT (139.7 KB) - AP Pagados
          📅 Rango: 07_01
        • Comparendos pagados 07_01.TXT (136.22 KB) - Comparendos Pagados
          📅 Rango: 07_01
    📂 09_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 08_01.TXT (90.4 KB) - AP Pagados
          📅 Rango: 08_01
        • Comparendos pagados 08_01.TXT (128.91 KB) - Comparendos Pagados
          📅 Rango: 08_01
    📂 10_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 09_01.TXT (94.13 KB) - AP Pagados
          📅 Rango: 09_01
        • Comparendos pagados 09_01.TXT (128.89 KB) - Comparendos Pagados
          📅 Rango: 09_01
    📂 13_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 10_ al 12_01.TXT (119.03 KB) - AP Pagados
          📅 Rango: 12_01
        • Comparendos pagados 10_ al 12_01.TXT (179.48 KB) - Comparendos Pagados
          📅 Rango: 12_01
    📂 14_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 13_01.TXT (100.63 KB) - AP Pagados
          📅 Rango: 13_01
        • Comparendos pagados 13_01.TXT (153.75 KB) - Comparendos Pagados
          📅 Rango: 13_01
    📂 15_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 14_01.TXT (88.24 KB) - AP Pagados
          📅 Rango: 14_01
        • Comparendos pagados 14_01.TXT (159.48 KB) - Comparendos Pagados
          📅 Rango: 14_01
    📂 16_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 15_01.TXT (97.72 KB) - AP Pagados
          📅 Rango: 15_01
        • Comparendos pagados 15_01.TXT (158.97 KB) - Comparendos Pagados
          📅 Rango: 15_01
    📂 17_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 16_01.TXT (104.45 KB) - AP Pagados
          📅 Rango: 16_01
        • Comparendos pagados 16_01.TXT (171.31 KB) - Comparendos Pagados
          📅 Rango: 16_01
    📂 18_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 17_01.TXT (81.99 KB) - AP Pagados
          📅 Rango: 17_01
        • Comparendos pagados 17_01.TXT (201.67 KB) - Comparendos Pagados
          📅 Rango: 17_01
    📂 20_01_2025
      📄 Archivos encontrados: 6
        • AP pagados 01_01  al 19_01.TXT (1220.19 KB) - AP Pagados
          📅 Rango: 01_01
        • Ap pagados 18_01 al 19_01.TXT (31.47 KB) - AP Pagados
          📅 Rango: 18_01
        • AP PAGADOS DEL 18_01 AL 19_01.TXT (31.47 KB) - AP Pagados
          📅 Rango: 18_01
        • Comparendos pagados 01_01 al 19_01.TXT (1875.64 KB) - Comparendos Pagados
          📅 Rango: 01_01
        • Comparendos pagados 18_01 al 19_01.TXT (78.66 KB) - Comparendos Pagados
          📅 Rango: 18_01
        • COMPARENDOS PAGADOS DEL 18_01 AL 19_01.TXT (78.66 KB) - Comparendos Pagados
          📅 Rango: 18_01
    📂 21_01_2025
      📄 Archivos encontrados: 2
        • AP PAGADOS 20_01.TXT (107.99 KB) - AP Pagados
          📅 Rango: 20_01
        • COMPARENDOS PAGADOS 20_01.TXT (165.57 KB) - Comparendos Pagados
          📅 Rango: 20_01
    📂 22_01_2025
      📄 Archivos encontrados: 2
        • A p pagados 21_01.TXT (72.56 KB) - Desconocido
          📅 Rango: 21_01
        • Comparendos pagados 21_01.TXT (136.32 KB) - Comparendos Pagados
          📅 Rango: 21_01
    📂 23_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados  22_01.TXT (67.27 KB) - AP Pagados
          📅 Rango: 22_01
        • Comparendos pagados  22_01.TXT (146.81 KB) - Comparendos Pagados
          📅 Rango: 22_01
    📂 24_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 23_01.TXT (66.06 KB) - AP Pagados
          📅 Rango: 23_01
        • Comparendos pagados 23_01.TXT (152.65 KB) - Comparendos Pagados
          📅 Rango: 23_01
    📂 27_01_2025
      📄 Archivos encontrados: 4
        • Ap pagados 01_01 al 26_01.TXT (1624.08 KB) - AP Pagados
          📅 Rango: 01_01
        • Ap pagados 24_01 al 26_01.TXT (91.08 KB) - AP Pagados
          📅 Rango: 24_01
        • Comparendos pagados 01_01 al 26_01.TXT (2688.36 KB) - Comparendos Pagados
          📅 Rango: 01_01
        • Comparendos pagados 24_01 al 26_01.TXT (211.82 KB) - Comparendos Pagados
          📅 Rango: 24_01
    📂 28_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 27_01.TXT (98.36 KB) - AP Pagados
          📅 Rango: 27_01
        • Comparendos pagados 27_01.TXT (171.11 KB) - Comparendos Pagados
          📅 Rango: 27_01
    📂 29_01_2025
      📄 Archivos encontrados: 3
        • Ap pagados 28_01.TXT (58.91 KB) - AP Pagados
          📅 Rango: 28_01
        • Comparendos pagados 28_01.TXT (117.75 KB) - Comparendos Pagados
          📅 Rango: 28_01
        • Comparendos pagados 28_01_V2.TXT (117.7 KB) - Comparendos Pagados
          📅 Rango: 28_01
    📂 30_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 29_01.TXT (65.09 KB) - AP Pagados
          📅 Rango: 29_01
        • Comparendos pagados 29_01.TXT (204.19 KB) - Comparendos Pagados
          📅 Rango: 29_01
    📂 31_01_2025
      📄 Archivos encontrados: 2
        • Ap pagados 30_01.TXT (92.35 KB) - AP Pagados
          📅 Rango: 30_01
        • Comparendo pagados 30_01.TXT (171.85 KB) - Desconocido
          📅 Rango: 30_01
  📂 FEBRERO
    📭 Sin archivos .txt
    📂 01_02_2025
      📄 Archivos encontrados: 3
        • Ap pagados 31_01.TXT (86.23 KB) - AP Pagados
          📅 Rango: 31_01
        • Comparendos pagados 31_01.TXT (156.2 KB) - Comparendos Pagados
          📅 Rango: 31_01
        • Comparendos pagados del 01_01 al 31_01.TXT (3508.17 KB) - Comparendos Pagados
          📅 Rango: 01_01
    📂 03_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 01_02 al 02_02.TXT (55.21 KB) - AP Pagados
          📅 Rango: 01_02
        • Comparendos pagados 01_02 al 02_02.TXT (83.39 KB) - Comparendos Pagados
          📅 Rango: 01_02
    📂 04_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 03_02.TXT (121.82 KB) - AP Pagados
          📅 Rango: 03_02
        • Comparendos pagados 03_02.TXT (173.24 KB) - Comparendos Pagados
          📅 Rango: 03_02
    📂 05_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 04_02.TXT (80.95 KB) - AP Pagados
          📅 Rango: 04_02
        • Comparendos pagados 04_02.TXT (167.88 KB) - Comparendos Pagados
          📅 Rango: 04_02
    📂 06_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 05_02.TXT (97.14 KB) - AP Pagados
          📅 Rango: 05_02
        • Comparendos pagados 05_02.TXT (172.98 KB) - Comparendos Pagados
          📅 Rango: 05_02
    📂 07_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 06_02.TXT (78.96 KB) - AP Pagados
          📅 Rango: 06_02
        • Comparendos pagados 06_02.TXT (155.03 KB) - Comparendos Pagados
          📅 Rango: 06_02
    📂 10_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 07_02 al 09_02.TXT (105.17 KB) - AP Pagados
          📅 Rango: 07_02
        • Comparendos pagados 07_02 al 09_02.TXT (235.47 KB) - Comparendos Pagados
          📅 Rango: 07_02
    📂 11_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 10_02.TXT (107.56 KB) - AP Pagados
          📅 Rango: 10_02
        • Comparendos pagados 10_02.TXT (155.03 KB) - Comparendos Pagados
          📅 Rango: 10_02
    📂 12_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 11_02.TXT (84.4 KB) - AP Pagados
          📅 Rango: 11_02
        • Comparedos pagados 11_02.TXT (137.51 KB) - Desconocido
          📅 Rango: 11_02
    📂 13_02_2025
      📄 Archivos encontrados: 4
        • Ap pagados 01_02 al 12_02.TXT (778.17 KB) - AP Pagados
          📅 Rango: 01_02
        • Ap pagados 12_02.TXT (79.9 KB) - AP Pagados
          📅 Rango: 12_02
        • Comparendos pagados 01_02 al 12_02.TXT (1407.89 KB) - Comparendos Pagados
          📅 Rango: 01_02
        • Comparendos pagados 12_02.TXT (128.62 KB) - Comparendos Pagados
          📅 Rango: 12_02
    📂 14_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 13_02.TXT (94.78 KB) - AP Pagados
          📅 Rango: 13_02
        • Comparendos pagados 13_02.TXT (129.48 KB) - Comparendos Pagados
          📅 Rango: 13_02
    📂 15_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 14_02.TXT (98.07 KB) - AP Pagados
          📅 Rango: 14_02
        • Comparendos pagados 14_02.TXT (129.23 KB) - Comparendos Pagados
          📅 Rango: 14_02
    📂 17_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 15_02 al 16_02.TXT (66.92 KB) - AP Pagados
          📅 Rango: 15_02
        • Comparendos pagados 15_02 al 16_02.TXT (59.2 KB) - Comparendos Pagados
          📅 Rango: 15_02
    📂 18_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 17_02.TXT (141.08 KB) - AP Pagados
          📅 Rango: 17_02
        • Comparendos pagados 17_02.TXT (134.98 KB) - Comparendos Pagados
          📅 Rango: 17_02
    📂 19_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 18_02.TXT (89.43 KB) - AP Pagados
          📅 Rango: 18_02
        • Comparendos pagados 18_02.TXT (114.68 KB) - Comparendos Pagados
          📅 Rango: 18_02
    📂 20_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 19_02.TXT (69.49 KB) - AP Pagados
          📅 Rango: 19_02
        • Comparendos pagados 19_02.TXT (158.35 KB) - Comparendos Pagados
          📅 Rango: 19_02
    📂 21_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 20_02.TXT (71.34 KB) - AP Pagados
          📅 Rango: 20_02
        • Comparendos pagados 20_02.TXT (144.89 KB) - Comparendos Pagados
          📅 Rango: 20_02
    📂 22_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 20_02.TXT (71.34 KB) - AP Pagados
          📅 Rango: 20_02
        • Comparendos pagados 20_02.TXT (144.89 KB) - Comparendos Pagados
          📅 Rango: 20_02
    📂 24_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 21_02 al 23_02.TXT (104.84 KB) - AP Pagados
          📅 Rango: 21_02
        • Comparendos pagados 21_02 al 23_02.TXT (206.98 KB) - Comparendos Pagados
          📅 Rango: 21_02
    📂 25_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 24_02.TXT (84.56 KB) - AP Pagados
          📅 Rango: 24_02
        • Comparendos pagados 24_02.TXT (146.0 KB) - Comparendos Pagados
          📅 Rango: 24_02
    📂 26_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 25_02.TXT (61.77 KB) - AP Pagados
          📅 Rango: 25_02
        • Comparendos pagados 25_02.TXT (138.22 KB) - Comparendos Pagados
          📅 Rango: 25_02
    📂 27_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 26_02.TXT (54.66 KB) - AP Pagados
          📅 Rango: 26_02
        • Comparendos pagados 26_02.TXT (140.02 KB) - Comparendos Pagados
          📅 Rango: 26_02
    📂 28_02_2025
      📄 Archivos encontrados: 2
        • Ap pagados 27_02.TXT (82.6 KB) - AP Pagados
          📅 Rango: 27_02
        • Comparendos pagados 27_02.TXT (144.73 KB) - Comparendos Pagados
          📅 Rango: 27_02
  📂 JUNIO
    📭 Sin archivos .txt
    📂 03_06_2025
      📄 Archivos encontrados: 4
        • Ap pagados 01_05 al 31_05.TXT (2347.05 KB) - AP Pagados
          📅 Rango: 01_05
        • Ap pagados 01_06 al 02_06.TXT (43.46 KB) - AP Pagados
          📅 Rango: 01_06
        • Comparendos pagados 01_05 al 31_05.TXT (3068.6 KB) - Comparendos Pagados
          📅 Rango: 01_05
        • Comparendos pagados 01_06 al 02_06.TXT (10.97 KB) - Comparendos Pagados
          📅 Rango: 01_06
    📂 04_06_2025
      📄 Archivos encontrados: 2
        • Ap pagados 03_06.TXT (113.68 KB) - AP Pagados
          📅 Rango: 03_06
        • Comparendos pagados 03_06.TXT (126.84 KB) - Comparendos Pagados
          📅 Rango: 03_06
    📂 05_06_2025
      📄 Archivos encontrados: 2
        • Ap pagados 04_06.TXT (107.48 KB) - AP Pagados
          📅 Rango: 04_06
        • Comparendos pagados 04_06.TXT (158.0 KB) - Comparendos Pagados
          📅 Rango: 04_06
    📂 06_06_2025
      📄 Archivos encontrados: 2
        • Ap pagados 05_06.TXT (109.1 KB) - AP Pagados
          📅 Rango: 05_06
        • Comparendos pagados 05_06.TXT (148.44 KB) - Comparendos Pagados
          📅 Rango: 05_06
    📂 09_06_2025
      📄 Archivos encontrados: 2
        • Ap pagados 06_06 al 08_06.TXT (152.04 KB) - AP Pagados
          📅 Rango: 06_06
        • Comparendos pagados 06_06 al 08_06.TXT (193.79 KB) - Comparendos Pagados
          📅 Rango: 06_06
    📂 10_06_2025
      📄 Archivos encontrados: 2
        • Ap pagados 09_06.TXT (116.37 KB) - AP Pagados
          📅 Rango: 09_06
        • Comparendos pagados 09_06.TXT (197.12 KB) - Comparendos Pagados
          📅 Rango: 09_06
    📂 11_06_2025
      📄 Archivos encontrados: 2
        • Ap pagados 10_06.TXT (88.6 KB) - AP Pagados
          📅 Rango: 10_06

In [3]:
import os
import pandas as pd
from datetime import datetime
from pathlib import Path
import chardet

def detectar_encoding(ruta_archivo):
    """
    Detecta la codificación de un archivo de texto
    
    Args:
        ruta_archivo (str): Ruta del archivo
    
    Returns:
        str: Codificación detectada
    """
    try:
        with open(ruta_archivo, 'rb') as f:
            muestra = f.read(10000)  # Leer primeros 10KB
            resultado = chardet.detect(muestra)
            return resultado['encoding'] if resultado['encoding'] else 'utf-8'
    except:
        return 'utf-8'

def leer_archivo_txt(ruta_archivo):
    """
    Lee un archivo TXT y devuelve un DataFrame
    
    Args:
        ruta_archivo (str): Ruta del archivo
    
    Returns:
        DataFrame: Datos del archivo o DataFrame vacío si hay error
    """
    try:
        # Detectar encoding
        encoding = detectar_encoding(ruta_archivo)
        
        # Intentar diferentes separadores
        separadores = ['\t', '|', ';', ',']
        
        for sep in separadores:
            try:
                df = pd.read_csv(ruta_archivo, 
                               sep=sep, 
                               encoding=encoding,
                               low_memory=False)
                
                # Verificar que tenga más de una columna
                if len(df.columns) > 1:
                    # Agregar metadatos del archivo
                    df['archivo_origen'] = os.path.basename(ruta_archivo)
                    df['ruta_archivo'] = ruta_archivo
                    df['fecha_procesamiento'] = datetime.now()
                    
                    return df
            except Exception as e:
                continue
        
        # Si no funciona con separadores, intentar leer como texto plano
        with open(ruta_archivo, 'r', encoding=encoding) as f:
            lineas = f.readlines()
            
        if lineas:
            print(f"⚠️  {os.path.basename(ruta_archivo)}: No se pudo determinar separador automáticamente")
            print(f"   Primeras líneas del archivo:")
            for i, linea in enumerate(lineas[:3]):
                print(f"   {i+1}: {linea.strip()}")
            
        return pd.DataFrame()
        
    except Exception as e:
        print(f"❌ Error leyendo {os.path.basename(ruta_archivo)}: {e}")
        return pd.DataFrame()

def explorar_y_consolidar(ruta_base):
    """
    Explora la estructura y consolida archivos por tipo
    
    Args:
        ruta_base (str): Ruta principal donde están las carpetas
    
    Returns:
        tuple: (df_ap_pagados, df_comparendos, info_procesamiento)
    """
    
    print(f"🔍 Explorando y consolidando archivos en: {ruta_base}")
    print("=" * 60)
    
    # Listas para almacenar DataFrames
    dfs_ap_pagados = []
    dfs_comparendos = []
    
    # Información de procesamiento
    info_procesamiento = {
        'archivos_ap_procesados': 0,
        'archivos_ap_error': 0,
        'archivos_comparendos_procesados': 0,
        'archivos_comparendos_error': 0,
        'archivos_ignorados': 0,
        'detalle_errores': []
    }
    
    # Recorrer todos los archivos
    for root, dirs, files in os.walk(ruta_base):
        archivos_txt = [f for f in files if f.lower().endswith('.txt')]
        
        if archivos_txt:
            carpeta_actual = os.path.basename(root)
            ruta_relativa = os.path.relpath(root, ruta_base)
            
            print(f"\n📂 Procesando carpeta: {ruta_relativa}")
            
            for archivo in archivos_txt:
                ruta_completa = os.path.join(root, archivo)
                nombre_lower = archivo.lower()
                
                print(f"   📄 {archivo} ... ", end="")
                
                # Clasificar tipo de archivo
                if "ap pagados" in nombre_lower:
                    df = leer_archivo_txt(ruta_completa)
                    if not df.empty:
                        # Agregar información adicional
                        df['carpeta_origen'] = carpeta_actual
                        df['ruta_relativa'] = ruta_relativa
                        
                        dfs_ap_pagados.append(df)
                        info_procesamiento['archivos_ap_procesados'] += 1
                        print(f"✅ AP ({len(df)} registros)")
                    else:
                        info_procesamiento['archivos_ap_error'] += 1
                        info_procesamiento['detalle_errores'].append(f"AP: {archivo}")
                        print("❌ Error")
                
                elif "comparendos pagados" in nombre_lower:
                    df = leer_archivo_txt(ruta_completa)
                    if not df.empty:
                        # Agregar información adicional
                        df['carpeta_origen'] = carpeta_actual
                        df['ruta_relativa'] = ruta_relativa
                        
                        dfs_comparendos.append(df)
                        info_procesamiento['archivos_comparendos_procesados'] += 1
                        print(f"✅ COMPARENDOS ({len(df)} registros)")
                    else:
                        info_procesamiento['archivos_comparendos_error'] += 1
                        info_procesamiento['detalle_errores'].append(f"COMPARENDOS: {archivo}")
                        print("❌ Error")
                
                else:
                    info_procesamiento['archivos_ignorados'] += 1
                    print("⏭️  Ignorado (no es AP ni Comparendos)")
    
    # Consolidar DataFrames
    print(f"\n🔄 Consolidando datos...")
    
    df_ap_consolidado = pd.DataFrame()
    if dfs_ap_pagados:
        try:
            df_ap_consolidado = pd.concat(dfs_ap_pagados, ignore_index=True)
            print(f"✅ AP Pagados consolidado: {len(df_ap_consolidado)} registros totales")
        except Exception as e:
            print(f"❌ Error consolidando AP Pagados: {e}")
    
    df_comparendos_consolidado = pd.DataFrame()
    if dfs_comparendos:
        try:
            df_comparendos_consolidado = pd.concat(dfs_comparendos, ignore_index=True)
            print(f"✅ Comparendos consolidado: {len(df_comparendos_consolidado)} registros totales")
        except Exception as e:
            print(f"❌ Error consolidando Comparendos: {e}")
    
    return df_ap_consolidado, df_comparendos_consolidado, info_procesamiento

def mostrar_resumen_consolidacion(df_ap, df_comparendos, info):
    """
    Muestra un resumen de la consolidación
    """
    print(f"\n📊 RESUMEN DE CONSOLIDACIÓN")
    print("=" * 40)
    
    print(f"\n🏦 AP PAGADOS:")
    print(f"   Archivos procesados: {info['archivos_ap_procesados']}")
    print(f"   Archivos con error: {info['archivos_ap_error']}")
    if not df_ap.empty:
        print(f"   Total registros: {len(df_ap):,}")
        print(f"   Columnas encontradas: {list(df_ap.columns[:10])}{'...' if len(df_ap.columns) > 10 else ''}")
        print(f"   Archivos origen únicos: {df_ap['archivo_origen'].nunique()}")
    
    print(f"\n🚔 COMPARENDOS PAGADOS:")
    print(f"   Archivos procesados: {info['archivos_comparendos_procesados']}")
    print(f"   Archivos con error: {info['archivos_comparendos_error']}")
    if not df_comparendos.empty:
        print(f"   Total registros: {len(df_comparendos):,}")
        print(f"   Columnas encontradas: {list(df_comparendos.columns[:10])}{'...' if len(df_comparendos.columns) > 10 else ''}")
        print(f"   Archivos origen únicos: {df_comparendos['archivo_origen'].nunique()}")
    
    print(f"\n📁 OTROS:")
    print(f"   Archivos ignorados: {info['archivos_ignorados']}")
    
    if info['detalle_errores']:
        print(f"\n❌ ERRORES DETALLADOS:")
        for error in info['detalle_errores']:
            print(f"   • {error}")

def analizar_estructura_datos(df, nombre_tipo):
    """
    Analiza la estructura de un DataFrame consolidado
    """
    if df.empty:
        print(f"\n📋 {nombre_tipo}: Sin datos para analizar")
        return
    
    print(f"\n📋 ANÁLISIS DE {nombre_tipo}")
    print("-" * 30)
    
    print(f"📌 Información básica:")
    print(f"   Registros: {len(df):,}")
    print(f"   Columnas: {len(df.columns)}")
    print(f"   Archivos origen: {df['archivo_origen'].nunique()}")
    
    print(f"\n📌 Columnas disponibles:")
    # Excluir columnas de metadatos
    columnas_datos = [col for col in df.columns if col not in 
                     ['archivo_origen', 'ruta_archivo', 'fecha_procesamiento', 'carpeta_origen', 'ruta_relativa']]
    
    for i, col in enumerate(columnas_datos, 1):
        tipo_datos = str(df[col].dtype)
        valores_unicos = df[col].nunique()
        valores_nulos = df[col].isnull().sum()
        
        print(f"   {i:2d}. {col} ({tipo_datos}) - {valores_unicos:,} únicos, {valores_nulos:,} nulos")
        
        # Mostrar muestra de valores para las primeras columnas
        if i <= 5:
            muestra = df[col].dropna().head(3).tolist()
            print(f"       Muestra: {muestra}")
    
    print(f"\n📌 Distribución por archivo origen:")
    distribucion = df['archivo_origen'].value_counts().head(10)
    for archivo, cantidad in distribucion.items():
        print(f"   • {archivo}: {cantidad:,} registros")
    
    if len(df['archivo_origen'].unique()) > 10:
        print(f"   ... y {len(df['archivo_origen'].unique()) - 10} archivos más")

# Función principal
def main(ruta_base):
    """
    Función principal para consolidar archivos
    """
    print("🚀 CONSOLIDADOR DE ARCHIVOS DE PAGOS")
    print("=" * 50)
    
    # Consolidar archivos
    df_ap, df_comparendos, info = explorar_y_consolidar(ruta_base)
    
    # Mostrar resumen
    mostrar_resumen_consolidacion(df_ap, df_comparendos, info)
    
    # Análisis detallado
    analizar_estructura_datos(df_ap, "AP PAGADOS")
    analizar_estructura_datos(df_comparendos, "COMPARENDOS PAGADOS")
    
    # Guardar archivos consolidados
    if not df_ap.empty:
        archivo_ap = 'ap_pagados_consolidado.csv'
        df_ap.to_csv(archivo_ap, index=False, encoding='utf-8')
        print(f"\n💾 AP Pagados guardado en: {archivo_ap}")
    
    if not df_comparendos.empty:
        archivo_comp = 'comparendos_pagados_consolidado.csv'
        df_comparendos.to_csv(archivo_comp, index=False, encoding='utf-8')
        print(f"💾 Comparendos guardado en: {archivo_comp}")
    
    return df_ap, df_comparendos, info

# Ejemplo de uso
if __name__ == "__main__":
    # Cambiar por tu ruta
    ruta_base = r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025"
    
    df_ap_pagados, df_comparendos_pagados, info_procesamiento = main(ruta_base)

🚀 CONSOLIDADOR DE ARCHIVOS DE PAGOS
==================================================
🔍 Explorando y consolidando archivos en: C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025
============================================================

📂 Procesando carpeta: ABRIL\01_04_2025
   📄 Ap pagados 31_03.TXT ... ✅ AP (989 registros)
   📄 Comparendos pagados 01_03 al 31_03.TXT ... ✅ COMPARENDOS (34580 registros)
   📄 Comparendos pagados 31_03.TXT ... ✅ COMPARENDOS (1534 registros)

📂 Procesando carpeta: ABRIL\02_04_2025
   📄 Ap pagados 01_04.TXT ... ✅ AP (731 registros)
   📄 Comparendos pagados 01_04.TXT ... ✅ COMPARENDOS (1539 registros)

📂 Procesando carpeta: ABRIL\03_04_2025
   📄 Ap pagados 02_03.TXT ... ✅ AP (563 registros)
   📄 Comparendos pagados 02_03.TXT ... ✅ COMPARENDOS (1559 registros)

📂 Procesando carpeta: ABRIL\04_04_2025
   📄 Ap pagados 01_03 al 31_03.TXT ... ✅ AP (15646 registros)
   📄 Ap pagados 03_04.TXT ... ✅ AP (756 registros)
   📄 Comparendos pagados 01_03 al 31_03.TXT ... ✅ COMPARENDOS (34580 registros)
   📄 Comparendos pagados 03_04.TXT ... ✅ COMPARENDOS (1419 registros)

📂 Procesando carpeta: ABRIL\05_04_2025
   📄 Ap pagados 04_04.TXT ... ✅ AP (761 registros)
   📄 Comparendos pagados 04_04.TXT ... ✅ COMPARENDOS (1497 registros)

📂 Procesando carpeta: ABRIL\07_04_2025
   📄 Ap pagados 05_04 al 06_04.TXT ... ✅ AP (391 registros)
   📄 Comparendos pagados 05_04 al 06_04.TXT ... ✅ COMPARENDOS (623 registros)

📂 Procesando carpeta: ABRIL\08_04_2025
   📄 Ap pagados 07_04.TXT ... ✅ AP (846 registros)
   📄 Comparendos pagados 07_04.TXT ... ✅ COMPARENDOS (1400 registros)

📂 Procesando carpeta: ABRIL\09_04_2025
   📄 Ap pagados 08_04.TXT ... ✅ AP (659 registros)
   📄 Comparendos pagados 08_04.TXT ... ✅ COMPARENDOS (1584 registros)

📂 Procesando carpeta: ABRIL\10_04_2025
   📄 Ap pagados 09_04.TXT ... ✅ AP (606 registros)
   📄 Comparendos pagados 09_04.TXT ... ✅ COMPARENDOS (1494 registros)

📂 Procesando carpeta: ABRIL\11_04_2025
   📄 Ap pagados 10_04.TXT ... ✅ AP (529 registros)
   📄 Comparendos pagados 10_04.TXT ... ✅ COMPARENDOS (1376 registros)

📂 Procesando carpeta: ABRIL\12_04_2025
   📄 Ap pagados 11_04.TXT ... ✅ AP (446 registros)
   📄 Comparendos pagados 11_04.TXT ... ✅ COMPARENDOS (1295 registros)

📂 Procesando carpeta: ABRIL\14_04_2025
   📄 Ap pagados 01_04 al 13_04.TXT ... ✅ AP (6665 registros)
   📄 Ap pagados 12_04 al 13_04.TXT ... ✅ AP (377 registros)
   📄 Comparendos pagados 01_04 al 13_04.TXT ... ✅ COMPARENDOS (14488 registros)
   📄 Comparendos pagados 12_04 al 13_04.TXT ... ✅ COMPARENDOS (702 registros)

📂 Procesando carpeta: ABRIL\15_04_2025
   📄 Ap pagados 14_04.TXT ... ✅ AP (641 registros)
   📄 Comparendos pagados 14_04.TXT ... ✅ COMPARENDOS (1435 registros)

📂 Procesando carpeta: ABRIL\16_04_2025
   📄 Ap pagados 15_04.TXT ... ✅ AP (703 registros)
   📄 Comparendos pagados 15_04.TXT ... ✅ COMPARENDOS (1265 registros)

📂 Procesando carpeta: ABRIL\21_04_2025
   📄 Ap pagados 01_04 al 20_04.TXT ... ✅ AP (9142 registros)
   📄 Ap pagados 16_04 al 20_04.TXT ... ✅ AP (1227 registros)
   📄 Comparendos pagados 01_04 al 20_04.TXT ... ✅ COMPARENDOS (18685 registros)
   📄 Comparendos pagados 16_04 al 20_04.TXT ... ✅ COMPARENDOS (1497 registros)

📂 Procesando carpeta: ABRIL\22_04_2025
   📄 Ap pagados 21_04.TXT ... ✅ AP (1031 registros)
   📄 Comparendos pagados 21_04.TXT ... ✅ COMPARENDOS (1205 registros)

📂 Procesando carpeta: ABRIL\23_04_2025
   📄 Ap pagados 22_04.TXT ... ❌ Error leyendo Ap pagados 22_04.TXT: 'johab' codec can't decode byte 0xc9 in position 1896: illegal multibyte sequence
❌ Error
   📄 Comparendos pagados 22_04.TXT ... ✅ COMPARENDOS (1440 registros)

📂 Procesando carpeta: ABRIL\24_04_2025
   📄 Ap pagados 23_04.TXT ... ✅ AP (635 registros)
   📄 Comparendos pagados 23_04.TXT ... ✅ COMPARENDOS (1560 registros)

📂 Procesando carpeta: ABRIL\25_04_2025
   📄 Ap pagados 01_04 al 24_04.TXT ... ✅ AP (11995 registros)
   📄 Comparendos pagados 01_04 al 24_04.TXT ... ✅ COMPARENDOS (24211 registros)

📂 Procesando carpeta: ABRIL\28_04_2025
   📄 Ap pagados 25_04 al 27_04.TXT ... ✅ AP (910 registros)
   📄 Comparendos pagados 25_04 al 27_04.TXT ... ✅ COMPARENDOS (1625 registros)

📂 Procesando carpeta: ABRIL\29_04_2025
   📄 Ap pagados 28_04.TXT ... ✅ AP (718 registros)
   📄 Comparendos pagados 28_04.TXT ... ✅ COMPARENDOS (1050 registros)

📂 Procesando carpeta: ABRIL\30_04_2025
   📄 Ap pagados 29_04.TXT ... ✅ AP (608 registros)
   📄 Comparendos pagados 29_04.TXT ... ✅ COMPARENDOS (1115 registros)

📂 Procesando carpeta: ENERO\02_01_2025
   📄 Ap pagados 01_12 al 31_12.TXT ... ✅ AP (11471 registros)
   📄 Ap pagados 31_12 al 01_01.TXT ... ✅ AP (172 registros)
   📄 Comparendos pagados 01_12 al 31_12.TXT ... ✅ COMPARENDOS (29256 registros)
   📄 Comparendos pagados 31_12 al 01_01.TXT ... ✅ COMPARENDOS (62 registros)

📂 Procesando carpeta: ENERO\03_01_2025
   📄 Ap pagados 02_01.TXT ... ✅ AP (1117 registros)
   📄 Comparendos pagados 02_01.TXT ... ✅ COMPARENDOS (2157 registros)

📂 Procesando carpeta: ENERO\04_01_2025
   📄 Ap pagados 03_01.TXT ... ✅ AP (658 registros)
   📄 Comparendos pagados 03_01.TXT ... ✅ COMPARENDOS (930 registros)

📂 Procesando carpeta: ENERO\07_01_2025
   📄 Ap pagados 04_01 al 06_01.TXT ... ✅ AP (551 registros)
   📄 Comparendos pagados 04_01 al 06_01.TXT ... ✅ COMPARENDOS (548 registros)

📂 Procesando carpeta: ENERO\08_01_2025
   📄 Ap pagados 07_01.TXT ... ✅ AP (1015 registros)
   📄 Comparendos pagados 07_01.TXT ... ✅ COMPARENDOS (1321 registros)

📂 Procesando carpeta: ENERO\09_01_2025
   📄 Ap pagados 08_01.TXT ... ✅ AP (660 registros)
   📄 Comparendos pagados 08_01.TXT ... ✅ COMPARENDOS (1254 registros)

📂 Procesando carpeta: ENERO\10_01_2025
   📄 Ap pagados 09_01.TXT ... ✅ AP (685 registros)
   📄 Comparendos pagados 09_01.TXT ... ✅ COMPARENDOS (1265 registros)

📂 Procesando carpeta: ENERO\13_01_2025
   📄 Ap pagados 10_ al 12_01.TXT ... ✅ AP (865 registros)
   📄 Comparendos pagados 10_ al 12_01.TXT ... ✅ COMPARENDOS (1760 registros)

📂 Procesando carpeta: ENERO\14_01_2025
   📄 Ap pagados 13_01.TXT ... ✅ AP (732 registros)
   📄 Comparendos pagados 13_01.TXT ... ✅ COMPARENDOS (1498 registros)

📂 Procesando carpeta: ENERO\15_01_2025
   📄 Ap pagados 14_01.TXT ... ✅ AP (641 registros)
   📄 Comparendos pagados 14_01.TXT ... ✅ COMPARENDOS (1557 registros)

📂 Procesando carpeta: ENERO\16_01_2025
   📄 Ap pagados 15_01.TXT ... ✅ AP (710 registros)
   📄 Comparendos pagados 15_01.TXT ... ✅ COMPARENDOS (1562 registros)

📂 Procesando carpeta: ENERO\17_01_2025
   📄 Ap pagados 16_01.TXT ... ✅ AP (760 registros)
   📄 Comparendos pagados 16_01.TXT ... ✅ COMPARENDOS (1680 registros)

📂 Procesando carpeta: ENERO\18_01_2025
   📄 Ap pagados 17_01.TXT ... ✅ AP (595 registros)
   📄 Comparendos pagados 17_01.TXT ... ✅ COMPARENDOS (1978 registros)

📂 Procesando carpeta: ENERO\20_01_2025
   📄 AP pagados 01_01  al 19_01.TXT ... ✅ AP (8888 registros)
   📄 Ap pagados 18_01 al 19_01.TXT ... ✅ AP (229 registros)
   📄 AP PAGADOS DEL 18_01 AL 19_01.TXT ... ✅ AP (229 registros)
   📄 Comparendos pagados 01_01 al 19_01.TXT ... ✅ COMPARENDOS (18350 registros)
   📄 Comparendos pagados 18_01 al 19_01.TXT ... ✅ COMPARENDOS (779 registros)
   📄 COMPARENDOS PAGADOS DEL 18_01 AL 19_01.TXT ... ✅ COMPARENDOS (779 registros)

📂 Procesando carpeta: ENERO\21_01_2025
   📄 AP PAGADOS 20_01.TXT ... ✅ AP (784 registros)
   📄 COMPARENDOS PAGADOS 20_01.TXT ... ✅ COMPARENDOS (1622 registros)

📂 Procesando carpeta: ENERO\22_01_2025
   📄 A p pagados 21_01.TXT ... ⏭️  Ignorado (no es AP ni Comparendos)
   📄 Comparendos pagados 21_01.TXT ... ✅ COMPARENDOS (1335 registros)

📂 Procesando carpeta: ENERO\23_01_2025
   📄 Ap pagados  22_01.TXT ... ✅ AP (489 registros)
   📄 Comparendos pagados  22_01.TXT ... ✅ COMPARENDOS (1428 registros)

📂 Procesando carpeta: ENERO\24_01_2025
   📄 Ap pagados 23_01.TXT ... ✅ AP (480 registros)
   📄 Comparendos pagados 23_01.TXT ... ✅ COMPARENDOS (1492 registros)

📂 Procesando carpeta: ENERO\27_01_2025
   📄 Ap pagados 01_01 al 26_01.TXT ... ✅ AP (11830 registros)
   📄 Ap pagados 24_01 al 26_01.TXT ... ✅ AP (662 registros)
   📄 Comparendos pagados 01_01 al 26_01.TXT ... ✅ COMPARENDOS (26299 registros)
   📄 Comparendos pagados 24_01 al 26_01.TXT ... ✅ COMPARENDOS (2068 registros)

📂 Procesando carpeta: ENERO\28_01_2025
   📄 Ap pagados 27_01.TXT ... ✅ AP (716 registros)
   📄 Comparendos pagados 27_01.TXT ... ✅ COMPARENDOS (1664 registros)

📂 Procesando carpeta: ENERO\29_01_2025
   📄 Ap pagados 28_01.TXT ... ✅ AP (428 registros)
   📄 Comparendos pagados 28_01.TXT ... ✅ COMPARENDOS (1156 registros)
   📄 Comparendos pagados 28_01_V2.TXT ... ✅ COMPARENDOS (1156 registros)

📂 Procesando carpeta: ENERO\30_01_2025
   📄 Ap pagados 29_01.TXT ... ✅ AP (475 registros)
   📄 Comparendos pagados 29_01.TXT ... ✅ COMPARENDOS (1993 registros)

📂 Procesando carpeta: ENERO\31_01_2025
   📄 Ap pagados 30_01.TXT ... ✅ AP (671 registros)
   📄 Comparendo pagados 30_01.TXT ... ⏭️  Ignorado (no es AP ni Comparendos)

📂 Procesando carpeta: FEBRERO\01_02_2025
   📄 Ap pagados 31_01.TXT ... ✅ AP (625 registros)
   📄 Comparendos pagados 31_01.TXT ... ✅ COMPARENDOS (1528 registros)
   📄 Comparendos pagados del 01_01 al 31_01.TXT ... ✅ COMPARENDOS (34318 registros)

📂 Procesando carpeta: FEBRERO\03_02_2025
   📄 Ap pagados 01_02 al 02_02.TXT ... ✅ AP (402 registros)
   📄 Comparendos pagados 01_02 al 02_02.TXT ... ✅ COMPARENDOS (828 registros)

📂 Procesando carpeta: FEBRERO\04_02_2025
   📄 Ap pagados 03_02.TXT ... ✅ AP (886 registros)
   📄 Comparendos pagados 03_02.TXT ... ✅ COMPARENDOS (1687 registros)

📂 Procesando carpeta: FEBRERO\05_02_2025
   📄 Ap pagados 04_02.TXT ... ✅ AP (588 registros)
   📄 Comparendos pagados 04_02.TXT ... ✅ COMPARENDOS (1633 registros)

📂 Procesando carpeta: FEBRERO\06_02_2025
   📄 Ap pagados 05_02.TXT ... ✅ AP (707 registros)
   📄 Comparendos pagados 05_02.TXT ... ✅ COMPARENDOS (1682 registros)

📂 Procesando carpeta: FEBRERO\07_02_2025
   📄 Ap pagados 06_02.TXT ... ✅ AP (576 registros)
   📄 Comparendos pagados 06_02.TXT ... ✅ COMPARENDOS (1527 registros)

📂 Procesando carpeta: FEBRERO\10_02_2025
   📄 Ap pagados 07_02 al 09_02.TXT ... ✅ AP (765 registros)
   📄 Comparendos pagados 07_02 al 09_02.TXT ... ✅ COMPARENDOS (2298 registros)

📂 Procesando carpeta: FEBRERO\11_02_2025
   📄 Ap pagados 10_02.TXT ... ✅ AP (783 registros)
   📄 Comparendos pagados 10_02.TXT ... ✅ COMPARENDOS (1510 registros)

📂 Procesando carpeta: FEBRERO\12_02_2025
   📄 Ap pagados 11_02.TXT ... ✅ AP (614 registros)
   📄 Comparedos pagados 11_02.TXT ... ⏭️  Ignorado (no es AP ni Comparendos)

📂 Procesando carpeta: FEBRERO\13_02_2025
   📄 Ap pagados 01_02 al 12_02.TXT ... ✅ AP (5674 registros)
   📄 Ap pagados 12_02.TXT ... ✅ AP (582 registros)
   📄 Comparendos pagados 01_02 al 12_02.TXT ... ✅ COMPARENDOS (13760 registros)
   📄 Comparendos pagados 12_02.TXT ... ✅ COMPARENDOS (1250 registros)

📂 Procesando carpeta: FEBRERO\14_02_2025
   📄 Ap pagados 13_02.TXT ... ✅ AP (692 registros)
   📄 Comparendos pagados 13_02.TXT ... ✅ COMPARENDOS (1265 registros)

📂 Procesando carpeta: FEBRERO\15_02_2025
   📄 Ap pagados 14_02.TXT ... ✅ AP (714 registros)
   📄 Comparendos pagados 14_02.TXT ... ✅ COMPARENDOS (1257 registros)

📂 Procesando carpeta: FEBRERO\17_02_2025
   📄 Ap pagados 15_02 al 16_02.TXT ... ✅ AP (487 registros)
   📄 Comparendos pagados 15_02 al 16_02.TXT ... ✅ COMPARENDOS (580 registros)

📂 Procesando carpeta: FEBRERO\18_02_2025
   📄 Ap pagados 17_02.TXT ... ✅ AP (1027 registros)
   📄 Comparendos pagados 17_02.TXT ... ✅ COMPARENDOS (1307 registros)

📂 Procesando carpeta: FEBRERO\19_02_2025
   📄 Ap pagados 18_02.TXT ... ✅ AP (649 registros)
   📄 Comparendos pagados 18_02.TXT ... ✅ COMPARENDOS (1122 registros)

📂 Procesando carpeta: FEBRERO\20_02_2025
   📄 Ap pagados 19_02.TXT ... ✅ AP (504 registros)
   📄 Comparendos pagados 19_02.TXT ... ✅ COMPARENDOS (1533 registros)

📂 Procesando carpeta: FEBRERO\21_02_2025
   📄 Ap pagados 20_02.TXT ... ✅ AP (519 registros)
   📄 Comparendos pagados 20_02.TXT ... ❌ Error leyendo Comparendos pagados 20_02.TXT: 'johab' codec can't decode byte 0xc9 in position 7695: illegal multibyte sequence
❌ Error

📂 Procesando carpeta: FEBRERO\22_02_2025
   📄 Ap pagados 20_02.TXT ... ✅ AP (519 registros)
   📄 Comparendos pagados 20_02.TXT ... ❌ Error leyendo Comparendos pagados 20_02.TXT: 'johab' codec can't decode byte 0xc9 in position 7695: illegal multibyte sequence
❌ Error

📂 Procesando carpeta: FEBRERO\24_02_2025
   📄 Ap pagados 21_02 al 23_02.TXT ... ✅ AP (761 registros)
   📄 Comparendos pagados 21_02 al 23_02.TXT ... ✅ COMPARENDOS (2019 registros)

📂 Procesando carpeta: FEBRERO\25_02_2025
   📄 Ap pagados 24_02.TXT ... ✅ AP (615 registros)
   📄 Comparendos pagados 24_02.TXT ... ✅ COMPARENDOS (1423 registros)

📂 Procesando carpeta: FEBRERO\26_02_2025
   📄 Ap pagados 25_02.TXT ... ✅ AP (448 registros)
   📄 Comparendos pagados 25_02.TXT ... ✅ COMPARENDOS (1343 registros)

📂 Procesando carpeta: FEBRERO\27_02_2025
   📄 Ap pagados 26_02.TXT ... ✅ AP (399 registros)
   📄 Comparendos pagados 26_02.TXT ... ✅ COMPARENDOS (1366 registros)

📂 Procesando carpeta: FEBRERO\28_02_2025
   📄 Ap pagados 27_02.TXT ... ✅ AP (601 registros)
   📄 Comparendos pagados 27_02.TXT ... ✅ COMPARENDOS (1410 registros)

📂 Procesando carpeta: JUNIO\03_06_2025
   📄 Ap pagados 01_05 al 31_05.TXT ... ✅ AP (17136 registros)
   📄 Ap pagados 01_06 al 02_06.TXT ... ✅ AP (315 registros)
   📄 Comparendos pagados 01_05 al 31_05.TXT ... ✅ COMPARENDOS (29782 registros)
   📄 Comparendos pagados 01_06 al 02_06.TXT ... ✅ COMPARENDOS (104 registros)

📂 Procesando carpeta: JUNIO\04_06_2025
   📄 Ap pagados 03_06.TXT ... ✅ AP (827 registros)
   📄 Comparendos pagados 03_06.TXT ... ✅ COMPARENDOS (1226 registros)

📂 Procesando carpeta: JUNIO\05_06_2025
   📄 Ap pagados 04_06.TXT ... ✅ AP (785 registros)
   📄 Comparendos pagados 04_06.TXT ... ✅ COMPARENDOS (1541 registros)

📂 Procesando carpeta: JUNIO\06_06_2025
   📄 Ap pagados 05_06.TXT ... ✅ AP (794 registros)
   📄 Comparendos pagados 05_06.TXT ... ✅ COMPARENDOS (1443 registros)

📂 Procesando carpeta: JUNIO\09_06_2025
   📄 Ap pagados 06_06 al 08_06.TXT ... ✅ AP (1105 registros)
   📄 Comparendos pagados 06_06 al 08_06.TXT ... ✅ COMPARENDOS (1897 registros)

📂 Procesando carpeta: JUNIO\10_06_2025
   📄 Ap pagados 09_06.TXT ... ✅ AP (850 registros)
   📄 Comparendos pagados 09_06.TXT ... ✅ COMPARENDOS (1912 registros)

📂 Procesando carpeta: JUNIO\11_06_2025
   📄 Ap pagados 10_06.TXT ... ✅ AP (646 registros)
   📄 Comparendos pagados 10_06.TXT ... ✅ COMPARENDOS (1332 registros)

📂 Procesando carpeta: JUNIO\12_06_2025
   📄 Ap pagados 11_06.TXT ... ✅ AP (543 registros)
   📄 Comparendos pagados 11_06.TXT ... ✅ COMPARENDOS (1270 registros)

📂 Procesando carpeta: JUNIO\13_06_2025
   📄 Ap pagados 12_06.TXT ... ✅ AP (536 registros)
   📄 Comparendos pagados 12_06.TXT ... ✅ COMPARENDOS (1204 registros)

📂 Procesando carpeta: JUNIO\16_06_2025
   📄 Ap pagados 01_06 al 15_06.TXT ... ✅ AP (7708 registros)
   📄 Comparendos pagados 01_06 al 15_06.TXT ... ✅ COMPARENDOS (13923 registros)

📂 Procesando carpeta: JUNIO\17_06_2025
   📄 Ap pagados 16_06.TXT ... ✅ AP (1140 registros)
   📄 Comparendos pagados 16_06.TXT ... ✅ COMPARENDOS (1399 registros)

📂 Procesando carpeta: JUNIO\18_06_2025
   📄 Ap pagados 17_06.TXT ... ✅ AP (733 registros)
   📄 Comparendos pagados 17_06.TXT ... ✅ COMPARENDOS (1499 registros)

📂 Procesando carpeta: JUNIO\19_06_2025
   📄 Ap pagados 18_06.TXT ... ✅ AP (553 registros)
   📄 Comparendos pagados 18_06.TXT ... ❌ Error leyendo Comparendos pagados 18_06.TXT: 'johab' codec can't decode byte 0xc9 in position 1662: illegal multibyte sequence
❌ Error

📂 Procesando carpeta: JUNIO\20_06_2025
   📄 Ap pagados 19_06.TXT ... ✅ AP (649 registros)
   📄 Comparendos pagados 19_06.TXT ... ✅ COMPARENDOS (1221 registros)

📂 Procesando carpeta: JUNIO\21_06_2025
   📄 Ap pagados 20_06.TXT ... ✅ AP (660 registros)
   📄 Comparendos pagados 20_06.TXT ... ✅ COMPARENDOS (1292 registros)

📂 Procesando carpeta: JUNIO\24_06_2025
   📄 Ap pagados 21_06 al 23_06.TXT ... ✅ AP (197 registros)
   📄 Comparendos pagados 21_06 al 23_06.TXT ... ✅ COMPARENDOS (532 registros)

📂 Procesando carpeta: MARZO\01_03_2025
   📄 Ap pagados 01_02 al 28_02.TXT ... ✅ AP (13625 registros)
   📄 Ap pagados 28_02.TXT ... ✅ AP (756 registros)
   📄 Comparendos pagados 01_02 al 28_02.TXT ... ✅ COMPARENDOS (31108 registros)
   📄 Comparendos pagados 28_02.TXT ... ✅ COMPARENDOS (1311 registros)

📂 Procesando carpeta: MARZO\03_03_2025
   📄 Ap pagados 01_03 al 02_03.TXT ... ✅ AP (573 registros)
   📄 Comparendos pagados 01_03 al 02_03.TXT ... ✅ COMPARENDOS (786 registros)

📂 Procesando carpeta: MARZO\04_03_2025
   📄 Ap pagados 03_03.TXT ... ✅ AP (1076 registros)
   📄 Comparendos pagados 03_03.TXT ... ✅ COMPARENDOS (1378 registros)

📂 Procesando carpeta: MARZO\05_03_2025
   📄 Ap pagados 04_03.TXT ... ✅ AP (673 registros)
   📄 Comparendos pagados 04_03.TXT ... ✅ COMPARENDOS (2301 registros)

📂 Procesando carpeta: MARZO\06_03_2025
   📄 Ap pagados 05_03.TXT ... ✅ AP (672 registros)
   📄 Comparendos pagados 05_03.TXT ... ✅ COMPARENDOS (2196 registros)

📂 Procesando carpeta: MARZO\07_03_2025
   📄 AP pagados 06_03_2024.TXT ... ✅ AP (717 registros)
   📄 Comparendos pagados 06_03_2024.TXT ... ✅ COMPARENDOS (1665 registros)

📂 Procesando carpeta: MARZO\08_03_2025
   📄 Ap pagados 07_03.TXT ... ✅ AP (589 registros)
   📄 Comparendos pagados 07_03.TXT ... ✅ COMPARENDOS (1517 registros)

📂 Procesando carpeta: MARZO\10_03_2025
   📄 Ap pagados 08_03 al 09_03.TXT ... ✅ AP (284 registros)
   📄 Comparendos pagados 08_03 al 09_03.TXT ... ✅ COMPARENDOS (571 registros)

📂 Procesando carpeta: MARZO\11_03_2025
   📄 Ap pagados 10_03.TXT ... ✅ AP (786 registros)
   📄 Comparendos pagados 10_03.TXT ... ✅ COMPARENDOS (1329 registros)

📂 Procesando carpeta: MARZO\12_03_2025
   📄 Ap pagados 11_03.TXT ... ✅ AP (578 registros)
   📄 Comparendos pagados 11_03.TXT ... ✅ COMPARENDOS (1463 registros)

📂 Procesando carpeta: MARZO\13_03_2025
   📄 Ap pagados 12_03.TXT ... ✅ AP (601 registros)
   📄 Comparendos pagados 12_03.TXT ... ✅ COMPARENDOS (1513 registros)

📂 Procesando carpeta: MARZO\14_03_2025
   📄 Ap pagados 13_03.TXT ... ✅ AP (531 registros)
   📄 Comparendos pagados 13_03.TXT ... ✅ COMPARENDOS (1561 registros)

📂 Procesando carpeta: MARZO\17_03_2025
   📄 Ap pagados 01_03 al 16_03.TXT ... ✅ AP (8046 registros)
   📄 Ap pagados 14_03 al 16_03.TXT ... ✅ AP (1254 registros)
   📄 Comparendos pagados 01_03 al 16_03.TXT ... ✅ COMPARENDOS (18649 registros)
   📄 Comparendos pagados 14_03 al 16_03.TXT ... ✅ COMPARENDOS (2374 registros)

📂 Procesando carpeta: MARZO\18_03_2025
   📄 Ap pagados 17_03.TXT ... ✅ AP (1173 registros)
   📄 Comparendos pagados 17_03.TXT ... ✅ COMPARENDOS (1924 registros)

📂 Procesando carpeta: MARZO\19_03_2025
   📄 Ap pagados 01_03 al 18_03.TXT ... ✅ AP (9806 registros)
   📄 Ap pagados 18_03.TXT ... ✅ AP (784 registros)
   📄 Comparendos pagados 01_03 al 18_03.TXT ... ✅ COMPARENDOS (22348 registros)
   📄 Comparendos pagados 18_03.TXT ... ✅ COMPARENDOS (1775 registros)

📂 Procesando carpeta: MARZO\20_03_2025
   📄 Ap pagados 19_03.TXT ... ✅ AP (608 registros)
   📄 Comparendos pagados 19_03.TXT ... ✅ COMPARENDOS (1200 registros)

📂 Procesando carpeta: MARZO\21_03_2025
   📄 Ap pagados 20_03.TXT ... ✅ AP (537 registros)
   📄 Comparendos pagados 20_03.TXT ... ✅ COMPARENDOS (1238 registros)

📂 Procesando carpeta: MARZO\22_03_2025
   📄 Ap pagados 21_03.TXT ... ✅ AP (596 registros)
   📄 Comparendos pagados 21_03.TXT ... ✅ COMPARENDOS (1304 registros)

📂 Procesando carpeta: MARZO\25_03_2025
   📄 Ap pagados 22_03 al 24_03.TXT ... ✅ AP (379 registros)
   📄 Comparendos pagados 22_03 al 24_03.TXT ... ✅ COMPARENDOS (547 registros)

📂 Procesando carpeta: MARZO\26_03_2025
   📄 Ap pagados 25_03.TXT ... ✅ AP (614 registros)
   📄 Comparendos pagados 25_03.TXT ... ❌ Error leyendo Comparendos pagados 25_03.TXT: 'johab' codec can't decode byte 0xc1 in position 4022: illegal multibyte sequence
❌ Error


In [1]:
import os
import pandas as pd
from datetime import datetime, timedelta
from pathlib import Path
import chardet
import json
import hashlib
import logging
from typing import Tuple, Dict, List, Optional

# Configurar logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('consolidador_pagos.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

class ControlArchivos:
    """Maneja el control de archivos procesados"""
    
    def __init__(self, archivo_control='control_archivos.json'):
        self.archivo_control = archivo_control
        self.control = self._cargar_control()
    
    def _cargar_control(self) -> Dict:
        """Carga el archivo de control o crea uno nuevo"""
        try:
            if os.path.exists(self.archivo_control):
                with open(self.archivo_control, 'r', encoding='utf-8') as f:
                    return json.load(f)
        except Exception as e:
            logger.warning(f"No se pudo cargar control de archivos: {e}")
        return {}
    
    def _guardar_control(self):
        """Guarda el archivo de control"""
        try:
            with open(self.archivo_control, 'w', encoding='utf-8') as f:
                json.dump(self.control, f, indent=2, default=str)
        except Exception as e:
            logger.error(f"Error guardando control de archivos: {e}")
    
    def calcular_hash_archivo(self, ruta_archivo: str) -> str:
        """Calcula hash MD5 del archivo"""
        try:
            hash_md5 = hashlib.md5()
            with open(ruta_archivo, "rb") as f:
                for chunk in iter(lambda: f.read(4096), b""):
                    hash_md5.update(chunk)
            return hash_md5.hexdigest()
        except Exception:
            return ""
    
    def debe_procesar_archivo(self, ruta_archivo: str, dias_ventana: int = 7) -> Tuple[bool, str]:
        """
        Determina si un archivo debe ser procesado
        
        Returns:
            Tuple[bool, str]: (debe_procesar, razon)
        """
        nombre_archivo = os.path.basename(ruta_archivo)
        
        # Verificar si existe el archivo
        if not os.path.exists(ruta_archivo):
            return False, "Archivo no existe"
        
        # Obtener metadatos actuales
        fecha_mod = datetime.fromtimestamp(os.path.getmtime(ruta_archivo))
        hash_actual = self.calcular_hash_archivo(ruta_archivo)
        
        # Si no está en control, procesar
        if nombre_archivo not in self.control:
            return True, "Archivo nuevo"
        
        registro = self.control[nombre_archivo]
        fecha_mod_anterior = datetime.fromisoformat(registro.get('fecha_modificacion', '1900-01-01'))
        hash_anterior = registro.get('hash_archivo', '')
        
        # Si cambió el hash, procesar
        if hash_actual != hash_anterior:
            return True, "Contenido modificado"
        
        # Si fue modificado en la ventana de días, procesar
        limite_ventana = datetime.now() - timedelta(days=dias_ventana)
        if fecha_mod > limite_ventana and fecha_mod > fecha_mod_anterior:
            return True, f"Modificado en últimos {dias_ventana} días"
        
        return False, "Ya procesado y sin cambios"
    
    def registrar_procesamiento(self, ruta_archivo: str, registros_procesados: int, 
                              registros_nuevos: int = 0, registros_actualizados: int = 0):
        """Registra el procesamiento exitoso de un archivo"""
        nombre_archivo = os.path.basename(ruta_archivo)
        
        self.control[nombre_archivo] = {
            'ruta_completa': ruta_archivo,
            'fecha_modificacion': datetime.fromtimestamp(os.path.getmtime(ruta_archivo)).isoformat(),
            'fecha_procesamiento': datetime.now().isoformat(),
            'hash_archivo': self.calcular_hash_archivo(ruta_archivo),
            'registros_procesados': registros_procesados,
            'registros_nuevos': registros_nuevos,
            'registros_actualizados': registros_actualizados
        }
        
        self._guardar_control()
        logger.info(f"Registrado procesamiento de {nombre_archivo}: {registros_procesados} registros")

class ValidadorDatos:
    """Valida y limpia los datos de pagos"""
    
    @staticmethod
    def validar_comparendos(df: pd.DataFrame) -> Tuple[pd.DataFrame, Dict]:
        """Valida datos de comparendos"""
        stats = {'registros_entrada': len(df), 'errores': []}
        
        if df.empty:
            return df, stats
        
        df_limpio = df.copy()
        
        # Validación 1: Campos obligatorios
        campos_obligatorios = ['nro_comparendo', 'id_usuario']
        for campo in campos_obligatorios:
            if campo in df_limpio.columns:
                antes = len(df_limpio)
                df_limpio = df_limpio.dropna(subset=[campo])
                eliminados = antes - len(df_limpio)
                if eliminados > 0:
                    stats['errores'].append(f"{campo} nulo: {eliminados} registros eliminados")
        
        # Validación 2: Filtrar cobros en $0 (si existe columna)
        columnas_valor = ['cobro_coactivo', 'valor_pago', 'valor', 'intereses']
        for col in columnas_valor:
            if col in df_limpio.columns:
                antes = len(df_limpio)
                df_limpio = df_limpio[pd.to_numeric(df_limpio[col], errors='coerce') != 0]
                eliminados = antes - len(df_limpio)
                if eliminados > 0:
                    stats['errores'].append(f"{col} = $0: {eliminados} registros filtrados")
        
        # Validación 3: Fechas válidas
        columnas_fecha = ['fecha_liquida_contra', 'fecha_pago', 'fecha_liquidacion']
        for col in columnas_fecha:
            if col in df_limpio.columns:
                try:
                    df_limpio[col] = pd.to_datetime(df_limpio[col], errors='coerce')
                    nulos_fecha = df_limpio[col].isnull().sum()
                    if nulos_fecha > 0:
                        stats['errores'].append(f"{col} inválida: {nulos_fecha} fechas corregidas a null")
                except Exception as e:
                    stats['errores'].append(f"Error procesando {col}: {e}")
        
        stats['registros_salida'] = len(df_limpio)
        stats['registros_eliminados'] = stats['registros_entrada'] - stats['registros_salida']
        
        return df_limpio, stats
    
    @staticmethod
    def validar_ap(df: pd.DataFrame) -> Tuple[pd.DataFrame, Dict]:
        """Valida datos de acuerdos de pago"""
        stats = {'registros_entrada': len(df), 'errores': []}
        
        if df.empty:
            return df, stats
        
        df_limpio = df.copy()
        
        # Validación 1: Campos obligatorios
        campos_obligatorios = ['nro_acuerdo', 'consecutivo_ap']
        for campo in campos_obligatorios:
            if campo in df_limpio.columns:
                antes = len(df_limpio)
                df_limpio = df_limpio.dropna(subset=[campo])
                eliminados = antes - len(df_limpio)
                if eliminados > 0:
                    stats['errores'].append(f"{campo} nulo: {eliminados} registros eliminados")
        
        # Validación 2: Filtrar valores en $0 (pero mantener para análisis)
        columnas_valor = ['valor_cuota', 'valor_pago', 'valor']
        df_limpio['tiene_valor_positivo'] = False
        
        for col in columnas_valor:
            if col in df_limpio.columns:
                df_limpio['tiene_valor_positivo'] |= (pd.to_numeric(df_limpio[col], errors='coerce') > 0)
        
        # Contar pero NO eliminar registros con valor 0 (pueden ser actualizaciones)
        registros_cero = (~df_limpio['tiene_valor_positivo']).sum()
        if registros_cero > 0:
            stats['errores'].append(f"Registros con valor $0: {registros_cero} (mantenidos para análisis)")
        
        # Validación 3: Fechas válidas
        columnas_fecha = ['fecha_pago', 'fecha_liquida', 'fecha_cuota']
        for col in columnas_fecha:
            if col in df_limpio.columns:
                try:
                    df_limpio[col] = pd.to_datetime(df_limpio[col], errors='coerce')
                except Exception as e:
                    stats['errores'].append(f"Error procesando {col}: {e}")
        
        stats['registros_salida'] = len(df_limpio)
        stats['registros_eliminados'] = stats['registros_entrada'] - stats['registros_salida']
        
        return df_limpio, stats

class ConsolidadorAvanzado:
    """Consolidador principal mejorado"""
    
    def __init__(self, ruta_base: str, modo_procesamiento: str = 'completo'):
        self.ruta_base = ruta_base
        self.modo_procesamiento = modo_procesamiento  # 'completo' o 'incremental'
        self.control_archivos = ControlArchivos()
        self.validador = ValidadorDatos()
        
        # Estadísticas de procesamiento
        self.stats = {
            'archivos_procesados': 0,
            'archivos_saltados': 0,
            'archivos_error': 0,
            'registros_ap_totales': 0,
            'registros_comparendos_totales': 0,
            'validaciones_realizadas': [],
            'tiempo_inicio': datetime.now()
        }
    
    def detectar_encoding(self, ruta_archivo: str) -> str:
        """Detecta la codificación de un archivo"""
        try:
            with open(ruta_archivo, 'rb') as f:
                muestra = f.read(10000)
                resultado = chardet.detect(muestra)
                return resultado['encoding'] if resultado['encoding'] else 'utf-8'
        except:
            return 'utf-8'
    
    def leer_archivo_txt(self, ruta_archivo: str) -> pd.DataFrame:
        """Lee un archivo TXT y devuelve un DataFrame mejorado"""
        try:
            encoding = self.detectar_encoding(ruta_archivo)
            separadores = ['\t', '|', ';', ',']
            
            for sep in separadores:
                try:
                    df = pd.read_csv(ruta_archivo, 
                                   sep=sep, 
                                   encoding=encoding,
                                   low_memory=False)
                    
                    if len(df.columns) > 1:
                        # Limpiar nombres de columnas
                        df.columns = df.columns.str.strip().str.lower()
                        
                        # Agregar metadatos
                        df['archivo_origen'] = os.path.basename(ruta_archivo)
                        df['ruta_archivo'] = ruta_archivo
                        df['fecha_procesamiento'] = datetime.now()
                        df['fecha_modificacion_archivo'] = datetime.fromtimestamp(os.path.getmtime(ruta_archivo))
                        
                        return df
                except Exception:
                    continue
            
            logger.warning(f"No se pudo determinar separador para {os.path.basename(ruta_archivo)}")
            return pd.DataFrame()
            
        except Exception as e:
            logger.error(f"Error leyendo {os.path.basename(ruta_archivo)}: {e}")
            return pd.DataFrame()
    
    def clasificar_archivo(self, nombre_archivo: str) -> str:
        """Clasifica el tipo de archivo"""
        nombre_lower = nombre_archivo.lower()
        
        if "ap pagados" in nombre_lower:
            return "ap"
        elif "comparendos pagados" in nombre_lower or "comparendo pagados" in nombre_lower:
            return "comparendos"
        else:
            return "desconocido"
    
    def procesar_archivo_individual(self, ruta_archivo: str, tipo_archivo: str) -> Optional[pd.DataFrame]:
        """Procesa un archivo individual con validaciones"""
        
        # Verificar si debe procesarse
        if self.modo_procesamiento == 'incremental':
            debe_procesar, razon = self.control_archivos.debe_procesar_archivo(ruta_archivo)
            if not debe_procesar:
                logger.info(f"⏭️  Saltando {os.path.basename(ruta_archivo)}: {razon}")
                self.stats['archivos_saltados'] += 1
                return None
        
        logger.info(f"📄 Procesando {os.path.basename(ruta_archivo)}...")
        
        # Leer archivo
        df = self.leer_archivo_txt(ruta_archivo)
        if df.empty:
            self.stats['archivos_error'] += 1
            return None
        
        # Validar según tipo
        if tipo_archivo == "ap":
            df_validado, stats_validacion = self.validador.validar_ap(df)
            self.stats['registros_ap_totales'] += len(df_validado)
        elif tipo_archivo == "comparendos":
            df_validado, stats_validacion = self.validador.validar_comparendos(df)
            self.stats['registros_comparendos_totales'] += len(df_validado)
        else:
            df_validado = df
            stats_validacion = {'errores': []}
        
        # Registrar validaciones
        if stats_validacion['errores']:
            self.stats['validaciones_realizadas'].extend([
                f"{os.path.basename(ruta_archivo)}: {error}" 
                for error in stats_validacion['errores']
            ])
        
        # Registrar procesamiento exitoso
        self.control_archivos.registrar_procesamiento(
            ruta_archivo, 
            len(df_validado),
            len(df_validado),  # Nuevos (por ahora todos)
            0  # Actualizados (por ahora ninguno)
        )
        
        self.stats['archivos_procesados'] += 1
        logger.info(f"✅ {os.path.basename(ruta_archivo)}: {len(df_validado)} registros válidos")
        
        return df_validado
    
    def consolidar_datos(self) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """Método principal de consolidación"""
        logger.info(f"🚀 Iniciando consolidación en modo: {self.modo_procesamiento}")
        logger.info(f"📂 Ruta base: {self.ruta_base}")
        
        dfs_ap = []
        dfs_comparendos = []
        
        # Recorrer archivos
        for root, dirs, files in os.walk(self.ruta_base):
            archivos_txt = [f for f in files if f.lower().endswith('.txt')]
            
            if archivos_txt:
                carpeta_actual = os.path.relpath(root, self.ruta_base)
                logger.info(f"\n📂 Carpeta: {carpeta_actual}")
                
                for archivo in archivos_txt:
                    ruta_completa = os.path.join(root, archivo)
                    tipo_archivo = self.clasificar_archivo(archivo)
                    
                    if tipo_archivo == "desconocido":
                        continue
                    
                    df_procesado = self.procesar_archivo_individual(ruta_completa, tipo_archivo)
                    
                    if df_procesado is not None:
                        # Agregar información de carpeta
                        df_procesado['carpeta_origen'] = carpeta_actual
                        
                        if tipo_archivo == "ap":
                            dfs_ap.append(df_procesado)
                        elif tipo_archivo == "comparendos":
                            dfs_comparendos.append(df_procesado)
        
        # Consolidar DataFrames
        df_ap_final = pd.concat(dfs_ap, ignore_index=True) if dfs_ap else pd.DataFrame()
        df_comparendos_final = pd.concat(dfs_comparendos, ignore_index=True) if dfs_comparendos else pd.DataFrame()
        
        return df_ap_final, df_comparendos_final
    
    def generar_reporte_procesamiento(self, df_ap: pd.DataFrame, df_comparendos: pd.DataFrame):
        """Genera reporte completo del procesamiento"""
        tiempo_total = datetime.now() - self.stats['tiempo_inicio']
        
        print("\n" + "="*60)
        print("📊 REPORTE DE CONSOLIDACIÓN")
        print("="*60)
        
        print(f"\n⏱️  TIEMPO DE PROCESAMIENTO: {tiempo_total}")
        print(f"🗂️  MODO: {self.modo_procesamiento.upper()}")
        
        print(f"\n📁 ARCHIVOS:")
        print(f"   ✅ Procesados: {self.stats['archivos_procesados']}")
        print(f"   ⏭️  Saltados: {self.stats['archivos_saltados']}")
        print(f"   ❌ Con error: {self.stats['archivos_error']}")
        
        print(f"\n📋 REGISTROS CONSOLIDADOS:")
        print(f"   🏦 AP Pagados: {len(df_ap):,} registros")
        print(f"   🚔 Comparendos: {len(df_comparendos):,} registros")
        print(f"   📊 Total: {(len(df_ap) + len(df_comparendos)):,} registros")
        
        if self.stats['validaciones_realizadas']:
            print(f"\n⚠️  VALIDACIONES Y LIMPIEZAS:")
            for validacion in self.stats['validaciones_realizadas'][:10]:  # Mostrar solo las primeras 10
                print(f"   • {validacion}")
            if len(self.stats['validaciones_realizadas']) > 10:
                print(f"   ... y {len(self.stats['validaciones_realizadas']) - 10} más")
        
        # Análisis por fechas de archivos
        if not df_ap.empty:
            print(f"\n📅 AP - DISTRIBUCIÓN POR FECHA DE ARCHIVO:")
            fechas_ap = df_ap['fecha_modificacion_archivo'].dt.date.value_counts().head(5)
            for fecha, cantidad in fechas_ap.items():
                print(f"   • {fecha}: {cantidad:,} registros")
        
        if not df_comparendos.empty:
            print(f"\n📅 COMPARENDOS - DISTRIBUCIÓN POR FECHA DE ARCHIVO:")
            fechas_comp = df_comparendos['fecha_modificacion_archivo'].dt.date.value_counts().head(5)
            for fecha, cantidad in fechas_comp.items():
                print(f"   • {fecha}: {cantidad:,} registros")

def main(ruta_base: str, modo: str = 'completo'):
    """Función principal mejorada"""
    
    # Crear consolidador
    consolidador = ConsolidadorAvanzado(ruta_base, modo_procesamiento=modo)
    
    # Consolidar datos
    df_ap, df_comparendos = consolidador.consolidar_datos()
    
    # Generar reporte
    consolidador.generar_reporte_procesamiento(df_ap, df_comparendos)
    
    # Guardar archivos consolidados
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    if not df_ap.empty:
        archivo_ap = f'ap_pagados_consolidado_{timestamp}.csv'
        df_ap.to_csv(archivo_ap, index=False, encoding='utf-8')
        logger.info(f"💾 AP guardado: {archivo_ap}")
    
    if not df_comparendos.empty:
        archivo_comp = f'comparendos_consolidado_{timestamp}.csv'
        df_comparendos.to_csv(archivo_comp, index=False, encoding='utf-8')
        logger.info(f"💾 Comparendos guardado: {archivo_comp}")
    
    return df_ap, df_comparendos

# Ejemplo de uso
if __name__ == "__main__":
    # PROCESAMIENTO COMPLETO (primera vez)
    df_ap, df_comp = main(r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025", modo='completo')
    
    # PROCESAMIENTO INCREMENTAL (diario)
    # df_ap, df_comp = main(r"C:\ruta\a\tus\archivos", modo='incremental')
    
    pass

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1154, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in position 33: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\app\app_simm\venv\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\app\app_simm\venv\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 683, in run_forever
    self._run_once()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2042, in _run_once
    handle._run()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3098, in run_cell
    result = self._run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3153, in _run_cell
    result = runner(coro)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3365, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3610, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3670, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 445, in <module>
    df_ap, df_comp = main(r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025", modo='completo')
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 422, in main
    df_ap, df_comparendos = consolidador.consolidar_datos()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 336, in consolidar_datos
    logger.info(f"🚀 Iniciando consolidación en modo: {self.modo_procesamiento}")
Message: '🚀 Iniciando consolidación en modo: completo'
Arguments: ()
2025-07-01 09:35:28,807 - INFO - 🚀 Iniciando consolidación en modo: completo
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1154, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4c2' in position 33: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\app\app_simm\venv\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\app\app_simm\venv\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 683, in run_forever
    self._run_once()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2042, in _run_once
    handle._run()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3098, in run_cell
    result = self._run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3153, in _run_cell
    result = runner(coro)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3365, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3610, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3670, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 445, in <module>
    df_ap, df_comp = main(r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025", modo='completo')
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 422, in main
    df_ap, df_comparendos = consolidador.consolidar_datos()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 337, in consolidar_datos
    logger.info(f"📂 Ruta base: {self.ruta_base}")
Message: '📂 Ruta base: C:\\Users\\1513873.ANDESBPO\\ANDES BPO S.A.S\\Johan Felipe JG. Gómez Arango - SIMM\\BASES\\Pagos\\2025'
Arguments: ()
2025-07-01 09:35:28,933 - INFO - 📂 Ruta base: C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1154, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4c2' in position 35: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\app\app_simm\venv\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\app\app_simm\venv\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 683, in run_forever
    self._run_once()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2042, in _run_once
    handle._run()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3098, in run_cell
    result = self._run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3153, in _run_cell
    result = runner(coro)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3365, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3610, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3670, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 445, in <module>
    df_ap, df_comp = main(r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025", modo='completo')
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 422, in main
    df_ap, df_comparendos = consolidador.consolidar_datos()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 348, in consolidar_datos
    logger.info(f"\n📂 Carpeta: {carpeta_actual}")
Message: '\n📂 Carpeta: ABRIL\\01_04_2025'
Arguments: ()
2025-07-01 09:35:28,952 - INFO -
📂 Carpeta: ABRIL\01_04_2025
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1154, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4c4' in position 33: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\app\app_simm\venv\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\app\app_simm\venv\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 683, in run_forever
    self._run_once()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2042, in _run_once
    handle._run()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3098, in run_cell
    result = self._run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3153, in _run_cell
    result = runner(coro)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3365, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3610, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3670, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 445, in <module>
    df_ap, df_comp = main(r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025", modo='completo')
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 422, in main
    df_ap, df_comparendos = consolidador.consolidar_datos()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 357, in consolidar_datos
    df_procesado = self.procesar_archivo_individual(ruta_completa, tipo_archivo)
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 295, in procesar_archivo_individual
    logger.info(f"📄 Procesando {os.path.basename(ruta_archivo)}...")
Message: '📄 Procesando Ap pagados 31_03.TXT...'
Arguments: ()
2025-07-01 09:35:28,956 - INFO - 📄 Procesando Ap pagados 31_03.TXT...
C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py:200: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_limpio[col] = pd.to_datetime(df_limpio[col], errors='coerce')
2025-07-01 09:35:29,080 - INFO - Registrado procesamiento de Ap pagados 31_03.TXT: 989 registros
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1154, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\app\app_simm\venv\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\app\app_simm\venv\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 683, in run_forever
    self._run_once()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2042, in _run_once
    handle._run()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request

============================================================
📊 REPORTE DE CONSOLIDACIÓN
============================================================

⏱️  TIEMPO DE PROCESAMIENTO: 0:02:17.525495
🗂️  MODO: COMPLETO

📁 ARCHIVOS:
   ✅ Procesados: 288
   ⏭️  Saltados: 0
   ❌ Con error: 5

📋 REGISTROS CONSOLIDADOS:
   🏦 AP Pagados: 262,852 registros
   🚔 Comparendos: 139,689 registros
   📊 Total: 402,541 registros

⚠️  VALIDACIONES Y LIMPIEZAS:
   • Comparendos pagados 01_03 al 31_03.TXT: nro_comparendo nulo: 373 registros eliminados
   • Comparendos pagados 01_03 al 31_03.TXT: intereses = $0: 26702 registros filtrados
   • Comparendos pagados 31_03.TXT: nro_comparendo nulo: 21 registros eliminados
   • Comparendos pagados 31_03.TXT: intereses = $0: 1085 registros filtrados
   • Comparendos pagados 01_04.TXT: nro_comparendo nulo: 19 registros eliminados
   • Comparendos pagados 01_04.TXT: intereses = $0: 1136 registros filtrados
   • Comparendos pagados 02_03.TXT: nro_comparendo nulo: 14 registros eliminados
   • Comparendos pagados 02_03.TXT: intereses = $0: 1138 registros filtrados
   • Comparendos pagados 01_03 al 31_03.TXT: nro_comparendo nulo: 373 registros eliminados
   • Comparendos pagados 01_03 al 31_03.TXT: intereses = $0: 26702 registros filtrados
   ... y 276 más

📅 AP - DISTRIBUCIÓN POR FECHA DE ARCHIVO:
   • 2025-06-06: 19,857 registros
   • 2025-04-04: 16,402 registros
   • 2025-03-31: 15,879 registros
   • 2025-05-02: 15,096 registros
   • 2025-03-01: 14,381 registros

📅 COMPARENDOS - DISTRIBUCIÓN POR FECHA DE ARCHIVO:
   • 2025-06-06: 8,592 registros
   • 2025-04-01: 7,933 registros
   • 2025-04-04: 7,839 registros
   • 2025-05-02: 7,781 registros
   • 2025-03-31: 7,528 registros

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1154, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4be' in position 33: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\app\app_simm\venv\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\app\app_simm\venv\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 683, in run_forever
    self._run_once()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2042, in _run_once
    handle._run()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3098, in run_cell
    result = self._run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3153, in _run_cell
    result = runner(coro)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3365, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3610, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3670, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 445, in <module>
    df_ap, df_comp = main(r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025", modo='completo')
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 433, in main
    logger.info(f"💾 AP guardado: {archivo_ap}")
Message: '💾 AP guardado: ap_pagados_consolidado_20250701_093746.csv'
Arguments: ()
2025-07-01 09:37:51,819 - INFO - 💾 AP guardado: ap_pagados_consolidado_20250701_093746.csv
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1154, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4be' in position 33: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\app\app_simm\venv\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "c:\app\app_simm\venv\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 683, in run_forever
    self._run_once()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 2042, in _run_once
    handle._run()
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Programs\Python\Python313\Lib\asyncio\events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3098, in run_cell
    result = self._run_cell(
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3153, in _run_cell
    result = runner(coro)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3365, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3610, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\app\app_simm\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3670, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 445, in <module>
    df_ap, df_comp = main(r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025", modo='completo')
  File "C:\Users\1513873.ANDESBPO\AppData\Local\Temp\ipykernel_12444\925895377.py", line 438, in main
    logger.info(f"💾 Comparendos guardado: {archivo_comp}")
Message: '💾 Comparendos guardado: comparendos_consolidado_20250701_093746.csv'
Arguments: ()
2025-07-01 09:37:54,575 - INFO - 💾 Comparendos guardado: comparendos_consolidado_20250701_093746.csv

In [ ]:
import pandas as pd
import csv

df = pd.read_csv(
    r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025\MAYO\13_05_2025\Comparendos pagados 12_05.TXT",
    encoding='latin-1',  # <--- Asegúrate de usar la codificación correcta
    quoting=csv.QUOTE_NONE,  # <--- Desactiva el análisis de comillas
    sep=None,                # <--- Intenta inferir el delimitador automáticamente
    engine='python',         # <--- Requerido con quoting=QUOTE_NONE
    on_bad_lines='skip'      # <--- Ignora líneas dañadas
)

,nro_comparendo,nro_recibo,fecha_liquida_contrav,compute_0004,id_usuario,nombres,apellidos,nro_resolucion,cobro_coactivo,intereses
0,NaN,9002089999,12/05/2025 05:06:23,745308.0,1144206818,ANDRES FELIPE,VELASQUEZ FRANCO,386960,S,467056.0
1,D05001000000048073647,9002090001,12/05/2025 05:46:20,226520.0,98462297,HORENCIO,MONSALVE UPEGUI,NaN,NaN,0.0
2,D05001000000048044284,9002090005,12/05/2025 06:13:45,226520.0,43912877,KELY YOBANA,GONZALEZ MONCADA,NaN,NaN,0.0
3,D05001000000048081901,9002090005,12/05/2025 06:13:46,226520.0,43912877,KELY YOBANA,GONZALEZ MONCADA,NaN,NaN,0.0
4,D05001000000048044912,9002090008,12/05/2025 06:20:34,604054.0,1128270736,SONIA ANDREA,GONZALEZ QUICENO,NaN,NaN,0.0
5,D05001000000044533710,9002090010,12/05/2025 06:24:27,572628.0,1066750787,YERALDIN PAOLA,DURANGO ALARCON,NaN,NaN,0.0
6,D05001000000048124481,9002090011,12/05/2025 06:45:02,226520.0,79551406,FERNANDO ALBERTO,BEDOYA,NaN,NaN,0.0
7,D05001000000048119746,9002090016,12/05/2025 07:05:03,452911.0,1020447145,YONATAN STIWENS,MUÑOZ CARDONA,NaN,NaN,0.0
8,D05001000000048091166,9002090017,12/05/2025 07:06:32,604054.0,43202207,MARIA CLARA,SALDARRIAGA URIBE,NaN,NaN,0.0
9,D05001000000048101892,9002090024,12/05/2025 07:20:18,226520.0,1045696503,JOSE GABRIEL,SANCHEZ RAMIREZ,NaN,NaN,0.0

In [28]:
with open(
    r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025\MAYO\13_05_2025\Comparendos pagados 12_05.TXT", 
    'r', 
    encoding='latin1'
) as f:
    total_lineas = sum(1 for _ in f)

print("Líneas en el archivo original:", total_lineas)

Líneas en el archivo original: 1360

In [24]:
print("Filas leídas en el DataFrame:", len(df))
print("Líneas omitidas:", total_lineas - len(df))

Filas leídas en el DataFrame: 1359
Líneas omitidas: 1

In [30]:
import os
import pandas as pd
import csv

# Ruta principal donde buscar
ruta_raiz = r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025"

# Listas para acumular datos
dataframes = []
reporte_archivos = []

# Recorrer todas las carpetas y subcarpetas
for carpeta_actual, subcarpetas, archivos in os.walk(ruta_raiz):
    for archivo in archivos:
        if archivo.lower().endswith(".txt"):
            ruta_archivo = os.path.join(carpeta_actual, archivo)
            try:
                # Contar líneas totales del archivo original
                with open(ruta_archivo, 'r', encoding='latin1', errors='ignore') as f:
                    total_lineas = sum(1 for _ in f)

                # Leer con pandas
                df = pd.read_csv(
                    ruta_archivo,
                    encoding='latin1',
                    quoting=csv.QUOTE_NONE,
                    sep=None,
                    engine='python',
                    on_bad_lines='skip'
                )

                filas_leidas = len(df)
                filas_omitidas = total_lineas - filas_leidas

                dataframes.append(df)
                reporte_archivos.append({
                    'archivo': ruta_archivo,
                    'lineas_totales': total_lineas,
                    'filas_leidas': filas_leidas,
                    'filas_omitidas': filas_omitidas
                })

                print(f"✔️ {archivo}: {filas_leidas} filas leídas / {filas_omitidas} omitidas")

            except Exception as e:
                print(f"❌ Error en {ruta_archivo}: {e}")

# Unir todo
df_consolidado = pd.concat(dataframes, ignore_index=True)

# Crear reporte
df_reporte = pd.DataFrame(reporte_archivos)

print(f"\n📊 Archivos leídos: {len(df_reporte)}")
print(f"📂 Filas totales consolidadas: {len(df_consolidado)}")

# (Opcional) Exportar resumen
# df_reporte.to_excel("reporte_archivos_leidos.xlsx", index=False)

✔️ Ap pagados 31_03.TXT: 989 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 31_03.TXT: 34580 filas leídas / 1 omitidas
✔️ Comparendos pagados 31_03.TXT: 1534 filas leídas / 1 omitidas
✔️ Ap pagados 01_04.TXT: 731 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_04.TXT: 1539 filas leídas / 1 omitidas
✔️ Ap pagados 02_03.TXT: 563 filas leídas / 1 omitidas
✔️ Comparendos pagados 02_03.TXT: 1559 filas leídas / 1 omitidas
✔️ Ap pagados 01_03 al 31_03.TXT: 15646 filas leídas / 1 omitidas
✔️ Ap pagados 03_04.TXT: 756 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 31_03.TXT: 34580 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_04.TXT: 1419 filas leídas / 1 omitidas
✔️ Ap pagados 04_04.TXT: 761 filas leídas / 1 omitidas
✔️ Comparendos pagados 04_04.TXT: 1497 filas leídas / 1 omitidas
✔️ Ap pagados 05_04 al 06_04.TXT: 391 filas leídas / 1 omitidas
✔️ Comparendos pagados 05_04 al 06_04.TXT: 622 filas leídas / 2 omitidas
✔️ Ap pagados 07_04.TXT: 846 filas leídas / 1 omitidas
✔️ Comparendos pagados 07_04.TXT: 1400 filas leídas / 1 omitidas
✔️ Ap pagados 08_04.TXT: 659 filas leídas / 1 omitidas
✔️ Comparendos pagados 08_04.TXT: 1584 filas leídas / 1 omitidas
✔️ Ap pagados 09_04.TXT: 606 filas leídas / 1 omitidas
✔️ Comparendos pagados 09_04.TXT: 1494 filas leídas / 1 omitidas
✔️ Ap pagados 10_04.TXT: 529 filas leídas / 1 omitidas
✔️ Comparendos pagados 10_04.TXT: 1376 filas leídas / 1 omitidas
✔️ Ap pagados 11_04.TXT: 446 filas leídas / 1 omitidas
✔️ Comparendos pagados 11_04.TXT: 1295 filas leídas / 1 omitidas
✔️ Ap pagados 01_04 al 13_04.TXT: 6665 filas leídas / 1 omitidas
✔️ Ap pagados 12_04 al 13_04.TXT: 377 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_04 al 13_04.TXT: 14487 filas leídas / 2 omitidas
✔️ Comparendos pagados 12_04 al 13_04.TXT: 702 filas leídas / 1 omitidas
✔️ Ap pagados 14_04.TXT: 641 filas leídas / 1 omitidas
✔️ Comparendos pagados 14_04.TXT: 1435 filas leídas / 1 omitidas
✔️ Ap pagados 15_04.TXT: 703 filas leídas / 1 omitidas
✔️ Comparendos pagados 15_04.TXT: 1265 filas leídas / 1 omitidas
✔️ Ap pagados 01_04 al 20_04.TXT: 9142 filas leídas / 1 omitidas
✔️ Ap pagados 16_04 al 20_04.TXT: 1227 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_04 al 20_04.TXT: 18684 filas leídas / 2 omitidas
✔️ Comparendos pagados 16_04 al 20_04.TXT: 1497 filas leídas / 1 omitidas
✔️ Ap pagados 21_04.TXT: 1031 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_04.TXT: 1205 filas leídas / 1 omitidas
✔️ Ap pagados 22_04.TXT: 682 filas leídas / 1 omitidas
✔️ Comparendos pagados 22_04.TXT: 1440 filas leídas / 1 omitidas
✔️ Ap pagados 23_04.TXT: 635 filas leídas / 1 omitidas
✔️ Comparendos pagados 23_04.TXT: 1560 filas leídas / 1 omitidas
✔️ Ap pagados 01_04 al 24_04.TXT: 11995 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_04 al 24_04.TXT: 24210 filas leídas / 2 omitidas
✔️ Ap pagados 25_04 al 27_04.TXT: 910 filas leídas / 1 omitidas
✔️ Comparendos pagados 25_04 al 27_04.TXT: 1625 filas leídas / 1 omitidas
✔️ Ap pagados 28_04.TXT: 718 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_04.TXT: 1050 filas leídas / 1 omitidas
✔️ Ap pagados 29_04.TXT: 608 filas leídas / 1 omitidas
✔️ Comparendos pagados 29_04.TXT: 1115 filas leídas / 1 omitidas
✔️ Ap pagados 01_12 al 31_12.TXT: 11471 filas leídas / 1 omitidas
✔️ Ap pagados 31_12 al 01_01.TXT: 172 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_12 al 31_12.TXT: 29255 filas leídas / 2 omitidas
✔️ Comparendos pagados 31_12 al 01_01.TXT: 62 filas leídas / 1 omitidas
✔️ Ap pagados 02_01.TXT: 1117 filas leídas / 1 omitidas
✔️ Comparendos pagados 02_01.TXT: 2157 filas leídas / 1 omitidas
✔️ Ap pagados 03_01.TXT: 658 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_01.TXT: 930 filas leídas / 1 omitidas
✔️ Ap pagados 04_01 al 06_01.TXT: 551 filas leídas / 1 omitidas
✔️ Comparendos pagados 04_01 al 06_01.TXT: 548 filas leídas / 1 omitidas
✔️ Ap pagados 07_01.TXT: 1015 filas leídas / 1 omitidas
✔️ Comparendos pagados 07_01.TXT: 1321 filas leídas / 1 omitidas
✔️ Ap pagados 08_01.TXT: 660 filas leídas / 1 omitidas
✔️ Comparendos pagados 08_01.TXT: 1254 filas leídas / 1 omitidas
✔️ Ap pagados 09_01.TXT: 685 filas leídas / 1 omitidas
✔️ Comparendos pagados 09_01.TXT: 1265 filas leídas / 1 omitidas
✔️ Ap pagados 10_ al 12_01.TXT: 865 filas leídas / 1 omitidas
✔️ Comparendos pagados 10_ al 12_01.TXT: 1760 filas leídas / 1 omitidas
✔️ Ap pagados 13_01.TXT: 732 filas leídas / 1 omitidas
✔️ Comparendos pagados 13_01.TXT: 1498 filas leídas / 1 omitidas
✔️ Ap pagados 14_01.TXT: 641 filas leídas / 1 omitidas
✔️ Comparendos pagados 14_01.TXT: 1557 filas leídas / 1 omitidas
✔️ Ap pagados 15_01.TXT: 710 filas leídas / 1 omitidas
✔️ Comparendos pagados 15_01.TXT: 1562 filas leídas / 1 omitidas
✔️ Ap pagados 16_01.TXT: 760 filas leídas / 1 omitidas
✔️ Comparendos pagados 16_01.TXT: 1680 filas leídas / 1 omitidas
✔️ Ap pagados 17_01.TXT: 595 filas leídas / 1 omitidas
✔️ Comparendos pagados 17_01.TXT: 1978 filas leídas / 1 omitidas
✔️ AP pagados 01_01  al 19_01.TXT: 8888 filas leídas / 1 omitidas
✔️ Ap pagados 18_01 al 19_01.TXT: 229 filas leídas / 1 omitidas
✔️ AP PAGADOS DEL 18_01 AL 19_01.TXT: 229 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_01 al 19_01.TXT: 18350 filas leídas / 1 omitidas
✔️ Comparendos pagados 18_01 al 19_01.TXT: 779 filas leídas / 1 omitidas
✔️ COMPARENDOS PAGADOS DEL 18_01 AL 19_01.TXT: 779 filas leídas / 1 omitidas
✔️ AP PAGADOS 20_01.TXT: 784 filas leídas / 1 omitidas
✔️ COMPARENDOS PAGADOS 20_01.TXT: 1622 filas leídas / 1 omitidas
✔️ A p pagados 21_01.TXT: 527 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_01.TXT: 1335 filas leídas / 1 omitidas
✔️ Ap pagados  22_01.TXT: 489 filas leídas / 1 omitidas
✔️ Comparendos pagados  22_01.TXT: 1428 filas leídas / 1 omitidas
✔️ Ap pagados 23_01.TXT: 480 filas leídas / 1 omitidas
✔️ Comparendos pagados 23_01.TXT: 1492 filas leídas / 1 omitidas
✔️ Ap pagados 01_01 al 26_01.TXT: 11830 filas leídas / 1 omitidas
✔️ Ap pagados 24_01 al 26_01.TXT: 662 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_01 al 26_01.TXT: 26299 filas leídas / 1 omitidas
✔️ Comparendos pagados 24_01 al 26_01.TXT: 2068 filas leídas / 1 omitidas
✔️ Ap pagados 27_01.TXT: 716 filas leídas / 1 omitidas
✔️ Comparendos pagados 27_01.TXT: 1664 filas leídas / 1 omitidas
✔️ Ap pagados 28_01.TXT: 428 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_01.TXT: 1156 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_01_V2.TXT: 1156 filas leídas / 1 omitidas
✔️ Ap pagados 29_01.TXT: 475 filas leídas / 1 omitidas
✔️ Comparendos pagados 29_01.TXT: 1993 filas leídas / 1 omitidas
✔️ Ap pagados 30_01.TXT: 671 filas leídas / 1 omitidas
✔️ Comparendo pagados 30_01.TXT: 1679 filas leídas / 1 omitidas
✔️ Ap pagados 31_01.TXT: 625 filas leídas / 1 omitidas
✔️ Comparendos pagados 31_01.TXT: 1528 filas leídas / 1 omitidas
✔️ Comparendos pagados del 01_01 al 31_01.TXT: 34318 filas leídas / 1 omitidas
✔️ Ap pagados 01_02 al 02_02.TXT: 402 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_02 al 02_02.TXT: 828 filas leídas / 1 omitidas
✔️ Ap pagados 03_02.TXT: 886 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_02.TXT: 1687 filas leídas / 1 omitidas
✔️ Ap pagados 04_02.TXT: 588 filas leídas / 1 omitidas
✔️ Comparendos pagados 04_02.TXT: 1633 filas leídas / 1 omitidas
✔️ Ap pagados 05_02.TXT: 707 filas leídas / 1 omitidas
✔️ Comparendos pagados 05_02.TXT: 1682 filas leídas / 1 omitidas
✔️ Ap pagados 06_02.TXT: 576 filas leídas / 1 omitidas
✔️ Comparendos pagados 06_02.TXT: 1527 filas leídas / 1 omitidas
✔️ Ap pagados 07_02 al 09_02.TXT: 765 filas leídas / 1 omitidas
✔️ Comparendos pagados 07_02 al 09_02.TXT: 2298 filas leídas / 1 omitidas
✔️ Ap pagados 10_02.TXT: 783 filas leídas / 1 omitidas
✔️ Comparendos pagados 10_02.TXT: 1510 filas leídas / 1 omitidas
✔️ Ap pagados 11_02.TXT: 614 filas leídas / 1 omitidas
✔️ Comparedos pagados 11_02.TXT: 1347 filas leídas / 1 omitidas
✔️ Ap pagados 01_02 al 12_02.TXT: 5674 filas leídas / 1 omitidas
✔️ Ap pagados 12_02.TXT: 582 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_02 al 12_02.TXT: 13760 filas leídas / 1 omitidas
✔️ Comparendos pagados 12_02.TXT: 1250 filas leídas / 1 omitidas
✔️ Ap pagados 13_02.TXT: 692 filas leídas / 1 omitidas
✔️ Comparendos pagados 13_02.TXT: 1265 filas leídas / 1 omitidas
✔️ Ap pagados 14_02.TXT: 714 filas leídas / 1 omitidas
✔️ Comparendos pagados 14_02.TXT: 1257 filas leídas / 1 omitidas
✔️ Ap pagados 15_02 al 16_02.TXT: 487 filas leídas / 1 omitidas
✔️ Comparendos pagados 15_02 al 16_02.TXT: 580 filas leídas / 1 omitidas
✔️ Ap pagados 17_02.TXT: 1027 filas leídas / 1 omitidas
✔️ Comparendos pagados 17_02.TXT: 1307 filas leídas / 1 omitidas
✔️ Ap pagados 18_02.TXT: 649 filas leídas / 1 omitidas
✔️ Comparendos pagados 18_02.TXT: 1122 filas leídas / 1 omitidas
✔️ Ap pagados 19_02.TXT: 504 filas leídas / 1 omitidas
✔️ Comparendos pagados 19_02.TXT: 1533 filas leídas / 1 omitidas
✔️ Ap pagados 20_02.TXT: 519 filas leídas / 1 omitidas
✔️ Comparendos pagados 20_02.TXT: 1410 filas leídas / 1 omitidas
✔️ Ap pagados 20_02.TXT: 519 filas leídas / 1 omitidas
✔️ Comparendos pagados 20_02.TXT: 1410 filas leídas / 1 omitidas
✔️ Ap pagados 21_02 al 23_02.TXT: 761 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_02 al 23_02.TXT: 2019 filas leídas / 1 omitidas
✔️ Ap pagados 24_02.TXT: 615 filas leídas / 1 omitidas
✔️ Comparendos pagados 24_02.TXT: 1423 filas leídas / 1 omitidas
✔️ Ap pagados 25_02.TXT: 448 filas leídas / 1 omitidas
✔️ Comparendos pagados 25_02.TXT: 1343 filas leídas / 1 omitidas
✔️ Ap pagados 26_02.TXT: 399 filas leídas / 1 omitidas
✔️ Comparendos pagados 26_02.TXT: 1366 filas leídas / 1 omitidas
✔️ Ap pagados 27_02.TXT: 601 filas leídas / 1 omitidas
✔️ Comparendos pagados 27_02.TXT: 1410 filas leídas / 1 omitidas
✔️ Ap pagados 01_05 al 31_05.TXT: 17136 filas leídas / 1 omitidas
✔️ Ap pagados 01_06 al 02_06.TXT: 315 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_05 al 31_05.TXT: 29782 filas leídas / 2 omitidas
✔️ Comparendos pagados 01_06 al 02_06.TXT: 104 filas leídas / 1 omitidas
✔️ Ap pagados 03_06.TXT: 827 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_06.TXT: 1226 filas leídas / 1 omitidas
✔️ Ap pagados 04_06.TXT: 785 filas leídas / 1 omitidas
✔️ Comparendos pagados 04_06.TXT: 1541 filas leídas / 1 omitidas
✔️ Ap pagados 05_06.TXT: 794 filas leídas / 1 omitidas
✔️ Comparendos pagados 05_06.TXT: 1443 filas leídas / 1 omitidas
✔️ Ap pagados 06_06 al 08_06.TXT: 1105 filas leídas / 1 omitidas
✔️ Comparendos pagados 06_06 al 08_06.TXT: 1897 filas leídas / 1 omitidas
✔️ Ap pagados 09_06.TXT: 850 filas leídas / 1 omitidas
✔️ Comparendos pagados 09_06.TXT: 1912 filas leídas / 1 omitidas
✔️ Ap pagados 10_06.TXT: 646 filas leídas / 1 omitidas
✔️ Comparendos pagados 10_06.TXT: 1332 filas leídas / 1 omitidas
✔️ Ap pagados 11_06.TXT: 543 filas leídas / 1 omitidas
✔️ Comparendos pagados 11_06.TXT: 1270 filas leídas / 1 omitidas
✔️ Ap pagados 12_06.TXT: 536 filas leídas / 1 omitidas
✔️ Comparendos pagados 12_06.TXT: 1204 filas leídas / 1 omitidas
✔️ Ap pagados 01_06 al 15_06.TXT: 7708 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_06 al 15_06.TXT: 13923 filas leídas / 1 omitidas
✔️ Ap pagados 16_06.TXT: 1140 filas leídas / 1 omitidas
✔️ Comparendos pagados 16_06.TXT: 1399 filas leídas / 1 omitidas
✔️ Ap pagados 17_06.TXT: 733 filas leídas / 1 omitidas
✔️ Comparendos pagados 17_06.TXT: 1499 filas leídas / 1 omitidas
✔️ Ap pagados 18_06.TXT: 553 filas leídas / 1 omitidas
✔️ Comparendos pagados 18_06.TXT: 1389 filas leídas / 1 omitidas
✔️ Ap pagados 19_06.TXT: 649 filas leídas / 1 omitidas
✔️ Comparendos pagados 19_06.TXT: 1221 filas leídas / 1 omitidas
✔️ Ap pagados 20_06.TXT: 660 filas leídas / 1 omitidas
✔️ Comparendos pagados 20_06.TXT: 1292 filas leídas / 1 omitidas
✔️ Ap pagados 21_06 al 23_06.TXT: 197 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_06 al 23_06.TXT: 532 filas leídas / 1 omitidas
✔️ Ap pagados 01_02 al 28_02.TXT: 13625 filas leídas / 1 omitidas
✔️ Ap pagados 28_02.TXT: 756 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_02 al 28_02.TXT: 31108 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_02.TXT: 1311 filas leídas / 1 omitidas
✔️ Ap pagados 01_03 al 02_03.TXT: 573 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 02_03.TXT: 786 filas leídas / 1 omitidas
✔️ Ap pagados 03_03.TXT: 1076 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_03.TXT: 1378 filas leídas / 1 omitidas
✔️ Ap pagados 04_03.TXT: 673 filas leídas / 1 omitidas
✔️ Comparendos pagados 04_03.TXT: 2301 filas leídas / 1 omitidas
✔️ Ap pagados 05_03.TXT: 672 filas leídas / 1 omitidas
✔️ Comparendos pagados 05_03.TXT: 2196 filas leídas / 1 omitidas
✔️ AP pagados 06_03_2024.TXT: 717 filas leídas / 1 omitidas
✔️ Comparendos pagados 06_03_2024.TXT: 1665 filas leídas / 1 omitidas
✔️ Ap pagados 07_03.TXT: 589 filas leídas / 1 omitidas
✔️ Comparendos pagados 07_03.TXT: 1517 filas leídas / 1 omitidas
✔️ Ap pagados 08_03 al 09_03.TXT: 284 filas leídas / 1 omitidas
✔️ Comparendos pagados 08_03 al 09_03.TXT: 571 filas leídas / 1 omitidas
✔️ Ap pagados 10_03.TXT: 786 filas leídas / 1 omitidas
✔️ Comparendos pagados 10_03.TXT: 1329 filas leídas / 1 omitidas
✔️ Ap pagados 11_03.TXT: 578 filas leídas / 1 omitidas
✔️ Comparendos pagados 11_03.TXT: 1463 filas leídas / 1 omitidas
✔️ Ap pagados 12_03.TXT: 601 filas leídas / 1 omitidas
✔️ Comparendos pagados 12_03.TXT: 1513 filas leídas / 1 omitidas
✔️ Ap pagados 13_03.TXT: 531 filas leídas / 1 omitidas
✔️ Comparendos pagados 13_03.TXT: 1561 filas leídas / 1 omitidas
✔️ Ap pagados 01_03 al 16_03.TXT: 8046 filas leídas / 1 omitidas
✔️ Ap pagados 14_03 al 16_03.TXT: 1254 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 16_03.TXT: 18649 filas leídas / 1 omitidas
✔️ Comparendos pagados 14_03 al 16_03.TXT: 2374 filas leídas / 1 omitidas
✔️ Ap pagados 17_03.TXT: 1173 filas leídas / 1 omitidas
✔️ Comparendos pagados 17_03.TXT: 1924 filas leídas / 1 omitidas
✔️ Ap pagados 01_03 al 18_03.TXT: 9806 filas leídas / 1 omitidas
✔️ Ap pagados 18_03.TXT: 784 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 18_03.TXT: 22348 filas leídas / 1 omitidas
✔️ Comparendos pagados 18_03.TXT: 1775 filas leídas / 1 omitidas
✔️ Ap pagados 19_03.TXT: 608 filas leídas / 1 omitidas
✔️ Comparendos pagados 19_03.TXT: 1200 filas leídas / 1 omitidas
✔️ Ap pagados 20_03.TXT: 537 filas leídas / 1 omitidas
✔️ Comparendos pagados 20_03.TXT: 1238 filas leídas / 1 omitidas
✔️ Ap pagados 21_03.TXT: 596 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_03.TXT: 1304 filas leídas / 1 omitidas
✔️ Ap pagados 22_03 al 24_03.TXT: 379 filas leídas / 1 omitidas
✔️ Comparendos pagados 22_03 al 24_03.TXT: 547 filas leídas / 1 omitidas
✔️ Ap pagados 25_03.TXT: 614 filas leídas / 1 omitidas
✔️ Comparendos pagados 25_03.TXT: 1264 filas leídas / 1 omitidas
✔️ Ap pagados 26_03.TXT: 632 filas leídas / 1 omitidas
✔️ Comparendos pagados 26_03.TXT: 1423 filas leídas / 1 omitidas
✔️ Ap pagados 27_03.TXT: 589 filas leídas / 1 omitidas
✔️ Comparendos pagados 27_03.TXT: 1504 filas leídas / 1 omitidas
✔️ Ap pagados 27_03.TXT: 589 filas leídas / 1 omitidas
✔️ Comparendos pagados 27_03.TXT: 1504 filas leídas / 1 omitidas
✔️ Ap pagados 01_03 al 30_03.TXT: 14820 filas leídas / 1 omitidas
✔️ Ap pagados 28_03 al 30_03.TXT: 1059 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 30_03.TXT: 33046 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_03 al 30_03.TXT: 2220 filas leídas / 1 omitidas
✔️ Ap pagados 01_04 al 30_04.TXT: 15096 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_04 al 30_04.TXT: 29043 filas leídas / 2 omitidas
✔️ Ap pagados 01_05 al 02_05.TXT: 1104 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_05 al 02_05.TXT: 1482 filas leídas / 1 omitidas
✔️ Ap pagados 03_05 al 04_05.TXT: 486 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_05 al 04_05.TXT: 545 filas leídas / 1 omitidas
✔️ Ap pagados 05_05.TXT: 1069 filas leídas / 1 omitidas
✔️ Comparendos pagados 05_05.TXT: 1360 filas leídas / 1 omitidas
✔️ Ap pagados 06_05.TXT: 938 filas leídas / 1 omitidas
✔️ Comparendos pagados 06_05.TXT: 1392 filas leídas / 1 omitidas
✔️ Ap pagados 07_05.TXT: 750 filas leídas / 1 omitidas
✔️ Comparendos pagados 07_05.TXT: 1375 filas leídas / 1 omitidas
✔️ Ap pagados 08_05.TXT: 653 filas leídas / 1 omitidas
✔️ Comparendos pagados 08_05.TXT: 1178 filas leídas / 1 omitidas
✔️ Ap pagados 09_05 al 11_09.TXT: 947 filas leídas / 1 omitidas
✔️ Comparendos pagados 09_05 al 11_09.TXT: 1927 filas leídas / 1 omitidas
✔️ Ap pagados 12_05.TXT: 734 filas leídas / 1 omitidas
✔️ Comparendos pagados 12_05.TXT: 1359 filas leídas / 1 omitidas
✔️ Ap pagados 13_05.TXT: 623 filas leídas / 1 omitidas
✔️ Comparendos pagados 13_05.TXT: 1319 filas leídas / 1 omitidas
✔️ Ap pagados 14_05.TXT: 571 filas leídas / 1 omitidas
✔️ Comparendos pagados 14_05.TXT: 1387 filas leídas / 1 omitidas
✔️ Ap pagados 01_05 al 15_05.TXT: 8487 filas leídas / 1 omitidas
✔️ Ap pagados 15_05.TXT: 793 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_05 al 15_05.TXT: 14928 filas leídas / 1 omitidas
✔️ Comparendos pagados 15_05.TXT: 1612 filas leídas / 1 omitidas
✔️ Ap pagados 16_05.TXT: 763 filas leídas / 1 omitidas
✔️ Comparendos pagados 16_05.TXT: 1754 filas leídas / 1 omitidas
✔️ Ap pagados 17_05 al 18_05.TXT: 421 filas leídas / 1 omitidas
✔️ Comparendos pagados 17_05 al 18_05.TXT: 706 filas leídas / 1 omitidas
✔️ Ap pagados 19_05.TXT: 739 filas leídas / 1 omitidas
✔️ Comparendos pagados 19_05.TXT: 1269 filas leídas / 1 omitidas
✔️ Ap pagados 20_05.TXT: 682 filas leídas / 1 omitidas
✔️ Comparendos pagados 20_05.TXT: 1096 filas leídas / 1 omitidas
✔️ Ap pagados 21_05.TXT: 616 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_05.TXT: 1147 filas leídas / 2 omitidas
✔️ Ap pagados 22_05.TXT: 626 filas leídas / 1 omitidas
✔️ Comparendos pagados 22_05.TXT: 1155 filas leídas / 1 omitidas
✔️ Ap pagados 23_05 al 25_05.TXT: 909 filas leídas / 1 omitidas
✔️ Comparendos pagados 23_05 al 25_05.TXT: 1519 filas leídas / 1 omitidas
✔️ Ap pagados 26_05.TXT: 735 filas leídas / 1 omitidas
✔️ Comparendos pagados 26_05.TXT: 1126 filas leídas / 1 omitidas
✔️ Ap pagados 27_05.TXT: 634 filas leídas / 1 omitidas
✔️ Comparendos pagados 27_05.TXT: 1182 filas leídas / 1 omitidas
✔️ Ap pagados 28_05.TXT: 592 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_05.TXT: 1120 filas leídas / 1 omitidas
✔️ Ap pagados 29_05.TXT: 625 filas leídas / 1 omitidas
✔️ Comparendos pagados 29_05.TXT: 1132 filas leídas / 1 omitidas
✔️ Ap pagados 30_05.TXT: 910 filas leídas / 1 omitidas
✔️ Comparendos pagados 30_05.TXT: 1164 filas leídas / 1 omitidas

📊 Archivos leídos: 295
📂 Filas totales consolidadas: 885517

In [1]:
import os
import pandas as pd
import csv

# Ruta base
ruta_raiz = r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos\2025"

# Listas para guardar data y resumen
dataframes = []
resumen = []

for carpeta, subcarpetas, archivos in os.walk(ruta_raiz):
    for archivo in archivos:
        if archivo.lower().endswith('.txt'):
            ruta_archivo = os.path.join(carpeta, archivo)
            try:
                # Contar líneas totales del archivo
                with open(ruta_archivo, 'r', encoding='latin1', errors='ignore') as f:
                    total_lineas = sum(1 for _ in f)

                # Leer el archivo con pandas
                df = pd.read_csv(
                    ruta_archivo,
                    encoding='latin1',
                    quoting=csv.QUOTE_NONE,
                    sep=None,
                    engine='python',
                    on_bad_lines='skip'
                )

                filas_leidas = len(df)
                filas_omitidas = total_lineas - filas_leidas

                # Guardar DataFrame para concatenar luego
                dataframes.append(df)

                # Guardar info en resumen
                resumen.append({
                    'archivo': archivo,
                    'lineas_totales': total_lineas,
                    'filas_leidas': filas_leidas,
                    'filas_omitidas': filas_omitidas
                })

                print(f"✔️ {archivo}: {filas_leidas} filas leídas / {filas_omitidas} omitidas")

            except Exception as e:
                print(f"❌ Error con {archivo}: {e}")

# Concatenar todos los DataFrames leídos
df_consolidado = pd.concat(dataframes, ignore_index=True)

# Mostrar resumen final
print("\n📊 Resumen de archivos leídos:")
for r in resumen:
    print(f"{r['archivo']}: {r['filas_omitidas']} omitidas de {r['lineas_totales']} líneas")

# Opcional: convertir el resumen a un DataFrame
df_resumen = pd.DataFrame(resumen)

✔️ Ap pagados 31_03.TXT: 989 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 31_03.TXT: 34580 filas leídas / 1 omitidas
✔️ Comparendos pagados 31_03.TXT: 1534 filas leídas / 1 omitidas
✔️ Ap pagados 01_04.TXT: 731 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_04.TXT: 1539 filas leídas / 1 omitidas
✔️ Ap pagados 02_03.TXT: 563 filas leídas / 1 omitidas
✔️ Comparendos pagados 02_03.TXT: 1559 filas leídas / 1 omitidas
✔️ Ap pagados 01_03 al 31_03.TXT: 15646 filas leídas / 1 omitidas
✔️ Ap pagados 03_04.TXT: 756 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 31_03.TXT: 34580 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_04.TXT: 1419 filas leídas / 1 omitidas
✔️ Ap pagados 04_04.TXT: 761 filas leídas / 1 omitidas
✔️ Comparendos pagados 04_04.TXT: 1497 filas leídas / 1 omitidas
✔️ Ap pagados 05_04 al 06_04.TXT: 391 filas leídas / 1 omitidas
✔️ Comparendos pagados 05_04 al 06_04.TXT: 622 filas leídas / 2 omitidas
✔️ Ap pagados 07_04.TXT: 846 filas leídas / 1 omitidas
✔️ Comparendos pagados 07_04.TXT: 1400 filas leídas / 1 omitidas
✔️ Ap pagados 08_04.TXT: 659 filas leídas / 1 omitidas
✔️ Comparendos pagados 08_04.TXT: 1584 filas leídas / 1 omitidas
✔️ Ap pagados 09_04.TXT: 606 filas leídas / 1 omitidas
✔️ Comparendos pagados 09_04.TXT: 1494 filas leídas / 1 omitidas
✔️ Ap pagados 10_04.TXT: 529 filas leídas / 1 omitidas
✔️ Comparendos pagados 10_04.TXT: 1376 filas leídas / 1 omitidas
✔️ Ap pagados 11_04.TXT: 446 filas leídas / 1 omitidas
✔️ Comparendos pagados 11_04.TXT: 1295 filas leídas / 1 omitidas
✔️ Ap pagados 01_04 al 13_04.TXT: 6665 filas leídas / 1 omitidas
✔️ Ap pagados 12_04 al 13_04.TXT: 377 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_04 al 13_04.TXT: 14487 filas leídas / 2 omitidas
✔️ Comparendos pagados 12_04 al 13_04.TXT: 702 filas leídas / 1 omitidas
✔️ Ap pagados 14_04.TXT: 641 filas leídas / 1 omitidas
✔️ Comparendos pagados 14_04.TXT: 1435 filas leídas / 1 omitidas
✔️ Ap pagados 15_04.TXT: 703 filas leídas / 1 omitidas
✔️ Comparendos pagados 15_04.TXT: 1265 filas leídas / 1 omitidas
✔️ Ap pagados 01_04 al 20_04.TXT: 9142 filas leídas / 1 omitidas
✔️ Ap pagados 16_04 al 20_04.TXT: 1227 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_04 al 20_04.TXT: 18684 filas leídas / 2 omitidas
✔️ Comparendos pagados 16_04 al 20_04.TXT: 1497 filas leídas / 1 omitidas
✔️ Ap pagados 21_04.TXT: 1031 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_04.TXT: 1205 filas leídas / 1 omitidas
✔️ Ap pagados 22_04.TXT: 682 filas leídas / 1 omitidas
✔️ Comparendos pagados 22_04.TXT: 1440 filas leídas / 1 omitidas
✔️ Ap pagados 23_04.TXT: 635 filas leídas / 1 omitidas
✔️ Comparendos pagados 23_04.TXT: 1560 filas leídas / 1 omitidas
✔️ Ap pagados 01_04 al 24_04.TXT: 11995 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_04 al 24_04.TXT: 24210 filas leídas / 2 omitidas
✔️ Ap pagados 25_04 al 27_04.TXT: 910 filas leídas / 1 omitidas
✔️ Comparendos pagados 25_04 al 27_04.TXT: 1625 filas leídas / 1 omitidas
✔️ Ap pagados 28_04.TXT: 718 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_04.TXT: 1050 filas leídas / 1 omitidas
✔️ Ap pagados 29_04.TXT: 608 filas leídas / 1 omitidas
✔️ Comparendos pagados 29_04.TXT: 1115 filas leídas / 1 omitidas
✔️ Ap pagados 01_12 al 31_12.TXT: 11471 filas leídas / 1 omitidas
✔️ Ap pagados 31_12 al 01_01.TXT: 172 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_12 al 31_12.TXT: 29255 filas leídas / 2 omitidas
✔️ Comparendos pagados 31_12 al 01_01.TXT: 62 filas leídas / 1 omitidas
✔️ Ap pagados 02_01.TXT: 1117 filas leídas / 1 omitidas
✔️ Comparendos pagados 02_01.TXT: 2157 filas leídas / 1 omitidas
✔️ Ap pagados 03_01.TXT: 658 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_01.TXT: 930 filas leídas / 1 omitidas
✔️ Ap pagados 04_01 al 06_01.TXT: 551 filas leídas / 1 omitidas
✔️ Comparendos pagados 04_01 al 06_01.TXT: 548 filas leídas / 1 omitidas
✔️ Ap pagados 07_01.TXT: 1015 filas leídas / 1 omitidas
✔️ Comparendos pagados 07_01.TXT: 1321 filas leídas / 1 omitidas
✔️ Ap pagados 08_01.TXT: 660 filas leídas / 1 omitidas
✔️ Comparendos pagados 08_01.TXT: 1254 filas leídas / 1 omitidas
✔️ Ap pagados 09_01.TXT: 685 filas leídas / 1 omitidas
✔️ Comparendos pagados 09_01.TXT: 1265 filas leídas / 1 omitidas
✔️ Ap pagados 10_ al 12_01.TXT: 865 filas leídas / 1 omitidas
✔️ Comparendos pagados 10_ al 12_01.TXT: 1760 filas leídas / 1 omitidas
✔️ Ap pagados 13_01.TXT: 732 filas leídas / 1 omitidas
✔️ Comparendos pagados 13_01.TXT: 1498 filas leídas / 1 omitidas
✔️ Ap pagados 14_01.TXT: 641 filas leídas / 1 omitidas
✔️ Comparendos pagados 14_01.TXT: 1557 filas leídas / 1 omitidas
✔️ Ap pagados 15_01.TXT: 710 filas leídas / 1 omitidas
✔️ Comparendos pagados 15_01.TXT: 1562 filas leídas / 1 omitidas
✔️ Ap pagados 16_01.TXT: 760 filas leídas / 1 omitidas
✔️ Comparendos pagados 16_01.TXT: 1680 filas leídas / 1 omitidas
✔️ Ap pagados 17_01.TXT: 595 filas leídas / 1 omitidas
✔️ Comparendos pagados 17_01.TXT: 1978 filas leídas / 1 omitidas
✔️ AP pagados 01_01  al 19_01.TXT: 8888 filas leídas / 1 omitidas
✔️ Ap pagados 18_01 al 19_01.TXT: 229 filas leídas / 1 omitidas
✔️ AP PAGADOS DEL 18_01 AL 19_01.TXT: 229 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_01 al 19_01.TXT: 18350 filas leídas / 1 omitidas
✔️ Comparendos pagados 18_01 al 19_01.TXT: 779 filas leídas / 1 omitidas
✔️ COMPARENDOS PAGADOS DEL 18_01 AL 19_01.TXT: 779 filas leídas / 1 omitidas
✔️ AP PAGADOS 20_01.TXT: 784 filas leídas / 1 omitidas
✔️ COMPARENDOS PAGADOS 20_01.TXT: 1622 filas leídas / 1 omitidas
✔️ A p pagados 21_01.TXT: 527 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_01.TXT: 1335 filas leídas / 1 omitidas
✔️ Ap pagados  22_01.TXT: 489 filas leídas / 1 omitidas
✔️ Comparendos pagados  22_01.TXT: 1428 filas leídas / 1 omitidas
✔️ Ap pagados 23_01.TXT: 480 filas leídas / 1 omitidas
✔️ Comparendos pagados 23_01.TXT: 1492 filas leídas / 1 omitidas
✔️ Ap pagados 01_01 al 26_01.TXT: 11830 filas leídas / 1 omitidas
✔️ Ap pagados 24_01 al 26_01.TXT: 662 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_01 al 26_01.TXT: 26299 filas leídas / 1 omitidas
✔️ Comparendos pagados 24_01 al 26_01.TXT: 2068 filas leídas / 1 omitidas
✔️ Ap pagados 27_01.TXT: 716 filas leídas / 1 omitidas
✔️ Comparendos pagados 27_01.TXT: 1664 filas leídas / 1 omitidas
✔️ Ap pagados 28_01.TXT: 428 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_01.TXT: 1156 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_01_V2.TXT: 1156 filas leídas / 1 omitidas
✔️ Ap pagados 29_01.TXT: 475 filas leídas / 1 omitidas
✔️ Comparendos pagados 29_01.TXT: 1993 filas leídas / 1 omitidas
✔️ Ap pagados 30_01.TXT: 671 filas leídas / 1 omitidas
✔️ Comparendo pagados 30_01.TXT: 1679 filas leídas / 1 omitidas
✔️ Ap pagados 31_01.TXT: 625 filas leídas / 1 omitidas
✔️ Comparendos pagados 31_01.TXT: 1528 filas leídas / 1 omitidas
✔️ Comparendos pagados del 01_01 al 31_01.TXT: 34318 filas leídas / 1 omitidas
✔️ Ap pagados 01_02 al 02_02.TXT: 402 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_02 al 02_02.TXT: 828 filas leídas / 1 omitidas
✔️ Ap pagados 03_02.TXT: 886 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_02.TXT: 1687 filas leídas / 1 omitidas
✔️ Ap pagados 04_02.TXT: 588 filas leídas / 1 omitidas
✔️ Comparendos pagados 04_02.TXT: 1633 filas leídas / 1 omitidas
✔️ Ap pagados 05_02.TXT: 707 filas leídas / 1 omitidas
✔️ Comparendos pagados 05_02.TXT: 1682 filas leídas / 1 omitidas
✔️ Ap pagados 06_02.TXT: 576 filas leídas / 1 omitidas
✔️ Comparendos pagados 06_02.TXT: 1527 filas leídas / 1 omitidas
✔️ Ap pagados 07_02 al 09_02.TXT: 765 filas leídas / 1 omitidas
✔️ Comparendos pagados 07_02 al 09_02.TXT: 2298 filas leídas / 1 omitidas
✔️ Ap pagados 10_02.TXT: 783 filas leídas / 1 omitidas
✔️ Comparendos pagados 10_02.TXT: 1510 filas leídas / 1 omitidas
✔️ Ap pagados 11_02.TXT: 614 filas leídas / 1 omitidas
✔️ Comparedos pagados 11_02.TXT: 1347 filas leídas / 1 omitidas
✔️ Ap pagados 01_02 al 12_02.TXT: 5674 filas leídas / 1 omitidas
✔️ Ap pagados 12_02.TXT: 582 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_02 al 12_02.TXT: 13760 filas leídas / 1 omitidas
✔️ Comparendos pagados 12_02.TXT: 1250 filas leídas / 1 omitidas
✔️ Ap pagados 13_02.TXT: 692 filas leídas / 1 omitidas
✔️ Comparendos pagados 13_02.TXT: 1265 filas leídas / 1 omitidas
✔️ Ap pagados 14_02.TXT: 714 filas leídas / 1 omitidas
✔️ Comparendos pagados 14_02.TXT: 1257 filas leídas / 1 omitidas
✔️ Ap pagados 15_02 al 16_02.TXT: 487 filas leídas / 1 omitidas
✔️ Comparendos pagados 15_02 al 16_02.TXT: 580 filas leídas / 1 omitidas
✔️ Ap pagados 17_02.TXT: 1027 filas leídas / 1 omitidas
✔️ Comparendos pagados 17_02.TXT: 1307 filas leídas / 1 omitidas
✔️ Ap pagados 18_02.TXT: 649 filas leídas / 1 omitidas
✔️ Comparendos pagados 18_02.TXT: 1122 filas leídas / 1 omitidas
✔️ Ap pagados 19_02.TXT: 504 filas leídas / 1 omitidas
✔️ Comparendos pagados 19_02.TXT: 1533 filas leídas / 1 omitidas
✔️ Ap pagados 20_02.TXT: 519 filas leídas / 1 omitidas
✔️ Comparendos pagados 20_02.TXT: 1410 filas leídas / 1 omitidas
✔️ Ap pagados 20_02.TXT: 519 filas leídas / 1 omitidas
✔️ Comparendos pagados 20_02.TXT: 1410 filas leídas / 1 omitidas
✔️ Ap pagados 21_02 al 23_02.TXT: 761 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_02 al 23_02.TXT: 2019 filas leídas / 1 omitidas
✔️ Ap pagados 24_02.TXT: 615 filas leídas / 1 omitidas
✔️ Comparendos pagados 24_02.TXT: 1423 filas leídas / 1 omitidas
✔️ Ap pagados 25_02.TXT: 448 filas leídas / 1 omitidas
✔️ Comparendos pagados 25_02.TXT: 1343 filas leídas / 1 omitidas
✔️ Ap pagados 26_02.TXT: 399 filas leídas / 1 omitidas
✔️ Comparendos pagados 26_02.TXT: 1366 filas leídas / 1 omitidas
✔️ Ap pagados 27_02.TXT: 601 filas leídas / 1 omitidas
✔️ Comparendos pagados 27_02.TXT: 1410 filas leídas / 1 omitidas
✔️ Ap pagados 01_05 al 31_05.TXT: 17136 filas leídas / 1 omitidas
✔️ Ap pagados 01_06 al 02_06.TXT: 315 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_05 al 31_05.TXT: 29782 filas leídas / 2 omitidas
✔️ Comparendos pagados 01_06 al 02_06.TXT: 104 filas leídas / 1 omitidas
✔️ Ap pagados 03_06.TXT: 827 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_06.TXT: 1226 filas leídas / 1 omitidas
✔️ Ap pagados 04_06.TXT: 785 filas leídas / 1 omitidas
✔️ Comparendos pagados 04_06.TXT: 1541 filas leídas / 1 omitidas
✔️ Ap pagados 05_06.TXT: 794 filas leídas / 1 omitidas
✔️ Comparendos pagados 05_06.TXT: 1443 filas leídas / 1 omitidas
✔️ Ap pagados 06_06 al 08_06.TXT: 1105 filas leídas / 1 omitidas
✔️ Comparendos pagados 06_06 al 08_06.TXT: 1897 filas leídas / 1 omitidas
✔️ Ap pagados 09_06.TXT: 850 filas leídas / 1 omitidas
✔️ Comparendos pagados 09_06.TXT: 1912 filas leídas / 1 omitidas
✔️ Ap pagados 10_06.TXT: 646 filas leídas / 1 omitidas
✔️ Comparendos pagados 10_06.TXT: 1332 filas leídas / 1 omitidas
✔️ Ap pagados 11_06.TXT: 543 filas leídas / 1 omitidas
✔️ Comparendos pagados 11_06.TXT: 1270 filas leídas / 1 omitidas
✔️ Ap pagados 12_06.TXT: 536 filas leídas / 1 omitidas
✔️ Comparendos pagados 12_06.TXT: 1204 filas leídas / 1 omitidas
✔️ Ap pagados 01_06 al 15_06.TXT: 7708 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_06 al 15_06.TXT: 13923 filas leídas / 1 omitidas
✔️ Ap pagados 16_06.TXT: 1140 filas leídas / 1 omitidas
✔️ Comparendos pagados 16_06.TXT: 1399 filas leídas / 1 omitidas
✔️ Ap pagados 17_06.TXT: 733 filas leídas / 1 omitidas
✔️ Comparendos pagados 17_06.TXT: 1499 filas leídas / 1 omitidas
✔️ Ap pagados 18_06.TXT: 553 filas leídas / 1 omitidas
✔️ Comparendos pagados 18_06.TXT: 1389 filas leídas / 1 omitidas
✔️ Ap pagados 19_06.TXT: 649 filas leídas / 1 omitidas
✔️ Comparendos pagados 19_06.TXT: 1221 filas leídas / 1 omitidas
✔️ Ap pagados 20_06.TXT: 660 filas leídas / 1 omitidas
✔️ Comparendos pagados 20_06.TXT: 1292 filas leídas / 1 omitidas
✔️ Ap pagados 21_06 al 23_06.TXT: 197 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_06 al 23_06.TXT: 532 filas leídas / 1 omitidas
✔️ Ap pagados 01_02 al 28_02.TXT: 13625 filas leídas / 1 omitidas
✔️ Ap pagados 28_02.TXT: 756 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_02 al 28_02.TXT: 31108 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_02.TXT: 1311 filas leídas / 1 omitidas
✔️ Ap pagados 01_03 al 02_03.TXT: 573 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 02_03.TXT: 786 filas leídas / 1 omitidas
✔️ Ap pagados 03_03.TXT: 1076 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_03.TXT: 1378 filas leídas / 1 omitidas
✔️ Ap pagados 04_03.TXT: 673 filas leídas / 1 omitidas
✔️ Comparendos pagados 04_03.TXT: 2301 filas leídas / 1 omitidas
✔️ Ap pagados 05_03.TXT: 672 filas leídas / 1 omitidas
✔️ Comparendos pagados 05_03.TXT: 2196 filas leídas / 1 omitidas
✔️ AP pagados 06_03_2024.TXT: 717 filas leídas / 1 omitidas
✔️ Comparendos pagados 06_03_2024.TXT: 1665 filas leídas / 1 omitidas
✔️ Ap pagados 07_03.TXT: 589 filas leídas / 1 omitidas
✔️ Comparendos pagados 07_03.TXT: 1517 filas leídas / 1 omitidas
✔️ Ap pagados 08_03 al 09_03.TXT: 284 filas leídas / 1 omitidas
✔️ Comparendos pagados 08_03 al 09_03.TXT: 571 filas leídas / 1 omitidas
✔️ Ap pagados 10_03.TXT: 786 filas leídas / 1 omitidas
✔️ Comparendos pagados 10_03.TXT: 1329 filas leídas / 1 omitidas
✔️ Ap pagados 11_03.TXT: 578 filas leídas / 1 omitidas
✔️ Comparendos pagados 11_03.TXT: 1463 filas leídas / 1 omitidas
✔️ Ap pagados 12_03.TXT: 601 filas leídas / 1 omitidas
✔️ Comparendos pagados 12_03.TXT: 1513 filas leídas / 1 omitidas
✔️ Ap pagados 13_03.TXT: 531 filas leídas / 1 omitidas
✔️ Comparendos pagados 13_03.TXT: 1561 filas leídas / 1 omitidas
✔️ Ap pagados 01_03 al 16_03.TXT: 8046 filas leídas / 1 omitidas
✔️ Ap pagados 14_03 al 16_03.TXT: 1254 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 16_03.TXT: 18649 filas leídas / 1 omitidas
✔️ Comparendos pagados 14_03 al 16_03.TXT: 2374 filas leídas / 1 omitidas
✔️ Ap pagados 17_03.TXT: 1173 filas leídas / 1 omitidas
✔️ Comparendos pagados 17_03.TXT: 1924 filas leídas / 1 omitidas
✔️ Ap pagados 01_03 al 18_03.TXT: 9806 filas leídas / 1 omitidas
✔️ Ap pagados 18_03.TXT: 784 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 18_03.TXT: 22348 filas leídas / 1 omitidas
✔️ Comparendos pagados 18_03.TXT: 1775 filas leídas / 1 omitidas
✔️ Ap pagados 19_03.TXT: 608 filas leídas / 1 omitidas
✔️ Comparendos pagados 19_03.TXT: 1200 filas leídas / 1 omitidas
✔️ Ap pagados 20_03.TXT: 537 filas leídas / 1 omitidas
✔️ Comparendos pagados 20_03.TXT: 1238 filas leídas / 1 omitidas
✔️ Ap pagados 21_03.TXT: 596 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_03.TXT: 1304 filas leídas / 1 omitidas
✔️ Ap pagados 22_03 al 24_03.TXT: 379 filas leídas / 1 omitidas
✔️ Comparendos pagados 22_03 al 24_03.TXT: 547 filas leídas / 1 omitidas
✔️ Ap pagados 25_03.TXT: 614 filas leídas / 1 omitidas
✔️ Comparendos pagados 25_03.TXT: 1264 filas leídas / 1 omitidas
✔️ Ap pagados 26_03.TXT: 632 filas leídas / 1 omitidas
✔️ Comparendos pagados 26_03.TXT: 1423 filas leídas / 1 omitidas
✔️ Ap pagados 27_03.TXT: 589 filas leídas / 1 omitidas
✔️ Comparendos pagados 27_03.TXT: 1504 filas leídas / 1 omitidas
✔️ Ap pagados 27_03.TXT: 589 filas leídas / 1 omitidas
✔️ Comparendos pagados 27_03.TXT: 1504 filas leídas / 1 omitidas
✔️ Ap pagados 01_03 al 30_03.TXT: 14820 filas leídas / 1 omitidas
✔️ Ap pagados 28_03 al 30_03.TXT: 1059 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_03 al 30_03.TXT: 33046 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_03 al 30_03.TXT: 2220 filas leídas / 1 omitidas
✔️ Ap pagados 01_04 al 30_04.TXT: 15096 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_04 al 30_04.TXT: 29043 filas leídas / 2 omitidas
✔️ Ap pagados 01_05 al 02_05.TXT: 1104 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_05 al 02_05.TXT: 1482 filas leídas / 1 omitidas
✔️ Ap pagados 03_05 al 04_05.TXT: 486 filas leídas / 1 omitidas
✔️ Comparendos pagados 03_05 al 04_05.TXT: 545 filas leídas / 1 omitidas
✔️ Ap pagados 05_05.TXT: 1069 filas leídas / 1 omitidas
✔️ Comparendos pagados 05_05.TXT: 1360 filas leídas / 1 omitidas
✔️ Ap pagados 06_05.TXT: 938 filas leídas / 1 omitidas
✔️ Comparendos pagados 06_05.TXT: 1392 filas leídas / 1 omitidas
✔️ Ap pagados 07_05.TXT: 750 filas leídas / 1 omitidas
✔️ Comparendos pagados 07_05.TXT: 1375 filas leídas / 1 omitidas
✔️ Ap pagados 08_05.TXT: 653 filas leídas / 1 omitidas
✔️ Comparendos pagados 08_05.TXT: 1178 filas leídas / 1 omitidas
✔️ Ap pagados 09_05 al 11_09.TXT: 947 filas leídas / 1 omitidas
✔️ Comparendos pagados 09_05 al 11_09.TXT: 1927 filas leídas / 1 omitidas
✔️ Ap pagados 12_05.TXT: 734 filas leídas / 1 omitidas
✔️ Comparendos pagados 12_05.TXT: 1359 filas leídas / 1 omitidas
✔️ Ap pagados 13_05.TXT: 623 filas leídas / 1 omitidas
✔️ Comparendos pagados 13_05.TXT: 1319 filas leídas / 1 omitidas
✔️ Ap pagados 14_05.TXT: 571 filas leídas / 1 omitidas
✔️ Comparendos pagados 14_05.TXT: 1387 filas leídas / 1 omitidas
✔️ Ap pagados 01_05 al 15_05.TXT: 8487 filas leídas / 1 omitidas
✔️ Ap pagados 15_05.TXT: 793 filas leídas / 1 omitidas
✔️ Comparendos pagados 01_05 al 15_05.TXT: 14928 filas leídas / 1 omitidas
✔️ Comparendos pagados 15_05.TXT: 1612 filas leídas / 1 omitidas
✔️ Ap pagados 16_05.TXT: 763 filas leídas / 1 omitidas
✔️ Comparendos pagados 16_05.TXT: 1754 filas leídas / 1 omitidas
✔️ Ap pagados 17_05 al 18_05.TXT: 421 filas leídas / 1 omitidas
✔️ Comparendos pagados 17_05 al 18_05.TXT: 706 filas leídas / 1 omitidas
✔️ Ap pagados 19_05.TXT: 739 filas leídas / 1 omitidas
✔️ Comparendos pagados 19_05.TXT: 1269 filas leídas / 1 omitidas
✔️ Ap pagados 20_05.TXT: 682 filas leídas / 1 omitidas
✔️ Comparendos pagados 20_05.TXT: 1096 filas leídas / 1 omitidas
✔️ Ap pagados 21_05.TXT: 616 filas leídas / 1 omitidas
✔️ Comparendos pagados 21_05.TXT: 1147 filas leídas / 2 omitidas
✔️ Ap pagados 22_05.TXT: 626 filas leídas / 1 omitidas
✔️ Comparendos pagados 22_05.TXT: 1155 filas leídas / 1 omitidas
✔️ Ap pagados 23_05 al 25_05.TXT: 909 filas leídas / 1 omitidas
✔️ Comparendos pagados 23_05 al 25_05.TXT: 1519 filas leídas / 1 omitidas
✔️ Ap pagados 26_05.TXT: 735 filas leídas / 1 omitidas
✔️ Comparendos pagados 26_05.TXT: 1126 filas leídas / 1 omitidas
✔️ Ap pagados 27_05.TXT: 634 filas leídas / 1 omitidas
✔️ Comparendos pagados 27_05.TXT: 1182 filas leídas / 1 omitidas
✔️ Ap pagados 28_05.TXT: 592 filas leídas / 1 omitidas
✔️ Comparendos pagados 28_05.TXT: 1120 filas leídas / 1 omitidas
✔️ Ap pagados 29_05.TXT: 625 filas leídas / 1 omitidas
✔️ Comparendos pagados 29_05.TXT: 1132 filas leídas / 1 omitidas
✔️ Ap pagados 30_05.TXT: 910 filas leídas / 1 omitidas
✔️ Comparendos pagados 30_05.TXT: 1164 filas leídas / 1 omitidas

📊 Resumen de archivos leídos:
Ap pagados 31_03.TXT: 1 omitidas de 990 líneas
Comparendos pagados 01_03 al 31_03.TXT: 1 omitidas de 34581 líneas
Comparendos pagados 31_03.TXT: 1 omitidas de 1535 líneas
Ap pagados 01_04.TXT: 1 omitidas de 732 líneas
Comparendos pagados 01_04.TXT: 1 omitidas de 1540 líneas
Ap pagados 02_03.TXT: 1 omitidas de 564 líneas
Comparendos pagados 02_03.TXT: 1 omitidas de 1560 líneas
Ap pagados 01_03 al 31_03.TXT: 1 omitidas de 15647 líneas
Ap pagados 03_04.TXT: 1 omitidas de 757 líneas
Comparendos pagados 01_03 al 31_03.TXT: 1 omitidas de 34581 líneas
Comparendos pagados 03_04.TXT: 1 omitidas de 1420 líneas
Ap pagados 04_04.TXT: 1 omitidas de 762 líneas
Comparendos pagados 04_04.TXT: 1 omitidas de 1498 líneas
Ap pagados 05_04 al 06_04.TXT: 1 omitidas de 392 líneas
Comparendos pagados 05_04 al 06_04.TXT: 2 omitidas de 624 líneas
Ap pagados 07_04.TXT: 1 omitidas de 847 líneas
Comparendos pagados 07_04.TXT: 1 omitidas de 1401 líneas
Ap pagados 08_04.TXT: 1 omitidas de 660 líneas
Comparendos pagados 08_04.TXT: 1 omitidas de 1585 líneas
Ap pagados 09_04.TXT: 1 omitidas de 607 líneas
Comparendos pagados 09_04.TXT: 1 omitidas de 1495 líneas
Ap pagados 10_04.TXT: 1 omitidas de 530 líneas
Comparendos pagados 10_04.TXT: 1 omitidas de 1377 líneas
Ap pagados 11_04.TXT: 1 omitidas de 447 líneas
Comparendos pagados 11_04.TXT: 1 omitidas de 1296 líneas

In [2]:
df_consolidado.to_csv("consolidado_pagos_nuevo.csv", index=False)

# Funciona

In [1]:
import pandas as pd
import os
from pathlib import Path
import chardet
import hashlib
from datetime import datetime
import numpy as np
import re

# --- CONFIGURACIÓN ---
CARPETA_BASE = r"C:\Users\1513873.ANDESBPO\ANDES BPO S.A.S\Johan Felipe JG. Gómez Arango - SIMM\BASES\Pagos"

# --- VARIABLES GLOBALES ---
archivos_txt_con_datos = set()
archivos_txt_encontrados = set()

# --- FUNCIONES COMUNES ---
def detectar_encoding(archivo):
    with open(archivo, 'rb') as f:
        rawdata = f.read(100000)
    return chardet.detect(rawdata)['encoding']

def parse_fecha(fecha_str):
    if pd.isna(fecha_str) or fecha_str == '':
        return None
    formatos = [
        '%d/%m/%Y %H:%M:%S', '%Y-%m-%d %H:%M:%S', '%d/%m/%Y', 
        '%Y-%m-%d', '%m/%d/%Y', '%d-%m-%Y %H:%M:%S', '%Y/%m/%d %H:%M:%S'
    ]
    for fmt in formatos:
        try:
            return pd.to_datetime(fecha_str, format=fmt, errors='raise')
        except:
            continue
    return None

def limpiar_nombres(df, campos=['nombres', 'apellidos']):
    for col in campos:
        if col in df.columns:
            df[col] = (
                df[col].astype(str)
                .str.replace(r'[\t\n\r"]+', ' ', regex=True)
                .str.replace(r'\s+', ' ', regex=True)
                .str.strip()
            )
    return df

# --- PROCESAMIENTO ARCHIVOS ---
def procesar_archivo_ap(archivo):
    try:
        encoding = detectar_encoding(archivo)
        df = pd.read_csv(archivo, sep='\t', encoding=encoding, dtype=str)

        columnas = ['nro_acuerdo', 'id_usuario', 'nombres', 'apellidos', 'valor', 'fecha_liquida', 'consecutivo_cuota']
        df = df[[col for col in columnas if col in df.columns]]

        df['fecha_liquida'] = df['fecha_liquida'].apply(parse_fecha)

        df = limpiar_nombres(df)
        if 'nombres' in df.columns and 'apellidos' in df.columns:
            df['nombre_usuario'] = df['nombres'].str.cat(df['apellidos'], sep=' ', na_rep='').str.strip()
        else:
            df['nombre_usuario'] = ''
        df.drop(columns=[c for c in ['nombres', 'apellidos'] if c in df.columns], inplace=True)

        df['nro_acuerdo'] = df['nro_acuerdo'].astype(str)
        df['documento'] = df['id_usuario'].astype(str) if 'id_usuario' in df.columns else ''
        df['valor'] = pd.to_numeric(df['valor'], errors='coerce')

        df['archivo_origen'] = archivo.name
        df['fecha_carga'] = datetime.now()
        df['tipo_pago'] = 'AP'

        df['id_registro'] = df.apply(
            lambda x: hashlib.sha256(
                f"AP_{x.get('nro_acuerdo','')}_{x.get('documento','')}_{x.get('consecutivo_cuota','')}_{x.get('fecha_liquida','')}".encode()
            ).hexdigest(), axis=1
        )

        return df
    except Exception as e:
        print(f"Error procesando {archivo.name}: {e}")
        return pd.DataFrame()

def procesar_archivo_comparendos(archivo):
    try:
        encoding = detectar_encoding(archivo)
        df = pd.read_csv(archivo, sep='\t', encoding=encoding, dtype=str)

        columnas = ['nro_comparendo', 'nro_recibo', 'fecha_liquida_contrav',
                    'compute_0004', 'id_usuario', 'nombres', 'apellidos',
                    'nro_resolucion', 'intereses']
        df = df[[col for col in columnas if col in df.columns]]

        if 'fecha_liquida_contrav' in df.columns:
            df.rename(columns={'fecha_liquida_contrav': 'fecha_liquida'}, inplace=True)

        df['fecha_liquida'] = df['fecha_liquida'].apply(parse_fecha)

        if 'nro_comparendo' in df.columns and 'nro_resolucion' in df.columns:
            df['nro_comparendo'] = np.where(
                df['nro_comparendo'].isna() | (df['nro_comparendo'] == ''),
                df['nro_resolucion'], df['nro_comparendo']
            )

        df = limpiar_nombres(df)
        if 'nombres' in df.columns and 'apellidos' in df.columns:
            df['nombre_usuario'] = df['nombres'].str.cat(df['apellidos'], sep=' ', na_rep='').str.strip()
        else:
            df['nombre_usuario'] = ''
        df.drop(columns=[c for c in ['nombres', 'apellidos'] if c in df.columns], inplace=True)

        df['compute_0004'] = pd.to_numeric(df.get('compute_0004', 0), errors='coerce').fillna(0)
        df['intereses'] = pd.to_numeric(df.get('intereses', 0), errors='coerce').fillna(0)
        df['valor'] = df['compute_0004'] + df['intereses']

        df['documento'] = df['id_usuario'].astype(str) if 'id_usuario' in df.columns else ''
        df['archivo_origen'] = archivo.name
        df['fecha_carga'] = datetime.now()
        df['tipo_pago'] = 'COMP'

        df['id_registro'] = df.apply(
            lambda x: hashlib.sha256(
                f"COMP_{x.get('nro_comparendo','')}_{x.get('documento','')}_{x.get('valor','')}_{x.get('fecha_liquida','')}".encode()
            ).hexdigest(), axis=1
        )

        return df
    except Exception as e:
        print(f"Error procesando {archivo.name}: {e}")
        return pd.DataFrame()

# --- FUNCIONES DE PROCESAMIENTO ---
def obtener_todos_los_txt(carpeta_base):
    return [Path(root) / file
            for root, _, files in os.walk(carpeta_base)
            for file in files if file.lower().endswith('.txt')]

def buscar_y_procesar(tipo, patron_regex, funcion_procesar, nombre_salida):
    archivos_validos = [Path(root) / file
                        for root, _, files in os.walk(CARPETA_BASE)
                        for file in files if file.lower().endswith('.txt') and patron_regex.search(file)]
    
    print(f"\n[{tipo}]")
    print(f"- Archivos que coinciden con el patrón '{patron_regex.pattern}': {len(archivos_validos)}")
    
    dfs = []
    for archivo in archivos_validos:
        print(f"Procesando: {archivo.name}")
        path_str = str(archivo.resolve())
        archivos_txt_encontrados.add(path_str)
        
        df_temp = funcion_procesar(archivo)
        if not df_temp.empty:
            dfs.append(df_temp)
            archivos_txt_con_datos.add(path_str)

    if not dfs:
        print(f"No se encontraron datos válidos para [{tipo}].")
        return
    
    df_final = pd.concat(dfs, ignore_index=True)
    df_final.to_csv(f'{nombre_salida}_procesados.csv', index=False)

    df_filtrado = df_final.drop_duplicates(subset='id_registro')
    df_filtrado = df_filtrado[(df_filtrado['valor'] > 0) & df_filtrado['fecha_liquida'].notna()]
    
    print(f"[{tipo}] - Registros válidos: {len(df_filtrado)}")
    print(f"  • Valor mínimo: {df_filtrado['valor'].min():.2f}")
    print(f"  • Valor máximo: {df_filtrado['valor'].max():.2f}")
    print(f"  • Fecha más antigua: {df_filtrado['fecha_liquida'].min()}")
    print(f"  • Fecha más reciente: {df_filtrado['fecha_liquida'].max()}")

    df_filtrado.to_csv(f'{nombre_salida}_filtrados.csv', index=False)

# --- EJECUCIÓN ---
patron_ap = re.compile(r'\bap[\s_\-]*pa?g?[a-z]{2,}', re.IGNORECASE)
patron_comp = re.compile(r'(compa|compr)[a-z]*end?[oa]s?', re.IGNORECASE)

buscar_y_procesar('AP', patron_ap, procesar_archivo_ap, 'pagos_ap')
buscar_y_procesar('Comparendos', patron_comp, procesar_archivo_comparendos, 'pagos_comparendos')

# --- RESUMEN FINAL ---
todos_txt = obtener_todos_los_txt(CARPETA_BASE)
paths_totales = set(str(p.resolve()) for p in todos_txt)

archivos_no_procesados = sorted(paths_totales - archivos_txt_encontrados)
archivos_sin_datos = sorted(archivos_txt_encontrados - archivos_txt_con_datos)

print("\n======== RESUMEN GENERAL DEL PROCESAMIENTO ========")
print(f"- Total archivos .txt encontrados: {len(paths_totales)}")
print(f"- Archivos leídos (con patrón AP o Comparendos): {len(archivos_txt_encontrados)}")
print(f"- Archivos con registros válidos: {len(archivos_txt_con_datos)}")
print(f"- Archivos leídos sin datos válidos: {len(archivos_sin_datos)}")
print(f"- Archivos .txt que no fueron leídos (no coincidieron con patrones): {len(archivos_no_procesados)}")

# Mostrar ejemplos
if archivos_no_procesados:
    print("\n⚠️ Archivos NO leídos (no coincidieron con patrones):")
    for f in archivos_no_procesados[:10]:
        print(f"  ❌ {f}")
    if len(archivos_no_procesados) > 10:
        print(f"  ... y {len(archivos_no_procesados) - 10} más")

if archivos_sin_datos:
    print("\n⚠️ Archivos leídos pero SIN datos válidos:")
    for f in archivos_sin_datos[:10]:
        print(f"  ⚠️ {f}")
    if len(archivos_sin_datos) > 10:
        print(f"  ... y {len(archivos_sin_datos) - 10} más")

# Guardar resumen en .log
with open("resumen_procesamiento.log", "w", encoding="utf-8") as log:
    log.write("======== RESUMEN DEL PROCESAMIENTO ========\n")
    log.write(f"Total archivos .txt encontrados: {len(paths_totales)}\n")
    log.write(f"Archivos leídos (con patrón): {len(archivos_txt_encontrados)}\n")
    log.write(f"Archivos con datos válidos: {len(archivos_txt_con_datos)}\n")
    log.write(f"Archivos leídos sin datos válidos: {len(archivos_sin_datos)}\n")
    log.write(f"Archivos no leídos (no coincidieron con patrones): {len(archivos_no_procesados)}\n\n")

    if archivos_no_procesados:
        log.write("Archivos NO leídos:\n")
        for f in archivos_no_procesados:
            log.write(f"❌ {f}\n")
    if archivos_sin_datos:
        log.write("\nArchivos leídos sin datos válidos:\n")
        for f in archivos_sin_datos:
            log.write(f"⚠️ {f}\n")

[AP]
- Archivos que coinciden con el patrón '\bap[\s_\-]*pa?g?[a-z]{2,}': 156
Procesando: Ap pagados 31_03.TXT
Procesando: Ap pagados 01_04.TXT
Procesando: Ap pagados 02_03.TXT
Procesando: Ap pagados 01_03 al 31_03.TXT
Procesando: Ap pagados 03_04.TXT
Procesando: Ap pagados 04_04.TXT
Procesando: Ap pagados 05_04 al 06_04.TXT
Procesando: Ap pagados 07_04.TXT
Procesando: Ap pagados 08_04.TXT
Procesando: Ap pagados 09_04.TXT
Procesando: Ap pagados 10_04.TXT
Procesando: Ap pagados 11_04.TXT
Procesando: Ap pagados 01_04 al 13_04.TXT
Procesando: Ap pagados 12_04 al 13_04.TXT
Procesando: Ap pagados 14_04.TXT
Procesando: Ap pagados 15_04.TXT
Procesando: Ap pagados 01_04 al 20_04.TXT
Procesando: Ap pagados 16_04 al 20_04.TXT
Procesando: Ap pagados 21_04.TXT
Procesando: Ap pagados 22_04.TXT
Procesando: Ap pagados 23_04.TXT
Procesando: Ap pagados 01_04 al 24_04.TXT
Procesando: Ap pagados 25_04 al 27_04.TXT
Procesando: Ap pagados 28_04.TXT
Procesando: Ap pagados 29_04.TXT
Procesando: Ap pagados 01_12 al 31_12.TXT
Procesando: Ap pagados 31_12 al 01_01.TXT
Procesando: Ap pagados 02_01.TXT
Procesando: Ap pagados 03_01.TXT
Procesando: Ap pagados 04_01 al 06_01.TXT
Procesando: Ap pagados 07_01.TXT
Procesando: Ap pagados 08_01.TXT
Procesando: Ap pagados 09_01.TXT
Procesando: Ap pagados 10_ al 12_01.TXT
Procesando: Ap pagados 13_01.TXT
Procesando: Ap pagados 14_01.TXT
Procesando: Ap pagados 15_01.TXT
Procesando: Ap pagados 16_01.TXT
Procesando: Ap pagados 17_01.TXT
Procesando: AP pagados 01_01  al 19_01.TXT
Procesando: Ap pagados 18_01 al 19_01.TXT
Procesando: AP PAGADOS DEL 18_01 AL 19_01.TXT
Procesando: AP PAGADOS 20_01.TXT
Procesando: Ap pagados 21_01.TXT
Procesando: Ap pagados  22_01.TXT
Procesando: Ap pagados 23_01.TXT
Procesando: Ap pagados 01_01 al 26_01.TXT
Procesando: Ap pagados 24_01 al 26_01.TXT
Procesando: Ap pagados 27_01.TXT
Procesando: Ap pagados 28_01.TXT
Procesando: Ap pagados 29_01.TXT
Procesando: Ap pagados 30_01.TXT
Procesando: Ap pagados 31_01.TXT
Procesando: Ap pagados 01_02 al 02_02.TXT
Procesando: Ap pagados 03_02.TXT
Procesando: Ap pagados 04_02.TXT
Procesando: Ap pagados 05_02.TXT
Procesando: Ap pagados 06_02.TXT
Procesando: Ap pagados 07_02 al 09_02.TXT
Procesando: Ap pagados 10_02.TXT
Procesando: Ap pagados 11_02.TXT
Procesando: Ap pagados 01_02 al 12_02.TXT
Procesando: Ap pagados 12_02.TXT
Procesando: Ap pagados 13_02.TXT
Procesando: Ap pagados 14_02.TXT
Procesando: Ap pagados 15_02 al 16_02.TXT
Procesando: Ap pagados 17_02.TXT
Procesando: Ap pagados 18_02.TXT
Procesando: Ap pagados 19_02.TXT
Procesando: Ap pagados 20_02.TXT
Procesando: Ap pagados 20_02.TXT
Procesando: Ap pagados 21_02 al 23_02.TXT
Procesando: Ap pagados 24_02.TXT
Procesando: Ap pagados 25_02.TXT
Procesando: Ap pagados 26_02.TXT
Procesando: Ap pagados 27_02.TXT
Procesando: Ap pagados 01_06 al 30_06.TXT
Procesando: Ap pagados 27_06 al 30_06.TXT
Procesando: Ap pagados 01_07.TXT
Procesando: Ap pagados 01_06 al 30_06.TXT
Procesando: Ap pagados 27_06 al 30_06.TXT
Procesando: Ap pagados 01_07.TXT
Procesando: Ap pagados 02_07.TXT
Procesando: Ap pagados 01_05 al 31_05.TXT
Procesando: Ap pagados 01_06 al 02_06.TXT
Procesando: Ap pagados 03_06.TXT
Procesando: Ap pagados 04_06.TXT
Procesando: Ap pagados 05_06.TXT
Procesando: Ap pagados 06_06 al 08_06.TXT
Procesando: Ap pagados 09_06.TXT
Procesando: Ap pagados 10_06.TXT
Procesando: Ap pagados 11_06.TXT
Procesando: Ap pagados 12_06.TXT
Procesando: Ap pagados 01_06 al 15_06.TXT
Procesando: Ap pagados 16_06.TXT
Procesando: Ap pagados 17_06.TXT
Procesando: Ap pagados 18_06.TXT
Procesando: Ap pagados 19_06.TXT
Procesando: Ap pagados 20_06.TXT
Procesando: Ap pagados 21_06 al 23_06.TXT
Procesando: Ap pagados 24_06.TXT
Procesando: Ap pagados 25_06.TXT
Procesando: Ap pagados 25_06.TXT
Procesando: Ap pagados 01_02 al 28_02.TXT
Procesando: Ap pagados 28_02.TXT
Procesando: Ap pagados 01_03 al 02_03.TXT
Procesando: Ap pagados 03_03.TXT
Procesando: Ap pagados 04_03.TXT
Procesando: Ap pagados 05_03.TXT
Procesando: AP pagados 06_03_2024.TXT
Procesando: Ap pagados 07_03.TXT
Procesando: Ap pagados 08_03 al 09_03.TXT
Procesando: Ap pagados 10_03.TXT
Procesando: Ap pagados 11_03.TXT
Procesando: Ap pagados 12_03.TXT
Procesando: Ap pagados 13_03.TXT
Procesando: Ap pagados 01_03 al 16_03.TXT
Procesando: Ap pagados 14_03 al 16_03.TXT
Procesando: Ap pagados 17_03.TXT
Procesando: Ap pagados 01_03 al 18_03.TXT
Procesando: Ap pagados 18_03.TXT
Procesando: Ap pagados 19_03.TXT
Procesando: Ap pagados 20_03.TXT
Procesando: Ap pagados 21_03.TXT
Procesando: Ap pagados 22_03 al 24_03.TXT
Procesando: Ap pagados 25_03.TXT
Procesando: Ap pagados 26_03.TXT
Procesando: Ap pagados 27_03.TXT
Procesando: Ap pagados 27_03.TXT
Procesando: Ap pagados 01_03 al 30_03.TXT
Procesando: Ap pagados 28_03 al 30_03.TXT
Procesando: Ap pagados 01_04 al 30_04.TXT
Procesando: Ap pagados 01_05 al 02_05.TXT
Procesando: Ap pagados 03_05 al 04_05.TXT
Procesando: Ap pagados 05_05.TXT
Procesando: Ap pagados 06_05.TXT
Procesando: Ap pagados 07_05.TXT
Procesando: Ap pagados 08_05.TXT
Procesando: Ap pagados 09_05 al 11_09.TXT
Procesando: Ap pagados 12_05.TXT
Procesando: Ap pagados 13_05.TXT
Procesando: Ap pagados 14_05.TXT
Procesando: Ap pagados 01_05 al 15_05.TXT
Procesando: Ap pagados 15_05.TXT
Procesando: Ap pagados 16_05.TXT
Procesando: Ap pagados 17_05 al 18_05.TXT
Procesando: Ap pagados 19_05.TXT
Procesando: Ap pagados 20_05.TXT
Procesando: Ap pagados 21_05.TXT
Procesando: Ap pagados 22_05.TXT
Procesando: Ap pagados 23_05 al 25_05.TXT
Procesando: Ap pagados 26_05.TXT
Procesando: Ap pagados 27_05.TXT
Procesando: Ap pagados 28_05.TXT
Procesando: Ap pagados 29_05.TXT
Procesando: Ap pagados 30_05.TXT
[AP] - Registros válidos: 109654
  • Valor mínimo: 11155.00
  • Valor máximo: 31896783.00
  • Fecha más antigua: 2024-12-02 02:16:01
  • Fecha más reciente: 2025-07-02 23:06:01

[Comparendos]
- Archivos que coinciden con el patrón '(compa|compr)[a-z]*end?[oa]s?': 159
Procesando: Comparendos pagados 01_03 al 31_03.TXT
Procesando: Comparendos pagados 31_03.TXT
Procesando: Comparendos pagados 01_04.TXT
Procesando: Comparendos pagados 02_03.TXT
Procesando: Comparendos pagados 01_03 al 31_03.TXT
Procesando: Comparendos pagados 03_04.TXT
Procesando: Comparendos pagados 04_04.TXT
Procesando: Comparendos pagados 05_04 al 06_04.TXT
Procesando: Comparendos pagados 07_04.TXT
Procesando: Comparendos pagados 08_04.TXT
Procesando: Comparendos pagados 09_04.TXT
Procesando: Comparendos pagados 10_04.TXT
Procesando: Comparendos pagados 11_04.TXT
Procesando: Comparendos pagados 01_04 al 13_04.TXT
Procesando: Comparendos pagados 12_04 al 13_04.TXT
Procesando: Comparendos pagados 14_04.TXT
Procesando: Comparendos pagados 15_04.TXT
Procesando: Comparendos pagados 01_04 al 20_04.TXT
Procesando: Comparendos pagados 16_04 al 20_04.TXT
Procesando: Comparendos pagados 21_04.TXT
Procesando: Comparendos pagados 22_04.TXT
Procesando: Comparendos pagados 23_04.TXT
Procesando: Comparendos pagados 01_04 al 24_04.TXT
Procesando: Comparendos pagados 25_04 al 27_04.TXT
Procesando: Comparendos pagados 28_04.TXT
Procesando: Comparendos pagados 29_04.TXT
Procesando: Comparendos pagados 01_12 al 31_12.TXT
Procesando: Comparendos pagados 31_12 al 01_01.TXT
Procesando: Comparendos pagados 02_01.TXT
Procesando: Comparendos pagados 03_01.TXT
Procesando: Comparendos pagados 04_01 al 06_01.TXT
Procesando: Comparendos pagados 07_01.TXT
Procesando: Comparendos pagados 08_01.TXT
Procesando: Comparendos pagados 09_01.TXT
Procesando: Comparendos pagados 10_ al 12_01.TXT
Procesando: Comparendos pagados 13_01.TXT
Procesando: Comparendos pagados 14_01.TXT
Procesando: Comparendos pagados 15_01.TXT
Procesando: Comparendos pagados 16_01.TXT
Procesando: Comparendos pagados 17_01.TXT
Procesando: Comparendos pagados 01_01 al 19_01.TXT
Procesando: Comparendos pagados 18_01 al 19_01.TXT
Procesando: COMPARENDOS PAGADOS DEL 18_01 AL 19_01.TXT
Procesando: COMPARENDOS PAGADOS 20_01.TXT
Procesando: Comparendos pagados 21_01.TXT
Procesando: Comparendos pagados  22_01.TXT
Procesando: Comparendos pagados 23_01.TXT
Procesando: Comparendos pagados 01_01 al 26_01.TXT
Procesando: Comparendos pagados 24_01 al 26_01.TXT
Procesando: Comparendos pagados 27_01.TXT
Procesando: Comparendos pagados 28_01.TXT
Procesando: Comparendos pagados 28_01_V2.TXT
Procesando: Comparendos pagados 29_01.TXT
Procesando: Comparendo pagados 30_01.TXT
Procesando: Comparendos pagados 31_01.TXT
Procesando: Comparendos pagados del 01_01 al 31_01.TXT
Procesando: Comparendos pagados 01_02 al 02_02.TXT
Procesando: Comparendos pagados 03_02.TXT
Procesando: Comparendos pagados 04_02.TXT
Procesando: Comparendos pagados 05_02.TXT
Procesando: Comparendos pagados 06_02.TXT
Procesando: Comparendos pagados 07_02 al 09_02.TXT
Procesando: Comparendos pagados 10_02.TXT
Procesando: Comparendos pagados 11_02.TXT
Procesando: Comparendos pagados 01_02 al 12_02.TXT
Procesando: Comparendos pagados 12_02.TXT
Procesando: Comparendos pagados 13_02.TXT
Procesando: Comparendos pagados 14_02.TXT
Procesando: Comparendos pagados 15_02 al 16_02.TXT
Procesando: Comparendos pagados 17_02.TXT
Procesando: Comparendos pagados 18_02.TXT
Procesando: Comparendos pagados 19_02.TXT
Procesando: Comparendos pagados 20_02.TXT
Procesando: Comparendos pagados 20_02.TXT
Procesando: Comparendos pagados 21_02 al 23_02.TXT
Procesando: Comparendos pagados 24_02.TXT
Procesando: Comparendos pagados 25_02.TXT
Procesando: Comparendos pagados 26_02.TXT
Procesando: Comparendos pagados 27_02.TXT
Procesando: Comparendos pagados 01_06 al 30_06.TXT
Procesando: Comparendos pagados 27_06 al 30_06.TXT
Procesando: Comparendos pagados 01_07.TXT
Procesando: Comparendos pagados 01_06 al 30_06.TXT
Procesando: Comparendos pagados 27_06 al 30_06.TXT
Procesando: Comparendos pagados 01_07.TXT
Procesando: Comparendos pagados 02_07.TXT
Procesando: Comparendos pagados 01_05 al 31_05.TXT
Procesando: Comparendos pagados 01_06 al 02_06.TXT
Procesando: Comparendos pagados 03_06.TXT
Procesando: Comparendos pagados 04_06.TXT
Procesando: Comparendos pagados 05_06.TXT
Procesando: Comparendos pagados 06_06 al 08_06.TXT
Procesando: Comparendos pagados 09_06.TXT
Procesando: Comparendos pagados 10_06.TXT
Procesando: Comparendos pagados 11_06.TXT
Procesando: Comparendos pagados 12_06.TXT
Procesando: Comparendos pagados 01_06 al 15_06.TXT
Procesando: Comparendos pagados 16_06.TXT
Procesando: Comparendos pagados 17_06.TXT
Procesando: Comparendos pagados 18_06.TXT
Procesando: Comparendos pagados 19_06.TXT
Procesando: Comparendos pagados 20_06.TXT
Procesando: Comparendos pagados 21_06 al 23_06.TXT
Procesando: Comparendos pagados 24_06.TXT
Procesando: Comparendos pagados 25_06.TXT
Procesando: Comparendos pagados 25_06.TXT
Procesando: Comparendos pagados 01_02 al 28_02.TXT
Procesando: Comparendos pagados 28_02.TXT
Procesando: Comparendos pagados 01_03 al 02_03.TXT
Procesando: Comparendos pagados 03_03.TXT
Procesando: Comparendos pagados 04_03.TXT
Procesando: Comparendos pagados 05_03.TXT
Procesando: Comparendos pagados 06_03_2024.TXT
Procesando: Comparendos pagados 07_03.TXT
Procesando: Comparendos pagados 08_03 al 09_03.TXT
Procesando: Comparendos pagados 10_03.TXT
Procesando: Comparendos pagados 11_03.TXT
Procesando: Comparendos pagados 12_03.TXT
Procesando: Comparendos pagados 13_03.TXT
Procesando: Comparendos pagados 01_03 al 16_03.TXT
Procesando: Comparendos pagados 14_03 al 16_03.TXT
Procesando: Comparendos pagados 17_03.TXT
Procesando: Comparendos pagados 01_03 al 18_03.TXT
Procesando: Comparendos pagados 18_03.TXT
Procesando: Comparendos pagados 19_03.TXT
Procesando: Comparendos pagados 20_03.TXT
Procesando: Comparendos pagados 21_03.TXT
Procesando: Comparendos pagados 22_03 al 24_03.TXT
Procesando: Comparendos pagados 25_03.TXT
Procesando: Comparendos pagados 26_03.TXT
Procesando: Comparendos pagados 27_03.TXT
Procesando: Comparendos pagados 27_03.TXT
Procesando: Comparendos pagados 01_03 al 30_03.TXT
Procesando: Comparendos pagados 28_03 al 30_03.TXT
Procesando: Comparendos pagados 01_04 al 30_04.TXT
Procesando: Comparendos pagados 01_05 al 02_05.TXT
Procesando: Comparendos pagados 03_05 al 04_05.TXT
Procesando: Comparendos pagados 05_05.TXT
Procesando: Comparendos pagados 06_05.TXT
Procesando: Comparendos pagados 07_05.TXT
Procesando: Comparendos pagados 08_05.TXT
Procesando: Comparendos pagados 09_05 al 11_09.TXT
Procesando: Comparendos pagados 12_05.TXT
Procesando: Comparendos pagados 13_05.TXT
Procesando: Comparendos pagados 14_05.TXT
Procesando: Comparendos pagados 01_05 al 15_05.TXT
Procesando: Comparendos pagados 15_05.TXT
Procesando: Comparendos pagados 16_05.TXT
Procesando: Comparendos pagados 17_05 al 18_05.TXT
Procesando: Comparendos pagados 19_05.TXT
Procesando: Comparendos pagados 20_05.TXT
Procesando: Comparendos pagados 21_05.TXT
Procesando: Comparendos pagados 22_05.TXT
Procesando: Comparendos pagados 23_05 al 25_05.TXT
Procesando: Comparendos pagados 26_05.TXT
Procesando: Comparendos pagados 27_05.TXT
Procesando: Comparendos pagados 28_05.TXT
Procesando: Comparendos pagados 29_05.TXT
Procesando: Comparendos pagados 30_05.TXT
[Comparendos] - Registros válidos: 218777
  • Valor mínimo: 171.00
  • Valor máximo: 33094080.00
  • Fecha más antigua: 2024-12-01 09:45:24
  • Fecha más reciente: 2025-07-02 23:05:04

======== RESUMEN GENERAL DEL PROCESAMIENTO ========
- Total archivos .txt encontrados: 315
- Archivos leídos (con patrón AP o Comparendos): 315
- Archivos con registros válidos: 315
- Archivos leídos sin datos válidos: 0
- Archivos .txt que no fueron leídos (no coincidieron con patrones): 0